<?php

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

$router=new Router();

$router->get('/login',function():void{
    if(Auth::check()){header('Location: '.App::url('/'));exit;}
    $error=isset($_GET['error']);ob_start();?><section class="auth-card"><div class="auth-brand"><span class="mark">A</span><strong>ATLAS</strong></div><p class="eyebrow">Healthcare operations workspace</p><h1>Sign in</h1><p>One place for operational guidance, payer rules, playbooks, and patient education.</p><?php if($error):?><div class="alert">Email or password was not recognized.</div><?php endif;?><form class="auth-form" method="post" action="<?=App::e(App::url('/login'))?>"><?=Csrf::input()?><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="button" type="submit">Sign in</button></form></section><?php App::render('Sign in',(string)ob_get_clean(),false);
},false);

$router->post('/login',function():void{Csrf::verify($_POST['csrf']??null);if(Auth::attempt((string)($_POST['email']??''),(string)($_POST['password']??''))){header('Location: '.App::url('/'));exit;}header('Location: '.App::url('/login?error=1'));exit;},false);
$router->post('/logout',function():void{Csrf::verify($_POST['csrf']??null);Auth::logout();header('Location: '.App::url('/login'));exit;});

$router->get('/',function():void{
    $user=Auth::user();ob_start();?><section class="hero"><div><p class="eyebrow">Good afternoon</p><h1>Welcome back, <?=App::e((string)($user['display_name']??'Atlas User'))?>.</h1><p>Everything you need to move care forward, without hunting through five systems to find it.</p></div><div class="context-card"><span>Working in</span><strong>Atlas Demo Health</strong><small>Organization context will become server-authorized.</small></div></section><div class="metric-grid"><?php foreach(App::cards() as [$title,$desc,$path,$count]):?><a class="metric-card" href="<?=App::e(App::url($path))?>"><span class="metric-number"><?=App::e($count)?></span><div><strong><?=App::e($title)?></strong><p><?=App::e($desc)?></p></div></a><?php endforeach;?></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><p class="eyebrow">Pick up where you left off</p><h2>Recent work</h2></div></div><div class="list"><a href="<?=App::e(App::url('/resources/home-oxygen'))?>"><span class="pill">Resource</span><strong>Home Oxygen Qualification & Documentation</strong><small>Reviewed Jul 2026</small></a><a href="<?=App::e(App::url('/insurance'))?>"><span class="pill">Insurance</span><strong>Medicare DME: Oxygen</strong><small>Effective Jan 2026</small></a><a href="<?=App::e(App::url('/playbooks'))?>"><span class="pill">Playbook</span><strong>Arrange Home Oxygen</strong><small>7 steps</small></a></div></section><section class="panel"><p class="eyebrow">Start here</p><h2>Common actions</h2><div class="quick-grid"><a href="<?=App::e(App::url('/search'))?>">Search Atlas <span>→</span></a><a href="<?=App::e(App::url('/resources'))?>">Find a resource <span>→</span></a><a href="<?=App::e(App::url('/patient-resources'))?>">Patient education <span>→</span></a><a href="<?=App::e(App::url('/workspace'))?>">My workspace <span>→</span></a></div></section></div><?php App::render('Home',(string)ob_get_clean());
});

$router->get('/resources',function():void{
    $items=[['Home Oxygen Qualification & Documentation','DME','Practical guide to qualifying testing, documentation, and discharge coordination.','CMS Medicare Learning Network'],['Skilled Nursing Facility Placement Checklist','Post-acute','What to gather, confirm, and communicate before sending a post-acute referral.','Atlas Demo Health'],['Home Health Eligibility Guide','Home Health','Fast reference for homebound status, skilled need, and common referral pitfalls.','CMS'],['Non-Emergency Transportation Options','Transportation','Decision support based on mobility, payer, medical need, and destination.','Atlas Demo Health']];ob_start();?><section class="page-head"><div><p class="eyebrow">Resource Library</p><h1>Find the answer, then keep moving.</h1><p>Operational references with visible source and review context.</p></div><div class="count-card"><strong><?=count($items)?></strong><span>starter resources</span></div></section><div class="filterbar"><input placeholder="Search resources…"><select><option>All categories</option><option>DME</option><option>Post-acute</option><option>Home Health</option></select><button class="button">Search</button></div><div class="card-grid"><?php foreach($items as $i=>$item):?><article class="resource-card"><div><span class="pill"><?=App::e($item[1])?></span><span class="trust">● Reviewed</span></div><h2><?php if($i===0):?><a href="<?=App::e(App::url('/resources/home-oxygen'))?>"><?=App::e($item[0])?></a><?php else:?><?=App::e($item[0])?><?php endif;?></h2><p><?=App::e($item[2])?></p><footer><span><?=App::e($item[3])?></span><span>Open →</span></footer></article><?php endforeach;?></div><?php App::render('Resources',(string)ob_get_clean());
});

$router->get('/resources/home-oxygen',function():void{ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/resources'))?>">Resources</a><span>/</span><span>Home Oxygen</span></nav><section class="detail-head"><div><span class="pill">DME</span><h1>Home Oxygen Qualification & Documentation</h1><p>A practical guide to qualifying testing, documentation, and discharge coordination for home oxygen.</p></div><aside class="source-card"><span>Source</span><strong>CMS Medicare Learning Network</strong><small>Reviewed Jul 18, 2026</small></aside></section><div class="detail-grid"><div><section class="panel"><p class="eyebrow">At a glance</p><h2>Key points</h2><ul class="check-list"><li>Confirm qualifying clinical criteria before the patient leaves the care setting.</li><li>Match the order and supporting documentation to the payer requirement.</li><li>Make the qualifying result easy for the supplier to locate.</li></ul></section><section class="panel"><p class="eyebrow">Operational sequence</p><h2>From qualification to delivery</h2><ol class="steps"><li><span>1</span>Verify qualifying test or assessment.</li><li><span>2</span>Confirm prescriber documentation.</li><li><span>3</span>Identify an appropriate supplier.</li><li><span>4</span>Send the complete referral packet.</li><li><span>5</span>Confirm acceptance and delivery plan.</li></ol></section></div><aside class="panel"><p class="eyebrow">Connected in Atlas</p><h2>Related guidance</h2><a class="related" href="<?=App::e(App::url('/playbooks'))?>">Arrange Home Oxygen <span>→</span></a><a class="related" href="<?=App::e(App::url('/insurance'))?>">Medicare DME: Oxygen <span>→</span></a><a class="related" href="<?=App::e(App::url('/patient-resources'))?>">Home Oxygen: What to Expect <span>→</span></a></aside></div><?php App::render('Home Oxygen',(string)ob_get_clean());});

foreach(['/insurance'=>'Insurance','/playbooks'=>'Playbooks','/knowledge-base'=>'Knowledge Base','/patient-resources'=>'Patient Resources','/search'=>'Search','/workspace'=>'My Workspace'] as $path=>$label){$router->get($path,function()use($label):void{ob_start();?><section class="page-head"><div><p class="eyebrow">Atlas</p><h1><?=App::e($label)?></h1><p>This module is wired into the standalone Atlas router and ready for its visual workflow to be restored.</p></div></section><section class="empty"><strong>Standalone foundation active</strong><p>No WordPress route, page, query variable, or template hook is involved.</p></section><?php App::render($label,(string)ob_get_clean());});}

$router->dispatch();
