<?php

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

$router=new Router();

$router->get('/login',function():void{
    if(Auth::check()){header('Location: '.App::url('/'));exit;}
    $error=isset($_GET['error']);ob_start();?><section class="auth-card"><div class="auth-brand"><span class="mark">A</span><strong>ATLAS</strong></div><p class="eyebrow">Healthcare operations workspace</p><h1>Sign in</h1><p>Operational guidance, payer rules, Playbooks, local standards, and patient education in one place.</p><?php if($error):?><div class="alert">Email or password was not recognized.</div><?php endif;?><form class="auth-form" method="post" action="<?=App::e(App::url('/login'))?>"><?=Csrf::input()?><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="button" type="submit">Sign in</button></form></section><?php App::render('Sign in',(string)ob_get_clean(),false);
},false);
$router->post('/login',function():void{Csrf::verify($_POST['csrf']??null);if(Auth::attempt((string)($_POST['email']??''),(string)($_POST['password']??''))){header('Location: '.App::url('/'));exit;}header('Location: '.App::url('/login?error=1'));exit;},false);
$router->post('/logout',function():void{Csrf::verify($_POST['csrf']??null);Auth::logout();header('Location: '.App::url('/login'));exit;});

$router->get('/',function():void{
    $user=Auth::user();ob_start();?><section class="hero home-hero"><div><p class="eyebrow">Good afternoon</p><h1>What are we moving forward today, <?=App::e((string)($user['display_name']??'Atlas User'))?>?</h1><p>Atlas connects the rule, the workflow, the local standard, and the patient education around the work you are actually trying to finish.</p></div><div class="context-card"><span>Working organization</span><strong>Atlas Demo Health</strong><small>Visual context · server-authorized membership comes in the functional pass.</small></div></section><div class="home-actions"><a class="primary-action" href="<?=App::e(App::url('/search'))?>"><span>⌕</span><div><strong>Find guidance</strong><small>Search everything Atlas knows</small></div></a><a href="<?=App::e(App::url('/playbooks'))?>"><span>▶</span><div><strong>Start a Playbook</strong><small>Work a complete operational handoff</small></div></a><a href="<?=App::e(App::url('/patient-resources/packet-builder'))?>"><span>▤</span><div><strong>Build patient packet</strong><small>PHI-free patient education</small></div></a></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><p class="eyebrow">Continue working</p><h2>Arrange Home Oxygen</h2></div><span class="status-chip">Step 3 of 7</span></div><div class="progress"><span style="width:43%"></span></div><p>Next: locate qualifying evidence and make the result easy for the supplier to find.</p><a class="button inline" href="<?=App::e(App::url('/playbooks/arrange-home-oxygen'))?>">Continue Playbook</a></section><section class="panel"><p class="eyebrow">Needs attention</p><h2>Guidance review</h2><div class="attention-list"><a href="<?=App::e(App::url('/insurance'))?>"><strong>2 payer rules</strong><span>Review dates approaching</span></a><a href="<?=App::e(App::url('/knowledge-base'))?>"><strong>1 local standard</strong><span>Owner review due soon</span></a></div></section></div><section class="section-block"><div class="section-heading"><div><p class="eyebrow">Recently used</p><h2>Back to the work</h2></div><a href="<?=App::e(App::url('/workspace'))?>">Open My Workspace →</a></div><div class="mini-grid"><a href="<?=App::e(App::url('/resources/home-oxygen'))?>"><span>Resource</span><strong>Home Oxygen Qualification</strong><small>Reviewed Jul 2026</small></a><a href="<?=App::e(App::url('/insurance/medicare-oxygen'))?>"><span>Insurance</span><strong>Medicare DME: Oxygen</strong><small>Effective Jan 2026</small></a><a href="<?=App::e(App::url('/knowledge-base/discharge-documentation'))?>"><span>Knowledge Base</span><strong>Discharge Documentation Standard</strong><small>Clinical Operations</small></a><a href="<?=App::e(App::url('/patient-resources/home-oxygen'))?>"><span>Patient Resource</span><strong>Home Oxygen: What to Expect</strong><small>2 pages</small></a></div></section><?php App::render('Home',(string)ob_get_clean());
});

$router->get('/resources',function():void{
    $items=[['Home Oxygen Qualification & Documentation','DME','Practical guide to qualifying testing, documentation, and discharge coordination.','CMS Medicare Learning Network','/resources/home-oxygen'],['Skilled Nursing Facility Placement Checklist','Post-acute','What to gather, confirm, and communicate before sending a post-acute referral.','Atlas Demo Health','#'],['Home Health Eligibility Guide','Home Health','Fast reference for homebound status, skilled need, and common referral pitfalls.','CMS','#'],['Non-Emergency Transportation Options','Transportation','Decision support based on mobility, payer, medical need, and destination.','Atlas Demo Health','#']];ob_start();?><section class="page-head"><div><p class="eyebrow">Resource Library</p><h1>Find the answer, then keep moving.</h1><p>Practical references with visible source and review context.</p></div><div class="count-card"><strong><?=count($items)?></strong><span>starter resources</span></div></section><div class="filterbar"><input placeholder="Search resources…"><select><option>All categories</option><option>DME</option><option>Post-acute</option><option>Home Health</option></select><button class="button" type="button">Filter</button></div><div class="card-grid"><?php foreach($items as $item):?><article class="resource-card"><div><span class="pill"><?=App::e($item[1])?></span><span class="trust">● Reviewed</span></div><h2><?php if($item[4]!=='#'):?><a href="<?=App::e(App::url($item[4]))?>"><?=App::e($item[0])?></a><?php else:?><?=App::e($item[0])?><?php endif;?></h2><p><?=App::e($item[2])?></p><footer><span><?=App::e($item[3])?></span><span>Open →</span></footer></article><?php endforeach;?></div><?php App::render('Resources',(string)ob_get_clean());
});
$router->get('/resources/home-oxygen',function():void{ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/resources'))?>">Resources</a><span>/</span><span>Home Oxygen</span></nav><section class="detail-head"><div><span class="pill">DME</span><h1>Home Oxygen Qualification & Documentation</h1><p>A practical guide to qualifying testing, documentation, and discharge coordination for home oxygen.</p></div><aside class="source-card"><span>Source</span><strong>CMS Medicare Learning Network</strong><small>Reviewed Jul 18, 2026</small></aside></section><div class="detail-grid"><div><section class="panel"><p class="eyebrow">At a glance</p><h2>Key points</h2><ul class="check-list"><li>Confirm qualifying clinical criteria before the patient leaves the care setting.</li><li>Match the order and supporting documentation to the payer requirement.</li><li>Make the qualifying result easy for the supplier to locate.</li></ul></section><section class="panel"><p class="eyebrow">Operational sequence</p><h2>From qualification to delivery</h2><ol class="steps"><li><span>1</span>Verify qualifying test or assessment.</li><li><span>2</span>Confirm prescriber documentation.</li><li><span>3</span>Identify an appropriate supplier.</li><li><span>4</span>Send the complete referral packet.</li><li><span>5</span>Confirm acceptance and delivery plan.</li></ol></section></div><aside class="panel"><p class="eyebrow">Connected in Atlas</p><h2>Related guidance</h2><a class="related" href="<?=App::e(App::url('/playbooks/arrange-home-oxygen'))?>">Arrange Home Oxygen <b>→</b></a><a class="related" href="<?=App::e(App::url('/insurance/medicare-oxygen'))?>">Medicare DME: Oxygen <b>→</b></a><a class="related" href="<?=App::e(App::url('/patient-resources/home-oxygen'))?>">Home Oxygen: What to Expect <b>→</b></a></aside></div><?php App::render('Home Oxygen',(string)ob_get_clean());});

$router->get('/insurance',fn()=>AtlasViews::library('Insurance','Payer requirements without the scavenger hunt.','Coverage rules translated into the operational facts staff need to act correctly.',Fixtures::insurance(),'/insurance','source','payer references'));
foreach(Fixtures::insurance() as $slug=>$item){$router->get('/insurance/'.$slug,fn()=>AtlasViews::insuranceDetail($item));}

$router->get('/playbooks',fn()=>AtlasViews::library('Playbooks','Guidance that moves with the work.','Step-by-step operational guidance that connects requirements, documentation, handoffs, and patient education.',Fixtures::playbooks(),'/playbooks','time','guided workflows'));
foreach(Fixtures::playbooks() as $slug=>$item){$router->get('/playbooks/'.$slug,fn()=>AtlasViews::playbookDetail($item));}

$router->get('/knowledge-base',fn()=>AtlasViews::library('Knowledge Base','Local standards belong in one obvious place.','Organization-owned policies, SOPs, and standards—distinct from general Resources and payer guidance.',Fixtures::knowledgeBase(),'/knowledge-base','owner','local standards'));
foreach(Fixtures::knowledgeBase() as $slug=>$item){$router->get('/knowledge-base/'.$slug,fn()=>AtlasViews::knowledgeDetail($item));}

$router->get('/patient-resources',function():void{ob_start();$items=Fixtures::patientResources();?><section class="page-head"><div><p class="eyebrow">Patient Resources</p><h1>Education patients can actually use.</h1><p>Plain-language handouts that staff can preview, print, and assemble without creating a patient record in Atlas.</p></div><div class="count-card"><strong><?=count($items)?></strong><span>patient handouts</span></div></section><div class="patient-tools"><a class="button" href="<?=App::e(App::url('/patient-resources/packet-builder'))?>">Open Packet Builder</a><span>No patient identifiers are collected in this visual workflow.</span></div><div class="card-grid"><?php foreach($items as $slug=>$item):?><a class="module-card" href="<?=App::e(App::url('/patient-resources/'.$slug))?>"><div class="module-card-top"><span class="pill"><?=App::e($item['topic'])?></span><span class="trust">● <?=App::e($item['reading'])?></span></div><h2><?=App::e($item['title'])?></h2><p><?=App::e($item['summary'])?></p><footer><span><?=App::e((string)$item['pages'])?> pages · <?=App::e($item['languages'])?></span><strong>Preview →</strong></footer></a><?php endforeach;?></div><?php App::render('Patient Resources',(string)ob_get_clean());});
foreach(Fixtures::patientResources() as $slug=>$item){$router->get('/patient-resources/'.$slug,fn()=>AtlasViews::patientDetail($item));}
$router->get('/patient-resources/packet-builder',fn()=>AtlasViews::packetBuilder());

$router->get('/search',fn()=>AtlasViews::search());
$router->get('/workspace',fn()=>AtlasViews::workspace());
$router->get('/profile',fn()=>AtlasViews::profile());

$router->dispatch();
