<?php
declare(strict_types=1);

namespace Atlas\Platform\Core\Routes;

final class RouteInventory
{
    /** @return list<array<string, mixed>> */
    public function all(): array
    {
        return [
            ['name'=>'workflow_draft_create','method'=>'POST','path'=>'/atlas/v1/workflows/drafts','module'=>'workflows','capability'=>'atlas_manage_workflows','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'workflows_admin','method'=>'GET','path'=>'admin.php?page=atlas-workflows','module'=>'workflows','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'workflow_admin_detail','method'=>'GET','path'=>'admin.php?page=atlas-workflow&id={id}','module'=>'workflows','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'workflow_admin_create','method'=>'POST','path'=>'admin-post.php?action=atlas_create_workflow','module'=>'workflows','capability'=>'atlas_manage_workflows','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'resource_draft_create','method'=>'POST','path'=>'/atlas/v1/resources/drafts','module'=>'resources','capability'=>'atlas_create_resources','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'resources_admin','method'=>'GET','path'=>'admin.php?page=atlas-resources','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'resource_create_admin','method'=>'GET','path'=>'admin.php?page=atlas-resource-create','module'=>'resources','capability'=>'atlas_create_resources','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'resource_create_admin_post','method'=>'POST','path'=>'admin-post.php?action=atlas_create_resource','module'=>'resources','capability'=>'atlas_create_resources','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'resource_review_admin','method'=>'GET','path'=>'admin.php?page=atlas-resource-review','module'=>'resources','capability'=>'atlas_review_resources or atlas_publish_resources','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'resource_review_admin_post','method'=>'POST','path'=>'admin-post.php?action=atlas_editorial_transition','module'=>'resources','capability'=>'atlas_review_resources or atlas_publish_resources','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'organization_create','method'=>'POST','path'=>'/atlas/v1/organizations','module'=>'organizations','capability'=>'atlas_manage_organizations','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'organizations_admin','method'=>'GET','path'=>'admin.php?page=atlas-organizations','module'=>'organizations','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'organization_select','method'=>'POST','path'=>'admin-post.php?action=atlas_select_organization','module'=>'organizations','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'organization_admin_create','method'=>'POST','path'=>'admin-post.php?action=atlas_create_organization','module'=>'organizations','capability'=>'atlas_manage_organizations','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name' => 'atlas_home', 'method' => 'GET', 'path' => 'admin.php?page=atlas', 'module' => 'preview', 'capability' => 'atlas_access', 'registered' => true, 'implemented' => true, 'navigation' => true, 'mutates' => false],
            ['name' => 'health', 'method' => 'GET', 'path' => '/wp-json/atlas/v1/health', 'module' => 'health', 'capability' => 'public', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => false],
            ['name' => 'current_organization', 'method' => 'GET', 'path' => '/wp-json/atlas/v1/organizations/current', 'module' => 'organizations', 'capability' => 'atlas_access', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => false],
            ['name' => 'resource_detail', 'method' => 'GET', 'path' => '/wp-json/atlas/v1/resources/{id}', 'module' => 'resources', 'capability' => 'atlas_access', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => false],
            ['name' => 'resource_search', 'method' => 'GET', 'path' => '/wp-json/atlas/v1/resources', 'module' => 'resources', 'capability' => 'atlas_access', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => false],
            ['name' => 'resource_view', 'method' => 'GET', 'path' => 'admin.php?page=atlas-resource&id={id}', 'module' => 'resources', 'capability' => 'atlas_access', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => false],
            ['name'=>'resource_transition','method'=>'POST','path'=>'/wp-json/atlas/v1/resource-versions/{id}/transitions','module'=>'resources','capability'=>'atlas_review_resources or atlas_publish_resources','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'patient_resource_variant','method'=>'POST','path'=>'/wp-json/atlas/v1/patient-resources/{id}/variants','module'=>'patient_resources','capability'=>'atlas_manage_branding','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'patient_resource_composer','method'=>'GET','path'=>'admin.php?page=atlas-patient-resources','module'=>'patient_resources','capability'=>'atlas_manage_branding','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'patient_resource_compose_post','method'=>'POST','path'=>'admin-post.php?action=atlas_create_patient_resource','module'=>'patient_resources','capability'=>'atlas_manage_branding','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'packet_builder','method'=>'GET','path'=>'admin.php?page=atlas-packets','module'=>'resources','capability'=>'atlas_create_packets','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'source_workspace','method'=>'GET','path'=>'admin.php?page=atlas-sources','module'=>'resources','capability'=>'atlas_upload_sources','registered'=>true,'implemented'=>true,'navigation'=>true,'mutates'=>false],
            ['name'=>'source_intake_workspace','method'=>'GET','path'=>'/wp-json/atlas/v1/sources/documents/{id}/intake','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'source_candidate_from_page','method'=>'POST','path'=>'/wp-json/atlas/v1/sources/documents/{id}/candidates','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'source_comparison','method'=>'GET','path'=>'/wp-json/atlas/v1/sources/documents/{id}/comparison','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'source_impact_review_queue','method'=>'GET','path'=>'/wp-json/atlas/v1/source-impact-reviews','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'extraction_candidate_workspace','method'=>'GET','path'=>'/wp-json/atlas/v1/extraction-candidates/{id}/workspace','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'requirement_from_candidate','method'=>'POST','path'=>'/wp-json/atlas/v1/extraction-candidates/{id}/requirements','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'requirement_change_proposal_queue','method'=>'GET','path'=>'/wp-json/atlas/v1/requirement-change-proposals','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'requirement_change_proposal_list','method'=>'GET','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/change-proposals','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'requirement_change_proposal_create','method'=>'POST','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/change-proposals','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'requirement_change_proposal_workspace','method'=>'GET','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/change-proposals/{proposal_id}/workspace','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'requirement_change_proposal_apply','method'=>'POST','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/change-proposals/{proposal_id}/apply','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'requirement_change_proposal_reject','method'=>'POST','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/change-proposals/{proposal_id}/reject','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'requirement_workspace','method'=>'GET','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/workspace','module'=>'resources','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'source_impact_review_open','method'=>'POST','path'=>'/wp-json/atlas/v1/sources/documents/{id}/impact-review','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'source_impact_review_clear','method'=>'DELETE','path'=>'/wp-json/atlas/v1/payer-requirements/{id}/source-review','module'=>'resources','capability'=>'atlas_review_extractions','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>true],
            ['name'=>'workflow_detail','method'=>'GET','path'=>'/wp-json/atlas/v1/workflows/{id}','module'=>'workflows','capability'=>'atlas_access','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name'=>'release_readiness','method'=>'GET','path'=>'/wp-json/atlas/v1/diagnostics/readiness','module'=>'diagnostics','capability'=>'atlas_view_diagnostics','registered'=>true,'implemented'=>true,'navigation'=>false,'mutates'=>false],
            ['name' => 'diagnostics', 'method' => 'GET', 'path' => 'tools.php?page=atlas-diagnostics', 'module' => 'diagnostics', 'capability' => 'atlas_view_diagnostics', 'registered' => true, 'implemented' => true, 'navigation' => true, 'mutates' => false],
            ['name' => 'run_migrations', 'method' => 'POST', 'path' => 'admin-post.php?action=atlas_run_migrations', 'module' => 'diagnostics', 'capability' => 'atlas_run_migrations', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => true],
            ['name' => 'clear_stale_lock', 'method' => 'POST', 'path' => 'admin-post.php?action=atlas_clear_stale_migration_lock', 'module' => 'diagnostics', 'capability' => 'atlas_run_migrations', 'registered' => true, 'implemented' => true, 'navigation' => false, 'mutates' => true],
        ];
    }
}
