<?php
declare(strict_types=1);
use Atlas\Platform\Core\Migrations\Migration;use Atlas\Platform\Core\Migrations\MigrationContext;use Atlas\Platform\Core\Migrations\SchemaInspector;
return new class implements Migration{
public function id():string{return '0004';}public function description():string{return 'Create and verify idempotent editorial operations and audit events.';}
public function up(MigrationContext $context):void{$db=$context->database;$s=new SchemaInspector($db);$charset=$db->get_charset_collate();$ops=$db->prefix.'atlas_operations';$audit=$db->prefix.'atlas_audit_events';
if(!$s->tableExists($ops)){$s->execute("CREATE TABLE `{$ops}` (id char(36) NOT NULL, operation_key varchar(191) NOT NULL, resource_version_id char(36) NOT NULL, operation_name varchar(60) NOT NULL, result_json longtext NOT NULL, completed_at datetime NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB {$charset}",'Create operations table');}$s->assertTable($ops);foreach([['id','char(36)',false,null],['operation_key','varchar(191)',false,null],['resource_version_id','char(36)',false,null],['operation_name','varchar(60)',false,null],['result_json','longtext',false,null],['completed_at','datetime',false,null]]as[$c,$t,$n,$d]){$s->assertColumn($ops,$c,$t,$n,$d);}$s->assertIndex($ops,'PRIMARY',['id'],true);$this->index($s,$ops,'atlas_operation_key_unique',['operation_key'],true,"ALTER TABLE `{$ops}` ADD UNIQUE INDEX atlas_operation_key_unique (operation_key)");
if(!$s->tableExists($audit)){$s->execute("CREATE TABLE `{$audit}` (id char(36) NOT NULL, event_name varchar(100) NOT NULL, module varchar(60) NOT NULL, actor_user_id bigint(20) unsigned NOT NULL, organization_id char(36) NULL, object_type varchar(60) NOT NULL, object_id char(36) NOT NULL, context_json longtext NOT NULL, occurred_at datetime NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB {$charset}",'Create audit events table');}$s->assertTable($audit);foreach([['id','char(36)',false,null],['event_name','varchar(100)',false,null],['module','varchar(60)',false,null],['actor_user_id','bigint unsigned',false,null],['organization_id','char(36)',true,null],['object_type','varchar(60)',false,null],['object_id','char(36)',false,null],['context_json','longtext',false,null],['occurred_at','datetime',false,null]]as[$c,$t,$n,$d]){$s->assertColumn($audit,$c,$t,$n,$d);}$s->assertIndex($audit,'PRIMARY',['id'],true);$this->index($s,$audit,'atlas_audit_object',['object_type','object_id','occurred_at'],false,"ALTER TABLE `{$audit}` ADD INDEX atlas_audit_object (object_type, object_id, occurred_at)");$this->index($s,$audit,'atlas_audit_org_time',['organization_id','occurred_at'],false,"ALTER TABLE `{$audit}` ADD INDEX atlas_audit_org_time (organization_id, occurred_at)");}
private function index(SchemaInspector $s,string $table,string $name,array $columns,bool $unique,string $sql):void{if(!$s->indexMatches($table,$name,$columns,$unique)){$s->execute($sql,"Add {$name}");$s->assertIndex($table,$name,$columns,$unique);}}
};
