<?php
declare(strict_types=1);define('ATLAS_PLATFORM_DIR',dirname(__DIR__).'/plugin/atlas-platform/');require ATLAS_PLATFORM_DIR.'src/Autoloader.php';Atlas\Platform\Autoloader::register();
use Atlas\Platform\Resources\Editorial\EditorialRepository;use Atlas\Platform\Resources\Editorial\EditorialResult;use Atlas\Platform\Resources\Editorial\EditorialService;use Atlas\Platform\Resources\Editorial\EditorialTransitionPolicy;
final class MemoryEditorial implements EditorialRepository{public array $states=[];public array $operations=[];public int $effects=0;public function __construct(private EditorialTransitionPolicy $policy){}public function transition(string $versionId,string $to,int $actorUserId,?string $organizationId,bool $allowPlatform,string $key):?EditorialResult{if(isset($this->operations[$key])){$r=$this->operations[$key];if($r->versionId!==$versionId||$r->to!==$to){throw new RuntimeException('idempotency conflict');}return new EditorialResult($r->resourceId,$r->versionId,$r->from,$r->to,true);}if($organizationId!=='org-a'&&!$allowPlatform){return null;}$from=$this->states[$versionId]??'draft';if(!$this->policy->allows($from,$to)){throw new RuntimeException('not allowed');}$r=new EditorialResult('resource-a',$versionId,$from,$to,false);$this->states[$versionId]=$to;$this->operations[$key]=$r;$this->effects++;return $r;}}
function edit_expect(bool $c,string $m):void{if(!$c){throw new RuntimeException($m);}echo "PASS: {$m}\n";}
$policy=new EditorialTransitionPolicy();edit_expect($policy->allows('draft','in_review')&&!$policy->allows('draft','published'),'editorial policy allows only explicit transitions');edit_expect($policy->allows('approved','published')&&!$policy->allows('archived','draft'),'publication and terminal states follow policy');
$repo=new MemoryEditorial($policy);$service=new EditorialService($repo);$id='550e8400-e29b-41d4-a716-446655440000';$first=$service->transition($id,'in_review',10,'org-a',false,'request-0001');$retry=$service->transition($id,'in_review',10,'org-a',false,'request-0001');edit_expect($first?->replayed===false&&$retry?->replayed===true&&$repo->effects===1,'repeated idempotency keys return the successful result without duplicate effects');edit_expect($service->transition($id,'approved',10,'org-b',false,'request-0002')===null,'organization A editorial access does not authorize organization B');
try{$service->transition($id,'published',10,'org-a',false,'request-0003');throw new RuntimeException('invalid transition accepted');}catch(RuntimeException){edit_expect(true,'invalid status transitions are rejected');}
try{$service->transition($id,'approved',10,'org-a',false,'bad');throw new RuntimeException('bad key accepted');}catch(InvalidArgumentException){edit_expect(true,'editorial mutations require a bounded idempotency key');}
try{$service->transition($id,'approved',10,'org-a',false,'request-0001');throw new RuntimeException('conflicting retry accepted');}catch(RuntimeException){edit_expect($repo->effects===1,'an idempotency key cannot be reused for a conflicting operation');}
echo "All editorial lifecycle tests passed.\n";
