<?php
declare(strict_types=1);
define('ATLAS_PLATFORM_DIR', dirname(__DIR__) . '/plugins/atlas-platform/');
require ATLAS_PLATFORM_DIR . 'src/Autoloader.php';
Atlas\Platform\Autoloader::register();
if (! function_exists('sanitize_key')) { function sanitize_key(string $key): string { return strtolower(preg_replace('/[^a-z0-9_\-]/', '', $key) ?? ''); } }
if (! function_exists('sanitize_title')) { function sanitize_title(string $key): string { return trim(preg_replace('/-+/', '-', preg_replace('/[^a-z0-9]+/', '-', strtolower($key)) ?? '') ?? '', '-'); } }

use Atlas\Platform\Core\Audit\AuditRecorder;
use Atlas\Platform\PatientResources\Catalog\PatientEducationCatalogRepository;
use Atlas\Platform\PatientResources\Catalog\PatientEducationItem;
use Atlas\Platform\Resources\Packets\PacketItemResolver;
use Atlas\Platform\Resources\Packets\PacketRepository;
use Atlas\Platform\Resources\Packets\PacketService;
use Atlas\Platform\Resources\Packets\PacketSnapshotRepository;
use Atlas\Platform\Resources\Sources\SourceWorkspaceRepository;
use Atlas\Platform\Resources\Sources\SourceWorkspaceService;

final class MemoryPackets implements PacketRepository {
    public array $packets = [];
    private string $id = '550e8400-e29b-41d4-a716-446655440000';
    public function create(string $o, int $u, string $n, array $i, string $d = ''): string { $this->packets[$this->id] = ['id'=>$this->id,'organization_id'=>$o,'org'=>$o,'user'=>$u,'name'=>$n,'description'=>$d,'status'=>'draft','items'=>$i]; return $this->id; }
    public function addItem(string $p, int $u, array $i): bool { $this->packets[$p]['items'][] = $i + ['item_type'=>$i['type'] ?? 'resource','item_id'=>$i['id'] ?? $this->id,'display_order'=>count($this->packets[$p]['items']),'id'=>$this->id]; return true; }
    public function removeItem(string $p, string $i, int $u): bool { array_pop($this->packets[$p]['items']); return true; }
    public function setStatus(string $p, int $u, string $s): bool { $this->packets[$p]['status'] = $s; return true; }
    public function findForUser(string $p, int $u, ?string $o): ?array { return isset($this->packets[$p]) ? ['packet'=>$this->packets[$p], 'items'=>$this->packets[$p]['items']] : null; }
    public function listForUser(int $u, ?string $o, int $l = 25): array { return array_values(array_filter($this->packets, fn($p) => $p['user'] === $u || $p['org'] === $o)); }
}

final class MemorySources implements SourceWorkspaceRepository {
    public array $docs = [], $sections = [], $pages = [], $candidates = [], $requirements = [], $states = [], $profiles = [], $dme = [], $revisions = [], $proposals = [];
    private string $id = '550e8400-e29b-41d4-a716-446655440000';
    private int $requirementSeq = 0;
    private int $proposalSeq = 0;
    public function createDocument(?string $o, int $u, array $i): string { $this->docs[$this->id] = $i + ['id'=>$this->id,'organization_id'=>$o,'org'=>$o,'user'=>$u,'extraction_status'=>'queued']; return $this->id; }
    public function findDocument(string $id, ?string $o): ?array { $d = $this->docs[$id] ?? null; return is_array($d) && (($d['organization_id'] ?? $d['org'] ?? null) === null || ($d['organization_id'] ?? $d['org'] ?? null) === $o) ? $d : null; }
    public function updateDocumentStatus(string $id, ?string $o, string $s, string $n = ''): bool { $this->docs[$id]['extraction_status'] = $s; return true; }
    public function saveDocumentPage(string $d, int $p, int $u, array $i): string { $key=$d.':'.$p; $this->pages[$key]=$i+['id'=>$this->id,'source_document_id'=>$d,'page_number'=>$p,'text_checksum'=>hash('sha256',(string)($i['text_content']??'')),'created_by'=>$u,'extracted_at'=>'now']; return $this->id; }
    public function documentPages(string $d, int $l = 25): array { return array_values(array_filter($this->pages, fn($p) => $p['source_document_id'] === $d)); }
    public function createSection(string $d, array $i): string { $this->sections[$this->id] = $i + ['id'=>$this->id,'doc'=>$d]; return $this->id; }
    public function createCandidate(string $s, ?string $o, array $i): string { $this->candidates[$this->id] = $i + ['id'=>$this->id,'section'=>$s,'org'=>$o,'status'=>'pending']; return $this->id; }
    public function findCandidate(string $id, ?string $o): ?array { $c = $this->candidates[$id] ?? null; if (! is_array($c) || (($c['org'] ?? null) !== null && ($c['org'] ?? null) !== $o)) { return null; } $s = $this->sections[$c['section'] ?? ''] ?? []; $d = $this->docs[$s['doc'] ?? ''] ?? []; return $c + ['source_document_id'=>$s['doc'] ?? '', 'page_number'=>$s['page_number'] ?? null, 'section_label'=>$s['section_label'] ?? '', 'text_excerpt'=>$s['text_excerpt'] ?? '', 'anchor'=>$s['anchor'] ?? '', 'document_title'=>$d['title'] ?? '', 'publisher'=>$d['publisher'] ?? '', 'document_effective_date'=>$d['effective_date'] ?? null]; }
    public function reviewCandidate(string $id, string $status, int $user): bool { if (! isset($this->candidates[$id]) || ! in_array($status, ['approved','rejected','needs_changes'], true)) { return false; } $this->candidates[$id]['status'] = $status; return true; }
    public function createRequirement(?string $o, int $u, array $i): string { $id = sprintf('550e8400-e29b-41d4-a716-100000000%03d', $this->requirementSeq++); $this->requirements[$id] = $i + ['id'=>$id,'org'=>$o,'user'=>$u,'review_status'=>'draft']; return $id; }
    public function reviewRequirement(string $id, ?string $o, string $s, int $u): bool { $this->requirements[$id]['review_status'] = $s; return true; }
    public function markRequirementsForSourceReview(string $old, string $new, ?string $o, int $u, string $reason): int { $count=0; foreach ($this->requirements as &$r) { $c=$this->candidates[$r['source_candidate_id'] ?? ''] ?? null; $s=is_array($c) ? ($this->sections[$c['section']] ?? null) : null; if (is_array($s) && ($s['doc'] ?? '') === $old && (($r['org'] ?? null) === null || ($r['org'] ?? null) === $o)) { $r['source_review_status']='needs_source_review'; $r['source_review_document_id']=$new; $r['source_review_reason']=$reason; $r['source_reviewed_at']=''; $count++; } } unset($r); return $count; }
    public function clearRequirementSourceReview(string $id, ?string $o, int $u, string $note): bool { if (! isset($this->requirements[$id])) { return false; } $this->requirements[$id]['source_review_status']='current'; $this->requirements[$id]['source_review_reason']=$note; $this->requirements[$id]['source_reviewed_at']='now'; return true; }
    public function createRequirementChangeProposal(string $id, ?string $o, int $u, array $i): string { $proposalId = sprintf('550e8400-e29b-41d4-a716-%012d', $this->proposalSeq++); $proposal = ['id'=>$proposalId,'requirement_id'=>$id,'organization_id'=>$o,'source_document_id'=>$i['source_document_id'] ?? '','proposal_status'=>$i['proposal_status'] ?? 'draft','proposal_reason'=>$i['proposal_reason'] ?? '','proposed_changes'=>$i['proposed_changes'] ?? [],'created_by'=>$u,'created_at'=>'now','updated_at'=>'now']; $this->proposals[$id][] = $proposal; return $proposalId; }
    public function findRequirementChangeProposal(string $id, ?string $o): ?array { foreach ($this->proposals as $items) { foreach ($items as $proposal) { if (($proposal['id'] ?? '') === $id && (($proposal['organization_id'] ?? null) === null || ($proposal['organization_id'] ?? null) === $o)) { return $proposal; } } } return null; }
    public function applyRequirementChangeProposal(string $id, string $r, ?string $o, int $u, array $changes): bool { if (! isset($this->requirements[$r])) { return false; } foreach ($changes as $field => $value) { $this->requirements[$r][$field] = $value; } foreach ($this->proposals[$r] as &$proposal) { if (($proposal['id'] ?? '') === $id) { $proposal['proposal_status'] = 'applied'; $proposal['applied_by'] = $u; $proposal['applied_at'] = 'now'; } } unset($proposal); return true; }
    public function rejectRequirementChangeProposal(string $id, string $r, ?string $o, int $u, string $note): bool { foreach ($this->proposals[$r] as &$proposal) { if (($proposal['id'] ?? '') === $id) { $proposal['proposal_status'] = 'rejected'; $proposal['rejection_note'] = $note; $proposal['rejected_by'] = $u; $proposal['rejected_at'] = 'now'; return true; } } unset($proposal); return false; }
    public function requirementChangeProposals(string $id, ?string $o, int $l = 25): array { return array_slice(array_reverse($this->proposals[$id] ?? []), 0, $l); }
    public function changeProposalQueue(?string $o, int $l = 50, array $c = []): array { $out=[]; foreach ($this->proposals as $items) { foreach ($items as $proposal) { if ((($c['proposal_status'] ?? '') === '' || ($proposal['proposal_status'] ?? '') === $c['proposal_status']) && (($proposal['organization_id'] ?? null) === null || ($proposal['organization_id'] ?? null) === $o)) { $req=$this->requirements[$proposal['requirement_id']] ?? []; $out[]=$proposal+['payer'=>$req['payer'] ?? '', 'topic'=>$req['topic'] ?? '', 'review_status'=>$req['review_status'] ?? '', 'source_review_status'=>$req['source_review_status'] ?? 'current']; } } } return array_slice(array_reverse($out), 0, $l); }
    public function appendRequirementRevision(string $id, ?string $o, int $u, string $t, array $s): string { $revision = ['id'=>$this->id,'requirement_id'=>$id,'organization_id'=>$o,'revision_number'=>count($this->revisions[$id] ?? []) + 1,'revision_type'=>$t,'snapshot'=>$s,'created_by'=>$u,'created_at'=>'now']; $this->revisions[$id][] = $revision; return $this->id; }
    public function requirementRevisions(string $id, ?string $o, int $l = 25): array { return array_reverse(array_slice($this->revisions[$id] ?? [], -$l)); }
    public function createInsuranceProfile(?string $o, int $u, array $i): string { $this->profiles[$this->id] = $i + ['id'=>$this->id,'org'=>$o,'user'=>$u,'status'=>'active']; return $this->id; }
    public function insuranceProfiles(?string $o, int $l = 25, array $c = []): array { return array_values($this->profiles); }
    public function createDmeCategory(array $i): string { $this->dme[$this->id] = $i + ['id'=>$this->id,'status'=>'active']; return $this->id; }
    public function dmeCategories(int $l = 100, array $c = []): array { return array_values($this->dme); }
    public function findRequirement(string $id, ?string $o): ?array { return $this->requirements[$id] ?? null; }
    public function findRequirementSource(string $id, ?string $o): ?array { $c = $this->candidates[$id] ?? null; if (! is_array($c)) { return null; } $s = $this->sections[$c['section']] ?? []; $d = $this->docs[$s['doc'] ?? ''] ?? []; return ['candidate_id'=>$id,'statement'=>$c['statement'] ?? '','candidate_status'=>$c['status'] ?? '','section_id'=>$s['id'] ?? '','page_number'=>$s['page_number'] ?? null,'section_label'=>$s['section_label'] ?? '','text_excerpt'=>$s['text_excerpt'] ?? '','anchor'=>$s['anchor'] ?? '','document_id'=>$d['id'] ?? '','document_title'=>$d['title'] ?? '','publisher'=>$d['publisher'] ?? '','source_family_key'=>$d['source_family_key'] ?? '','source_version_label'=>$d['source_version_label'] ?? '','supersedes_document_id'=>$d['supersedes_document_id'] ?? '','source_url'=>$d['source_url'] ?? '','original_filename'=>$d['original_filename'] ?? '','mime_type'=>$d['mime_type'] ?? '','file_size_bytes'=>$d['file_size_bytes'] ?? 0,'checksum'=>$d['checksum'] ?? '','preserved_at'=>$d['preserved_at'] ?? '','effective_date'=>$d['effective_date'] ?? '','retrieved_at'=>$d['retrieved_at'] ?? '']; }
    public function requirementsForSourceDocument(string $d, ?string $o, int $l = 50): array { $out=[]; foreach ($this->requirements as $r) { $c=$this->candidates[$r['source_candidate_id'] ?? ''] ?? null; $s=is_array($c) ? ($this->sections[$c['section']] ?? null) : null; if (is_array($s) && ($s['doc'] ?? '') === $d && (($r['organization_id'] ?? $r['org'] ?? null) === null || ($r['organization_id'] ?? $r['org'] ?? null) === $o)) { $out[] = $r + ['candidate_id'=>$c['id'] ?? '', 'page_number'=>$s['page_number'] ?? null, 'section_label'=>$s['section_label'] ?? '']; } } return array_slice($out, 0, $l); }
    public function saveChecklistState(string $r, ?string $o, string $h, string $l, string $s, string $n, int $u): bool { $this->states[$r . ':' . $h] = ['requirement_id'=>$r,'checklist_hash'=>$h,'label'=>$l,'status'=>$s,'notes'=>$n,'updated_by'=>$u,'updated_at'=>'now']; return true; }
    public function checklistState(array $ids, ?string $o): array { return array_filter($this->states, fn($v) => in_array($v['requirement_id'], $ids, true)); }
    public function documents(?string $o, int $l = 25): array { return array_values($this->docs); }
    public function candidates(?string $o, int $l = 25): array { return array_values($this->candidates); }
    public function requirements(?string $o, int $l = 25, array $c = []): array { return array_values(array_filter($this->requirements, fn($r) => (($c['status'] ?? '') === '' || $r['review_status'] === $c['status']) && (($c['source_review_status'] ?? '') === '' || ($r['source_review_status'] ?? 'current') === $c['source_review_status']) && (($c['payer'] ?? '') === '' || $r['payer'] === $c['payer']) && (($c['topic'] ?? '') === '' || str_contains($r['topic'], $c['topic'])) && (($c['dme_category_slug'] ?? '') === '' || ($r['dme_category_slug'] ?? '') === $c['dme_category_slug']) && (($c['prior_authorization_status'] ?? '') === '' || ($r['prior_authorization_status'] ?? '') === $c['prior_authorization_status']) && (($c['plan_name'] ?? '') === '' || ($r['plan_name'] ?? '') === '' || ($r['plan_name'] ?? '') === $c['plan_name']) && (($c['jurisdiction'] ?? '') === '' || ($r['jurisdiction'] ?? '') === '' || ($r['jurisdiction'] ?? '') === $c['jurisdiction']))); }
    public function summary(?string $o): array { return ['atlas_source_documents.queued'=>count($this->docs),'atlas_extraction_candidates.approved'=>1,'atlas_payer_requirements.published'=>count(array_filter($this->requirements, fn($r) => ($r['review_status'] ?? '') === 'published'))]; }
}

final class MemoryAudit implements AuditRecorder { public array $events = []; public function record(string $e, string $m, int $a, ?string $o, string $t, string $id, array $c = []): void { $this->events[] = $e; } }
final class MemoryResolver implements PacketItemResolver { public function resolve(array $item, ?string $o): array { return $item + ['summary'=>'Resolved','html'=>'<p>Resolved content</p>','status'=>'resolved','provenance'=>[['label'=>'Source','value'=>'Test']]]; } }
final class MemoryCatalog implements PatientEducationCatalogRepository { public function publishedForContext(string $o, int $l = 50): array { return [new PatientEducationItem('550e8400-e29b-41d4-a716-446655440000', 'v1', 'Education', 'Summary', 'organization', 'Source')]; } }
final class MemorySnapshots implements PacketSnapshotRepository { public array $items = []; public function create(string $p, ?string $o, int $u, string $s, array $snap): string { $this->items[] = ['id'=>'550e8400-e29b-41d4-a716-446655440000','packet_id'=>$p,'snapshot'=>$snap,'packet_status'=>$s,'actor_user_id'=>$u,'created_at'=>'now']; return '550e8400-e29b-41d4-a716-446655440000'; } public function find(string $id, string $p): ?array { return $this->items[0] ?? null; } public function listForPacket(string $p, int $l = 10): array { return $this->items; } }
function sw_expect(bool $c, string $m): void { if (! $c) { throw new RuntimeException($m); } echo "PASS: {$m}\n"; }

$audit = new MemoryAudit(); $packets = new MemoryPackets(); $snapshots = new MemorySnapshots(); $uuid = '550e8400-e29b-41d4-a716-446655440000';
$packetService = new PacketService($packets, $audit, new MemoryResolver(), new MemoryCatalog(), $snapshots);
$packet = $packetService->create('org-a', 7, ['name'=>'Discharge packet','description'=>'After visit','items'=>[['type'=>'resource','id'=>$uuid,'title'=>'Education']]]);
$packetService->addItem($packet, 7, ['type'=>'instruction','id'=>$uuid,'title'=>'Instruction','notes'=>'Bring your device.']);
$packetService->setStatus($packet, 7, 'ready');
$preview = $packetService->preview($packet, 7, 'org-a');
sw_expect(count($preview['items'] ?? []) === 2 && $packetService->listForUser(7, 'org-a')[0]['status'] === 'ready', 'patient packet builder manages patient-facing resources, instructions, preview, and lifecycle through the service');
sw_expect(($preview['items'][0]['html'] ?? '') === '<p>Resolved content</p>' && ($preview['items'][0]['provenance'][0]['value'] ?? '') === 'Test', 'packet preview includes resolved printable content and provenance');
sw_expect(($packetService->patientResourceOptions('org-a')[0]['title'] ?? '') === 'Education' && $packetService->createSnapshot($packet, 7, 'org-a') === $uuid && count($snapshots->items) === 1, 'patient packet picker options and immutable print snapshots are service-backed');
try { $packetService->addItem($packet, 7, ['type'=>'resource','id'=>'00000000-0000-0000-0000-000000000000','title'=>'Internal']); throw new RuntimeException('Packet patient-facing guardrail did not trigger.'); } catch (InvalidArgumentException) { sw_expect(true, 'patient packets reject resources outside the patient-facing catalog'); }
try { $packetService->addItem($packet, 7, ['type'=>'requirement','id'=>$uuid,'title'=>'Requirement']); throw new RuntimeException('Packet requirement guardrail did not trigger.'); } catch (InvalidArgumentException) { sw_expect(true, 'patient packets reject internal payer requirements'); }
try { $packetService->addItem($packet, 7, ['type'=>'instruction','id'=>$uuid,'notes'=>'MRN 123']); throw new RuntimeException('Packet PHI warning did not trigger.'); } catch (InvalidArgumentException) { sw_expect(true, 'packet service rejects obvious patient-identifying markers'); }

$sources = new MemorySources(); $service = new SourceWorkspaceService($sources, $audit);
$service->createDocument('org-a', 7, ['title'=>'Policy','publisher'=>'Payer','preserved_file_path'=>'/private/atlas/policy.pdf','original_filename'=>'policy.pdf','mime_type'=>'application/pdf','file_size_bytes'=>2048,'preserved_at'=>'2026-01-01 00:00:00','checksum'=>str_repeat('a',64)]);
$service->updateDocumentStatus($uuid, 'org-a', 'ready', '', 7);
$service->saveDocumentPageText($uuid, ['page_number'=>2,'extraction_method'=>'manual','text_content'=>'Page two says must document use.'], 7);
$service->saveDocumentPageText($uuid, ['page_number'=>2,'extraction_method'=>'manual','text_content'=>'Page two says must document use and signed order.'], 7);
sw_expect(count($service->documentPages($uuid)) === 1 && ($service->documentPages($uuid)[0]['text_checksum'] ?? '') === hash('sha256','Page two says must document use and signed order.'), 'page-aware source extraction stores replaceable text by document and page');
try { $service->saveDocumentPageText($uuid, ['page_number'=>3,'text_content'=>'DOB 2020-01-01'], 7); throw new RuntimeException('PHI page warning did not trigger.'); } catch (InvalidArgumentException) { sw_expect(true, 'page-aware source extraction rejects obvious patient-identifying text'); }
$intake = $service->sourceIntakeWorkspace($uuid, 'org-a');
sw_expect(($intake['summary']['suggestion_count'] ?? 0) >= 1 && (($intake['candidate_suggestions'][0]['page_number'] ?? 0) === 2), 'source intake workspace suggests candidate statements from stored page text');
$pageCandidate = $service->createCandidateFromPage($uuid, 'org-a', ['page_number'=>2,'statement'=>'Requires documentation and signed order.','text_excerpt'=>'Requires documentation and signed order.'], 7);
sw_expect($pageCandidate === $uuid && (($sources->candidates[$pageCandidate]['statement'] ?? '') === 'Requires documentation and signed order.'), 'source intake can create an extraction candidate directly from page text');
try { $service->createRequirementDraftFromCandidate($pageCandidate, 'org-a', 9, ['payer'=>'Payer','topic'=>'CPAP']); throw new RuntimeException('Unapproved candidate created a requirement.'); } catch (InvalidArgumentException) { sw_expect(true, 'candidate fast path requires approved extraction before creating a requirement draft'); }
$service->reviewCandidate($pageCandidate, 'approved', 9, 'org-a');
$candidateWorkspace = $service->candidateWorkspace($pageCandidate, 'org-a');
sw_expect(($candidateWorkspace['actions']['can_create_draft'] ?? false) === true && (($candidateWorkspace['suggested_requirement']['requirement_type'] ?? '') === 'documentation'), 'candidate workspace provides source context and inferred requirement fields');
$draftFromCandidate = $service->createRequirementDraftFromCandidate($pageCandidate, 'org-a', 9, ['payer'=>'Payer','topic'=>'CPAP','prior_authorization_status'=>'required','required_forms_text'=>'SWO']);
sw_expect(($sources->requirements[$draftFromCandidate]['source_candidate_id'] ?? '') === $pageCandidate && (($sources->requirements[$draftFromCandidate]['review_status'] ?? '') === 'draft') && (($sources->requirements[$draftFromCandidate]['required_forms'][0] ?? '') === 'SWO'), 'approved candidate can create a structured payer requirement draft');
unset($sources->requirements[$draftFromCandidate], $sources->revisions[$draftFromCandidate]);
$service->createSection($uuid, ['page_number'=>2,'section_label'=>'Coverage','text_excerpt'=>'Must document use.','anchor'=>'dme-coverage'], 7);
$candidate = $service->createCandidate($uuid, 'org-a', ['statement'=>'Requires documentation.'], 7);
sw_expect($service->reviewCandidate($candidate, 'approved', 9, 'org-a'), 'extraction candidates require explicit review decisions');
$requirement = $service->createRequirement('org-a', 9, ['payer'=>'Payer','plan_name'=>'Gold','topic'=>'CPAP','dme_category_slug'=>'cpap','jurisdiction'=>'PA','prior_authorization_status'=>'required','frequency_limit'=>'1 every 5 years','replacement_interval'=>'5 years','required_forms'=>['SWO','CMN'],'coverage_criteria_text'=>'Meets policy criteria.','requirement_text'=>'Requires documentation. Submit signed order.','source_candidate_id'=>$uuid]);
$service->reviewRequirement($requirement, 'org-a', 'published', 9);
$publishedRequirement = $service->requirements('org-a', ['status'=>'published','dme_category_slug'=>'cpap','prior_authorization_status'=>'required'])[0] ?? [];
sw_expect(($publishedRequirement['source_candidate_id'] ?? '') === $uuid && ($publishedRequirement['required_forms'][0] ?? '') === 'SWO' && ($publishedRequirement['frequency_limit'] ?? '') === '1 every 5 years', 'payer requirements can be filtered after review and retain DME details and provenance');
$source = $sources->findRequirementSource($uuid, 'org-a');
sw_expect(($source['document_title'] ?? '') === 'Policy' && ($source['page_number'] ?? 0) === 2 && ($source['text_excerpt'] ?? '') === 'Must document use.', 'payer requirement provenance resolves source document, location, excerpt, and reviewed extraction');
sw_expect(($source['original_filename'] ?? '') === 'policy.pdf' && ($source['mime_type'] ?? '') === 'application/pdf' && ($source['checksum'] ?? '') === str_repeat('a',64), 'source document preservation metadata is retained without exposing patient packet content');
$checklist = $service->documentationChecklist('org-a', ['status'=>'published']); $evidence = $service->requirementEvidence($requirement, 'org-a');
sw_expect(count($checklist[0]['checklist_items'] ?? []) === 2 && ($evidence['source']['document_title'] ?? '') === 'Policy', 'payer requirements produce internal documentation checklists and evidence detail outside patient packets');
$summary = $service->coverageSummary($requirement, 'org-a');
sw_expect(($summary['internal_only'] ?? false) === true && ($summary['patient_packet_safe'] ?? true) === false && ($summary['readiness']['ready'] ?? false) === true && ($summary['prior_authorization_workup']['ready_for_submission_prep'] ?? false) === true && ($summary['source']['document_title'] ?? '') === 'Policy', 'payer requirements produce internal DME coverage summaries with readiness, prior authorization workups, evidence, and packet separation guardrails');
$detail = $service->requirementDetailWorkspace($requirement, 'org-a');
sw_expect(($detail['internal_only'] ?? false) === true && ($detail['patient_packet_safe'] ?? true) === false && ($detail['readiness_status'] ?? '') === 'ready' && ($detail['prior_authorization']['ready_for_submission_prep'] ?? false) === true && count($detail['checklist_items'] ?? []) === 2 && ($detail['source']['document_title'] ?? '') === 'Policy', 'coverage requirement detail workspace composes readiness, prior auth tasks, checklist state, and source evidence');
sw_expect(count($detail['revisions'] ?? []) === 2 && ($detail['revisions'][0]['revision_type'] ?? '') === 'status_published' && ($detail['revisions'][1]['revision_type'] ?? '') === 'created', 'payer requirement revisions are appended as immutable detail history');
$newSource = '550e8400-e29b-41d4-a716-446655440001';
$sources->docs[$newSource] = array_replace($sources->docs[$uuid], ['id'=>$newSource,'title'=>'Policy update','source_family_key'=>'payer-policy','source_version_label'=>'2026 update','supersedes_document_id'=>$uuid,'checksum'=>str_repeat('b',64),'effective_date'=>'2026-06-01']);
$sources->docs[$uuid]['source_family_key'] = 'payer-policy';
$sources->docs[$uuid]['source_version_label'] = '2025 policy';
$sources->pages[$newSource . ':2'] = ['id'=>$newSource,'source_document_id'=>$newSource,'page_number'=>2,'text_content'=>'Page two now requires signed order and recent usage report.','text_checksum'=>hash('sha256','Page two now requires signed order and recent usage report.'),'extracted_at'=>'now'];
$comparison = $service->sourceVersionComparison($newSource, 'org-a');
sw_expect(($comparison['status'] ?? '') === 'comparison_ready' && ($comparison['checksum_changed'] ?? false) === true && ($comparison['changed_page_count'] ?? 0) === 1 && ($comparison['impacted_requirement_count'] ?? 0) === 1, 'source version comparison detects changed preserved sources, changed page text, and impacted requirements for review');
sw_expect(($comparison['patient_packet_safe'] ?? true) === false && ($comparison['impacted_requirements'][0]['id'] ?? '') === $requirement, 'source version comparison remains internal-only and points staff back to affected requirement review');
$opened = $service->openSourceImpactReview($newSource, 'org-a', 9);
$needsReview = $service->requirements('org-a', ['source_review_status'=>'needs_source_review']);
sw_expect(($opened['opened_requirement_count'] ?? 0) === 1 && count($needsReview) === 1 && ($needsReview[0]['source_review_document_id'] ?? '') === $newSource, 'source impact review queue marks requirements affected by a changed superseding source');
$queue = $service->sourceImpactReviewQueue('org-a');
sw_expect(($queue['summary']['needs_source_review_count'] ?? 0) === 1 && ($queue['items'][0]['id'] ?? '') === $requirement, 'source impact review queue returns dedicated internal review rows');
$proposal = $service->createRequirementChangeProposal($requirement, 'org-a', 9, ['proposal_reason'=>'Draft update from source review; do not publish yet.','requirement_text'=>'Requires documentation, signed order, and recent usage report.','required_forms_text'=>'SWO, Usage report']);
$proposalDetail = $service->requirementDetailWorkspace($requirement, 'org-a');
sw_expect($proposal === '550e8400-e29b-41d4-a716-000000000000' && (($proposalDetail['change_proposals'][0]['proposed_changes']['requirement_text'] ?? '') === 'Requires documentation, signed order, and recent usage report.') && (($proposalDetail['change_proposals'][0]['source_document_id'] ?? '') === $newSource) && (($sources->requirements[$requirement]['requirement_text'] ?? '') === 'Requires documentation. Submit signed order.'), 'requirement change proposals draft updates from source review without mutating the published requirement');
sw_expect(($proposalDetail['change_proposals'][0]['diff'][0]['field'] ?? '') === 'requirement_text' && (($proposalDetail['change_proposals'][0]['diff'][0]['changed'] ?? false) === true), 'requirement change proposals include before-and-after field diffs for staff review');
$proposalWorkspace = $service->requirementChangeProposalWorkspace($proposal, $requirement, 'org-a');
sw_expect(($proposalWorkspace['decision_guidance']['can_apply'] ?? false) === true && ($proposalWorkspace['decision_guidance']['changed_field_count'] ?? 0) === 2 && (($proposalWorkspace['source_comparison']['status'] ?? '') === 'comparison_ready'), 'requirement change proposal workspace provides source comparison and apply guidance');
sw_expect($service->applyRequirementChangeProposal($proposal, $requirement, 'org-a', 9) && (($sources->requirements[$requirement]['requirement_text'] ?? '') === 'Requires documentation, signed order, and recent usage report.') && (($service->requirementChangeProposals($requirement, 'org-a')[0]['proposal_status'] ?? '') === 'applied') && (($service->requirementDetailWorkspace($requirement, 'org-a')['revisions'][0]['revision_type'] ?? '') === 'change_proposal_applied'), 'applied requirement change proposals mutate the requirement through the service and append immutable revision history');
$staleProposal = $service->createRequirementChangeProposal($requirement, 'org-a', 9, ['proposal_reason'=>'No-op stale proposal.','requirement_text'=>'Requires documentation, signed order, and recent usage report.']);
$staleWorkspace = $service->requirementChangeProposalWorkspace($staleProposal, $requirement, 'org-a');
sw_expect(($staleWorkspace['decision_guidance']['can_apply'] ?? true) === false && (($staleWorkspace['decision_guidance']['warnings'][0]['code'] ?? '') === 'stale_noop'), 'requirement change proposal workspace flags stale no-op proposals');
try { $service->applyRequirementChangeProposal($staleProposal, $requirement, 'org-a', 9); throw new RuntimeException('Stale no-op proposal was applied.'); } catch (InvalidArgumentException) { sw_expect(true, 'stale no-op requirement change proposals cannot be applied'); }
$service->rejectRequirementChangeProposal($staleProposal, $requirement, 'org-a', 9, 'Rejected stale no-op proposal.');
$rejectedProposal = $service->createRequirementChangeProposal($requirement, 'org-a', 9, ['proposal_reason'=>'Draft alternate update for rejection.','coverage_criteria_text'=>'Alternate criteria that staff declined.']);
sw_expect(($service->sourceImpactReviewQueue('org-a')['summary']['open_change_proposal_count'] ?? 0) === 1 && (($service->sourceImpactReviewQueue('org-a')['items'][0]['open_change_proposal_count'] ?? 0) === 1), 'source impact review queue warns when draft change proposals block closeout');
sw_expect(($service->changeProposalQueue('org-a')['summary']['proposal_count'] ?? 0) === 1 && (($service->changeProposalQueue('org-a')['items'][0]['id'] ?? '') === $rejectedProposal) && (($service->changeProposalQueue('org-a')['summary']['changed_field_counts']['coverage_criteria_text'] ?? 0) === 1), 'requirement change proposal queue lists draft proposals with changed-field summaries');
$actionDashboard = $service->dashboard('org-a');
sw_expect(($actionDashboard['change_proposal_summary']['needs_attention'] ?? -1) === 0 && (($actionDashboard['proposal_action_rows'][0]['blocks_source_closeout'] ?? false) === true) && (($actionDashboard['proposal_action_rows'][0]['next_action'] ?? '') !== ''), 'source workspace dashboard exposes proposal action rows for source review closeout');
sw_expect(($service->changeProposalQueue('org-a', ['proposal_status'=>'draft','payer'=>'Payer','topic'=>'CPAP','source_review_status'=>'needs_source_review'])['summary']['proposal_count'] ?? 0) === 1 && ($service->changeProposalQueue('org-a', ['proposal_status'=>'draft','payer'=>'Other'])['summary']['proposal_count'] ?? -1) === 0, 'requirement change proposal queue supports payer topic and source review filters');
sw_expect($service->rejectRequirementChangeProposal($rejectedProposal, $requirement, 'org-a', 9, 'Rejected after source review; applied proposal is preferred.') && (($service->requirementChangeProposals($requirement, 'org-a')[0]['proposal_status'] ?? '') === 'rejected') && (($service->requirementChangeProposals($requirement, 'org-a')[0]['rejection_note'] ?? '') !== ''), 'requirement change proposals can be rejected with a retained non-PHI review note');
sw_expect(($service->changeProposalQueue('org-a', ['proposal_status'=>'rejected'])['summary']['proposal_count'] ?? 0) >= 2 && ($service->changeProposalQueue('org-a', ['proposal_status'=>'applied'])['summary']['proposal_count'] ?? 0) === 1, 'requirement change proposal queue filters applied and rejected proposal buckets');
sw_expect(count($service->requirementDetailWorkspace($requirement, 'org-a')['proposal_timeline'] ?? []) >= 4, 'requirement detail timeline includes proposal draft, applied, rejected, and revision events');
try { $service->applyRequirementChangeProposal($rejectedProposal, $requirement, 'org-a', 9); throw new RuntimeException('Rejected proposal was applied.'); } catch (InvalidArgumentException) { sw_expect(true, 'rejected requirement change proposals cannot be applied later'); }
try { $service->clearSourceImpactReview($requirement, 'org-a', 9, ''); throw new RuntimeException('Review note was not required.'); } catch (InvalidArgumentException) { sw_expect(true, 'clearing source impact review requires a non-PHI human review note'); }
$blockingProposal = $service->createRequirementChangeProposal($requirement, 'org-a', 9, ['proposal_reason'=>'Draft must block closeout.','frequency_limit'=>'2 every 5 years']);
sw_expect(($service->requirementDetailWorkspace($requirement, 'org-a')['source_review_closeout']['ready_for_closeout'] ?? true) === false && (($service->requirementDetailWorkspace($requirement, 'org-a')['source_review_closeout']['open_change_proposal_count'] ?? 0) === 1), 'requirement detail shows source review closeout blockers before staff clear review');
try { $service->clearSourceImpactReview($requirement, 'org-a', 9, 'Reviewed source while draft proposal remains.'); throw new RuntimeException('Draft proposal did not block source review closeout.'); } catch (InvalidArgumentException) { sw_expect(true, 'source review closeout is blocked while draft requirement change proposals remain'); }
$service->rejectRequirementChangeProposal($blockingProposal, $requirement, 'org-a', 9, 'Rejected blocking draft before closeout.');
sw_expect($service->clearSourceImpactReview($requirement, 'org-a', 9, 'Reviewed updated source; requirement remains accurate.') && $service->requirements('org-a', ['source_review_status'=>'needs_source_review']) === [] && ($sources->requirements[$requirement]['source_review_reason'] ?? '') !== '', 'source impact review queue can be cleared after human requirement review with a retained note');
$summaryExport = $service->coverageSummaryExport('org-a', ['payer'=>'Payer','dme_category_slug'=>'cpap']);
sw_expect(($summaryExport['summary']['total_count'] ?? 0) === 1 && ($summaryExport['summary']['ready_count'] ?? 0) === 1 && ($summaryExport['summary']['prior_auth_ready_count'] ?? 0) === 1 && ($summaryExport['items'][0]['patient_packet_safe'] ?? true) === false, 'coverage summary exports provide filtered internal counts without becoming patient packet content');
$prep = $service->priorAuthorizationPrepWorkspace('org-a', ['payer'=>'Payer','dme_category_slug'=>'cpap']);
sw_expect(($prep['summary']['required_count'] ?? 0) === 1 && ($prep['summary']['ready_for_submission_prep_count'] ?? 0) === 1 && ($prep['summary']['blocked_count'] ?? 1) === 0 && count($prep['task_preview'] ?? []) >= 2, 'prior authorization prep workspace summarizes ready workups, blocked workups, and staff task previews');
$ops = $service->dmeCoverageOperationsDashboard('org-a', ['payer'=>'Payer','dme_category_slug'=>'cpap']);
sw_expect(($ops['summary']['total_count'] ?? 0) === 1 && ($ops['summary']['ready_count'] ?? 0) === 1 && ($ops['summary']['prior_auth_required_count'] ?? 0) === 1 && ($ops['action_rows'][0]['readiness'] ?? '') === 'ready', 'DME coverage operations dashboard summarizes readiness, prior authorization buckets, and action rows');
$profile = $service->createInsuranceProfile('org-a', 9, ['payer'=>'Payer','plan_name'=>'Gold','line_of_business'=>'commercial','jurisdiction'=>'PA']);
$dme = $service->createDmeCategory(9, ['label'=>'CPAP']);
$matches = $service->dmeRequirementMatches('org-a', ['payer'=>'Payer','plan_name'=>'Gold','dme_category'=>'CPAP','jurisdiction'=>'PA']);
sw_expect($profile === $uuid && $dme === $uuid && $matches['match_count'] === 1 && $matches['ready_count'] === 1 && ($matches['matches'][0]['readiness']['ready'] ?? false), 'insurance profiles and DME categories match published payer requirements with DME readiness without PHI');
sw_expect(($service->dashboard('org-a')['summary']['atlas_payer_requirements.published'] ?? 0) === 1, 'source workspace reports operational summary counts');
sw_expect(($service->dashboard('org-a')['change_proposal_summary']['total'] ?? 0) >= 3, 'source workspace dashboard reports proposal lifecycle summary counts');
try { $service->createRequirement('org-a', 9, ['payer'=>'Payer','topic'=>'DME','requirement_text'=>'DOB 2020-01-01']); throw new RuntimeException('PHI warning did not trigger.'); } catch (InvalidArgumentException) { sw_expect(true, 'source workspace rejects obvious patient-identifying markers'); }
sw_expect(in_array('payer_requirement.created', $audit->events, true) && in_array('packet.created', $audit->events, true), 'source and packet workspaces record audit events through services');
echo "All source workspace tests passed.\n";
