<?php
declare(strict_types=1);
define('ATLAS_PLATFORM_DIR',dirname(__DIR__).'/plugin/atlas-platform/');require ATLAS_PLATFORM_DIR.'src/Autoloader.php';Atlas\Platform\Autoloader::register();
use Atlas\Platform\Resources\Packets\PacketRepository;use Atlas\Platform\Resources\Sources\SourceWorkspaceRepository;
final class MemoryPackets implements PacketRepository{public array$packets=[];public function create(string$o,int$u,string$n,array$i,string$d=''):string{$this->packets['p1']=['id'=>'p1','org'=>$o,'user'=>$u,'name'=>$n,'description'=>$d,'status'=>'draft','items'=>$i];return'p1';}public function addItem(string$p,int$u,array$i):bool{$this->packets[$p]['items'][]=$i;return true;}public function removeItem(string$p,string$i,int$u):bool{array_pop($this->packets[$p]['items']);return true;}public function setStatus(string$p,int$u,string$s):bool{$this->packets[$p]['status']=$s;return true;}public function findForUser(string$p,int$u,?string$o):?array{return isset($this->packets[$p])?['packet'=>$this->packets[$p],'items'=>$this->packets[$p]['items']]:null;}public function listForUser(int$u,?string$o,int$l=25):array{return array_values(array_filter($this->packets,fn($p)=>$p['user']===$u||$p['org']===$o));}}
final class MemorySources implements SourceWorkspaceRepository{public array$docs=[],$sections=[],$candidates=[],$requirements=[];public function createDocument(?string$o,int$u,array$i):string{$this->docs['d1']=$i+['id'=>'d1','org'=>$o,'user'=>$u,'extraction_status'=>'queued'];return'd1';}public function updateDocumentStatus(string$id,?string$o,string$s,string$n=''):bool{$this->docs[$id]['extraction_status']=$s;return true;}public function createSection(string$d,array$i):string{$this->sections[]=$i+['doc'=>$d];return's1';}public function createCandidate(string$s,?string$o,array$i):string{$this->candidates['c1']=$i+['section'=>$s,'org'=>$o,'status'=>'pending'];return'c1';}public function reviewCandidate(string$id,string$status,int$user):bool{if(!isset($this->candidates[$id])||!in_array($status,['approved','rejected','needs_changes'],true)){return false;}$this->candidates[$id]['status']=$status;return true;}public function createRequirement(?string$o,int$u,array$i):string{$this->requirements['r1']=$i+['id'=>'r1','org'=>$o,'user'=>$u,'review_status'=>'draft'];return'r1';}public function reviewRequirement(string$id,?string$o,string$s,int$u):bool{$this->requirements[$id]['review_status']=$s;return true;}public function documents(?string$o,int$l=25):array{return array_values($this->docs);}public function candidates(?string$o,int$l=25):array{return array_values($this->candidates);}public function requirements(?string$o,int$l=25,array$c=[]):array{return array_values(array_filter($this->requirements,fn($r)=>($c['status']??'')===''||$r['review_status']===$c['status']));}public function summary(?string$o):array{return['atlas_source_documents.queued'=>count($this->docs),'atlas_extraction_candidates.approved'=>1,'atlas_payer_requirements.published'=>isset($this->requirements['r1'])&&$this->requirements['r1']['review_status']==='published'?1:0];}}
function sw_expect(bool$c,string$m):void{if(!$c){throw new RuntimeException($m);}echo"PASS: {$m}\n";}
$packets=new MemoryPackets();$packet=$packets->create('org-a',7,'Discharge packet',[['type'=>'resource','id'=>'r1']],'After visit');$packets->addItem($packet,7,['type'=>'requirement','id'=>'req1']);$packets->setStatus($packet,7,'ready');sw_expect(count($packets->findForUser($packet,7,'org-a')['items']??[])===2&&$packets->listForUser(7,'org-a')[0]['status']==='ready','packet builder manages items and lifecycle');
$sources=new MemorySources();$doc=$sources->createDocument('org-a',7,['title'=>'Policy','publisher'=>'Payer']);$sources->updateDocumentStatus($doc,'org-a','ready');$section=$sources->createSection($doc,['page_number'=>2,'text_excerpt'=>'Must document use.']);$candidate=$sources->createCandidate($section,'org-a',['statement'=>'Requires documentation.']);sw_expect($sources->reviewCandidate($candidate,'approved',9),'extraction candidates require explicit review decisions');$requirement=$sources->createRequirement('org-a',9,['payer'=>'Payer','topic'=>'DME','requirement_text'=>'Requires documentation.','source_candidate_id'=>$candidate]);$sources->reviewRequirement($requirement,'org-a','published',9);sw_expect(($sources->requirements('org-a',25,['status'=>'published'])[0]['source_candidate_id']??'')===$candidate,'payer requirements can be filtered after review and retain provenance');sw_expect(($sources->summary('org-a')['atlas_payer_requirements.published']??0)===1,'source workspace reports operational summary counts');echo"All source workspace tests passed.\n";
