<?php declare(strict_types=1);$matrix=[
 'owner'=>['All modules','Organization and account controls','Payroll and credentials','Reset or delete demo'],
 'admin'=>['All operational modules','People and organization setup','Approvals and reporting','No demo deletion'],
 'scheduler'=>['Schedule and coverage workspaces','Planning assistance','Open-shift management','No organization administration'],
 'supervisor'=>['Team schedule and coverage','Requests, trades, and callouts','Scoped operational actions','No payroll or organization settings'],
 'member'=>['Today and My Schedule','Availability and requests','Trades, time clock, and messages','No administration modules'],
];$counts=$demoDashboard['counts'];?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demo Testing · Atlas</title><link rel="stylesheet" href="<?=esc(url_for('assets/app.css'))?>"></head><body class="standalone-with-nav"><?=standaloneSidebar($navGroups,'demo-testing',$admin,$org,$user,$location)?><main class="page-wrap standalone-workspace demo-testing-page">
<header class="page-header"><div><p class="eyebrow">QUALITY ASSURANCE</p><h1>Demo Testing Center</h1><p>Use the populated sandbox to verify each role, workflow, exception, and responsive screen without rebuilding data.</p></div><?php if(!$demoDashboard['is_demo']):?><a class="button primary" href="<?=esc(url_for('local-accounts'))?>">Create full demo</a><?php endif;?></header>
<?php if($notice):?><div class="page-flash <?=$notice['type']?>"><span>✓</span><?=esc($notice['message'])?></div><?php endif;?><?php if($error):?><div class="form-alert error"><?=esc($error)?></div><?php endif;?>
<?php if(!$demoDashboard['is_demo']):?><section class="panel demo-empty"><span class="feature-symbol">D</span><div><h2>This organization is not a demo sandbox</h2><p>Switch to an Atlas Full Demo organization, or create one from Local Accounts. Reset and deletion controls intentionally remain unavailable in real organizations.</p></div></section><?php else:?>
<section class="demo-metrics"><article><strong><?=$counts['memberships']?></strong><span>staff</span></article><article><strong><?=$counts['shifts']?></strong><span>shifts</span></article><article><strong><?=$counts['open_shifts']?></strong><span>open shifts</span></article><article><strong><?=$counts['pending_requests']?></strong><span>pending requests</span></article><article><strong><?=$counts['callouts']?></strong><span>callouts</span></article><article><strong><?=$counts['command_center_items']?></strong><span>command items</span></article></section>
<section class="panel demo-section"><div class="demo-section-head"><div><p class="eyebrow">ROLE PASS</p><h2>Accounts and expected access</h2><p>Open a private browser window for each username. Demo passwords are the value shown when the organization is created or reset.</p></div><a class="button secondary" href="<?=esc(url_for('local-accounts'))?>">Account directory</a></div><div class="role-test-grid"><?php foreach($matrix as $role=>$expectations):$account=array_values(array_filter($demoDashboard['accounts'],fn($a)=>$a['role']===$role))[0]??null;?><article class="role-test-card"><div><span class="role-dot <?=$role?>"></span><strong><?=esc(ucfirst($role))?></strong></div><code><?=esc($account['username']??($role==='owner'?'Current account':'Not seeded'))?></code><ul><?php foreach($expectations as $item):?><li><?=esc($item)?></li><?php endforeach;?></ul><label><input type="checkbox"> Navigation matches role</label><label><input type="checkbox"> Allowed action succeeds</label><label><input type="checkbox"> Restricted action blocked</label></article><?php endforeach;?></div></section>
<section class="planning-grid"><article class="panel"><h2>Scenario coverage</h2><div class="scenario-list"><?php foreach([['Schedule board',$counts['shifts'].' seeded shifts'],['Requests',$counts['time_off_requests'].' time-off examples'],['Coverage',$counts['coverage_assignments'].' assignments'],['Credentials',$counts['member_credentials'].' employee credentials'],['Labor',$counts['time_entries'].' time entries'],['Communication',$counts['message_threads'].' message threads']] as [$label,$value]):?><div><span><strong><?=esc($label)?></strong><small><?=esc($value)?></small></span><b class="state-pill covered">Ready</b></div><?php endforeach;?></div><form method="post" class="demo-action-form"><?=Csrf::field()?><input type="hidden" name="action" value="seed_demo_edge_cases"><button class="button primary">Add or refresh edge cases</button><small>Adds a pending shift request, trade approval, critical command items, forecast gap, expired credential, and missed punch.</small></form></article>
<article class="panel"><h2>Suggested smoke loop</h2><ol class="smoke-loop"><li>Owner: review configuration, reports, payroll, and demo controls.</li><li>Administrator: process requests, credentials, and workforce records.</li><li>Scheduler: edit schedules, review gaps, and assign open shifts.</li><li>Supervisor: handle a request, trade, callout, and team exception.</li><li>Member: view shifts, submit availability, clock time, and read messages.</li><li>Repeat on desktop and mobile widths, then record anything inconsistent.</li></ol></article>
<article class="panel span-2 danger-zone"><div><p class="eyebrow">DEMO LIFECYCLE</p><h2>Reset or remove this sandbox</h2><p>These controls only work for organizations whose name begins with “Atlas Full Demo.” Real organizations cannot be affected.</p></div><?php if($org['role']==='owner'):?><div class="danger-actions"><form method="post" onsubmit="return confirm('Delete this demo and rebuild it from a clean dataset? The current demo data will be permanently removed.')"><?=Csrf::field()?><input type="hidden" name="action" value="reset_demo_organization"><button class="button secondary">Reset demo</button></form><form method="post" onsubmit="return confirm('Permanently delete this demo organization and its local test accounts?')"><?=Csrf::field()?><input type="hidden" name="action" value="delete_demo_organization"><button class="button danger-button">Delete demo</button></form></div><?php else:?><span class="state-pill">Owner only</span><?php endif;?></article></section>
<?php endif;?></main></body></html>
