<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Local Accounts · Atlas</title><link rel="stylesheet" href="<?=esc(url_for('assets/app.css'))?>"></head>
<body class="standalone-with-nav"><?=standaloneSidebar($navGroups,'local-accounts',$admin,$org,$user,$location)?><main class="page-wrap standalone-workspace local-accounts-page">
<header class="page-header"><div><p class="eyebrow">ACCESS MANAGEMENT</p><h1>Local accounts</h1><p>Create users who sign in with a username and do not need an email address.</p></div></header>
<?php if($notice):?><div class="page-flash <?=$notice['type']?>"><span>✓</span><?=esc($notice['message'])?></div><?php endif;?><?php if($error):?><div class="form-alert error"><?=esc($error)?></div><?php endif;?>
<?php if($localCredentials):?><section class="panel credential-panel"><div class="credential-heading"><div><p class="eyebrow">SHOWN ONCE</p><h2>Demo sign-in credentials</h2><p>Each card keeps the username and password together. Full-demo accounts retain this password for repeated testing.</p></div><a class="button secondary" href="<?=esc(url_for('login'))?>">Open sign-in</a></div><div class="credential-grid">
<?php foreach($localCredentials as $index=>$credential):$credentialId='credential-'.$index;?><article class="credential-card"><div class="credential-person"><span class="avatar"><?=esc(initials($credential['name']))?></span><span><strong><?=esc($credential['name'])?></strong><small><?=esc(ucfirst($credential['role']))?></small></span></div><label>Username<input id="<?=$credentialId?>-username" value="<?=esc($credential['username'])?>" readonly></label><button type="button" class="copy-field" data-copy="<?=$credentialId?>-username">Copy username</button><label>Password<input id="<?=$credentialId?>-password" value="<?=esc($credential['password'])?>" readonly></label><button type="button" class="copy-field" data-copy="<?=$credentialId?>-password">Copy password</button></article><?php endforeach;?>
</div></section><?php endif;?>
<section class="planning-grid local-account-tools"><article class="panel"><h2>Organization setting</h2><form method="post" class="stack-form"><?=Csrf::field()?><input type="hidden" name="action" value="save_local_account_settings"><label class="check-label"><input type="checkbox" name="allow_local_accounts" value="1" <?=!empty($localAccountSettings['allow_local_accounts'])?'checked':''?>><span>Allow username-only accounts</span></label><button class="button primary">Save setting</button></form><hr><h2>Full demo organization</h2><p>Creates a separate sandbox with staff, schedules, requests, coverage, credentials, payroll, master schedules, messages, and every access level.</p><form method="post" onsubmit="return confirm('Create and switch to a new full demo organization?')"><?=Csrf::field()?><input type="hidden" name="action" value="create_full_demo_organization"><button class="button primary">Create full demo organization</button></form><hr><h3>Quick test accounts</h3><p>Adds four role-based accounts to this organization without generating the complete dataset.</p><form method="post" onsubmit="return confirm('Create four demo accounts in this organization?')"><?=Csrf::field()?><input type="hidden" name="action" value="seed_smoke_accounts"><button class="button secondary">Create quick test accounts</button></form></article>
<article class="panel"><h2>Add a local user</h2><form method="post" class="stack-form"><?=Csrf::field()?><input type="hidden" name="action" value="create_local_account"><label>Name<input name="name" required></label><label>Username<input name="username" required pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,39}" autocomplete="off"></label><label>Temporary password<input type="password" name="password" minlength="8" required autocomplete="new-password"></label><label>Role<select name="role"><option value="member">Team member</option><option value="supervisor">Supervisor</option><option value="scheduler">Scheduler</option><option value="admin">Administrator</option></select></label><label>Location<select name="location_id"><option value="">Not assigned</option><?php foreach($data['locations'] as $x):?><option value="<?=$x['id']?>"><?=esc($x['name'])?></option><?php endforeach;?></select></label><label>Department<select name="department_id"><option value="">Not assigned</option><?php foreach($data['departments'] as $x):?><option value="<?=$x['id']?>"><?=esc($x['name'])?></option><?php endforeach;?></select></label><label>Position<select name="position_id"><option value="">Not assigned</option><?php foreach($data['positions'] as $x):?><option value="<?=$x['id']?>"><?=esc($x['name'])?></option><?php endforeach;?></select></label><button class="button primary" <?=empty($localAccountSettings['allow_local_accounts'])?'disabled':''?>>Create local user</button></form></article>
<article class="panel span-2 local-account-list"><h2>Existing local accounts</h2><?php foreach($localAccountSettings['accounts'] as $account):?><div class="planning-row"><span><strong><?=esc($account['name'])?></strong><small>@<?=esc($account['username'])?> · <?=esc(ucfirst($account['role']))?></small></span><b class="state-pill <?=$account['status']==='active'?'covered':'gap'?>"><?=esc($account['must_change_password']?'Password change required':ucfirst($account['status']))?></b></div><?php endforeach;?><?php if(!$localAccountSettings['accounts']):?><p>No local accounts yet.</p><?php endif;?></article></section>
</main></body></html>
