<?php
declare(strict_types=1);if(!defined('ABSPATH')){exit;}$messages=['created'=>__('Resource draft created.','atlas-platform'),'restored'=>__('The existing draft request was restored.','atlas-platform'),'failed'=>__('The draft could not be created. Review the required fields and try again.','atlas-platform')];$types=['patient_education','clinical_skill','lab_reference','payer_summary','community_resource','form','quick_reference'];
?>
<div class="atlas-preview-wrap"><div class="atlas-shell"><main class="atlas-resource-main"><p class="atlas-eyebrow"><?php echo esc_html__('Resource authoring','atlas-platform'); ?></p><h1><?php echo esc_html__('Create a sourced Resource draft','atlas-platform'); ?></h1><p><?php echo esc_html__('Drafts are immutable versions. Capture the source and citation that support the content.','atlas-platform'); ?></p>
<?php if(isset($messages[$notice])):?><div class="notice notice-<?php echo $notice==='failed'?'error':'success'; ?> inline"><p><?php echo esc_html($messages[$notice]); ?><?php if($versionId!==''):?> <code><?php echo esc_html($versionId); ?></code><?php endif;?></p></div><?php endif;?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-authoring-form"><input type="hidden" name="action" value="atlas_create_resource"><input type="hidden" name="idempotency_key" value="<?php echo esc_attr(wp_generate_uuid4()); ?>"><?php wp_nonce_field('atlas_create_resource'); ?>
<section class="atlas-admin-panel"><h2><?php echo esc_html__('Identity and scope','atlas-platform'); ?></h2><div class="atlas-form-columns"><label><?php echo esc_html__('Title','atlas-platform'); ?><input required maxlength="255" name="title"></label><label><?php echo esc_html__('Slug','atlas-platform'); ?><input required maxlength="191" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" name="slug"></label><label><?php echo esc_html__('Type','atlas-platform'); ?><select required name="resource_type"><?php foreach($types as$type):?><option value="<?php echo esc_attr($type); ?>"><?php echo esc_html(ucwords(str_replace('_',' ',$type))); ?></option><?php endforeach;?></select></label><label><?php echo esc_html__('Scope','atlas-platform'); ?><select name="scope"><option value="organization"><?php echo esc_html($organization?->name??__('Current organization','atlas-platform')); ?></option><?php if(current_user_can('atlas_manage_atlas')):?><option value="platform"><?php echo esc_html__('Platform','atlas-platform'); ?></option><?php endif;?></select></label></div><label><?php echo esc_html__('Summary','atlas-platform'); ?><textarea required maxlength="2000" rows="3" name="summary"></textarea></label></section>
<section class="atlas-admin-panel"><h2><?php echo esc_html__('Discovery metadata','atlas-platform'); ?></h2><p class="description"><?php echo esc_html__('Enter comma-separated values. These fields remain structured and searchable.','atlas-platform'); ?></p><div class="atlas-form-columns"><label><?php echo esc_html__('Audiences','atlas-platform'); ?><textarea name="audiences"></textarea></label><label><?php echo esc_html__('Specialties','atlas-platform'); ?><textarea name="specialties"></textarea></label><label><?php echo esc_html__('Jurisdictions','atlas-platform'); ?><textarea name="jurisdictions"></textarea></label><label><?php echo esc_html__('Payers','atlas-platform'); ?><textarea name="payers"></textarea></label><label><?php echo esc_html__('Tags','atlas-platform'); ?><textarea name="tags"></textarea></label></div></section>
<section class="atlas-admin-panel"><h2><?php echo esc_html__('Content','atlas-platform'); ?></h2><label><?php echo esc_html__('Body','atlas-platform'); ?><textarea required rows="12" name="body" aria-describedby="atlas-body-help"></textarea></label><p id="atlas-body-help" class="description"><?php echo esc_html__('Separate paragraphs with a blank line. Structured editing controls arrive in a later enhancement. Do not enter patient-identifying information.','atlas-platform'); ?></p><label><?php echo esc_html__('Change summary','atlas-platform'); ?><textarea maxlength="2000" rows="2" name="change_summary">Initial draft</textarea></label></section>
<section class="atlas-admin-panel"><h2><?php echo esc_html__('Source and citation','atlas-platform'); ?></h2><div class="atlas-form-columns"><label><?php echo esc_html__('Publisher','atlas-platform'); ?><input required maxlength="255" name="source_publisher"></label><label><?php echo esc_html__('Source title','atlas-platform'); ?><input required maxlength="255" name="source_title"></label><label><?php echo esc_html__('Source URL','atlas-platform'); ?><input type="url" name="source_url"></label><label><?php echo esc_html__('Document identifier','atlas-platform'); ?><input maxlength="191" name="document_identifier"></label><label><?php echo esc_html__('Effective date','atlas-platform'); ?><input type="date" name="effective_date"></label><label><?php echo esc_html__('Page','atlas-platform'); ?><input maxlength="40" name="citation_page"></label><label><?php echo esc_html__('Section','atlas-platform'); ?><input maxlength="255" name="citation_section"></label></div></section><p><button class="button button-primary button-hero" type="submit"><?php echo esc_html__('Create draft','atlas-platform'); ?></button></p></form></main></div></div>
