<?php
declare(strict_types=1);if(!defined('ABSPATH')){exit;}
?>
<div class="atlas-preview-wrap"><div class="atlas-shell"><main class="atlas-resource-main">
<p><a href="<?php echo esc_url(admin_url('admin.php?page=atlas-resource-review')); ?>">&larr; <?php echo esc_html__('Review queue','atlas-platform'); ?></a></p><p class="atlas-eyebrow"><?php echo esc_html__('Immutable record','atlas-platform'); ?></p><h1><?php echo esc_html__('Resource version history','atlas-platform'); ?></h1>
<?php if($history===[]):?><div class="atlas-empty-state"><p><?php echo esc_html__('No accessible resource history was found.','atlas-platform'); ?></p></div><?php endif;?>
<div class="atlas-library-list"><?php foreach($history as$version):?><article class="atlas-library-row"><div><h2><?php echo esc_html($version['title']); ?></h2><p><?php echo esc_html(sprintf(__('Version %d · %s','atlas-platform'),$version['version_number'],ucwords(str_replace('_',' ',$version['review_status'])))); ?></p><p><?php echo esc_html($version['change_summary']); ?></p><a href="<?php echo esc_url(add_query_arg(['page'=>'atlas-resource-history','resource_id'=>$resourceId,'version_id'=>$version['id']],admin_url('admin.php'))); ?>"><?php echo esc_html__('Open review workspace','atlas-platform'); ?></a></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="atlas_create_revision"><input type="hidden" name="version_id" value="<?php echo esc_attr($version['id']); ?>"><?php wp_nonce_field('atlas_create_revision'); ?><button class="button"><?php echo esc_html__('Create revision','atlas-platform'); ?></button></form></article><?php endforeach;?></div>
<?php if($versionId!==''):?><section class="atlas-admin-panel"><h2><?php echo esc_html__('Review assignment','atlas-platform'); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-form-columns"><input type="hidden" name="action" value="atlas_assign_reviewer"><input type="hidden" name="version_id" value="<?php echo esc_attr($versionId); ?>"><?php wp_nonce_field('atlas_assign_reviewer'); ?><label><?php echo esc_html__('Reviewer','atlas-platform'); ?><select name="reviewer_user_id" required><?php foreach($reviewers as$reviewer):?><option value="<?php echo esc_attr((string)$reviewer->ID); ?>"><?php echo esc_html($reviewer->display_name?:$reviewer->user_email); ?></option><?php endforeach;?></select></label><label><?php echo esc_html__('Due date','atlas-platform'); ?><input type="date" name="due_at"></label><button class="button button-primary"><?php echo esc_html__('Assign reviewer','atlas-platform'); ?></button></form>
<h2><?php echo esc_html__('Review notes','atlas-platform'); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="atlas_add_review_note"><input type="hidden" name="version_id" value="<?php echo esc_attr($versionId); ?>"><?php wp_nonce_field('atlas_add_review_note'); ?><label><?php echo esc_html__('Note type','atlas-platform'); ?><select name="note_type"><option value="comment"><?php echo esc_html__('Comment','atlas-platform'); ?></option><option value="requested_change"><?php echo esc_html__('Requested change','atlas-platform'); ?></option><option value="decision"><?php echo esc_html__('Decision','atlas-platform'); ?></option></select></label><label><?php echo esc_html__('Note','atlas-platform'); ?><textarea required maxlength="5000" name="note_text"></textarea></label><button class="button"><?php echo esc_html__('Add note','atlas-platform'); ?></button></form>
<?php foreach($workspace['notes'] as$note):?><blockquote><strong><?php echo esc_html(ucwords(str_replace('_',' ',$note['note_type']))); ?></strong><p><?php echo nl2br(esc_html($note['note_text'])); ?></p><cite><?php echo esc_html(($note['display_name']?:__('Atlas user','atlas-platform')).' · '.$note['created_at']); ?></cite></blockquote><?php endforeach;?></section><?php endif;?>
<?php if($history!==[]):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="atlas_archive_resource"><input type="hidden" name="resource_id" value="<?php echo esc_attr($resourceId); ?>"><?php wp_nonce_field('atlas_archive_resource'); ?><button class="button"><?php echo esc_html__('Archive resource','atlas-platform'); ?></button></form><?php endif;?>
</main></div></div>
