<?php declare(strict_types=1); if (! defined('ABSPATH')) { exit; } ?>
<div class="atlas-preview-wrap<?php echo $isPrint ? ' atlas-export-mode' : ''; ?>"><div class="atlas-shell"><main class="atlas-resource-main">
<?php if (! $isPrint): ?>
<p class="atlas-eyebrow"><?php echo esc_html__('Patient packets', 'atlas-platform'); ?></p>
<h1><?php echo esc_html__('Packet builder', 'atlas-platform'); ?></h1>
<?php if ($error !== ''): ?><div class="notice notice-error inline"><p><?php echo esc_html($error); ?></p></div><?php endif; ?>
<p class="description"><?php echo esc_html__('Patient packets are reusable patient-facing education and instruction collections. Payer requirements and internal-only materials stay out of packets.', 'atlas-platform'); ?></p>

<section class="atlas-admin-panel"><h2><?php echo esc_html__('Create packet', 'atlas-platform'); ?></h2>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-authoring-form"><input type="hidden" name="action" value="atlas_create_packet"><?php wp_nonce_field('atlas_create_packet'); ?><label><?php echo esc_html__('Packet name', 'atlas-platform'); ?><input required maxlength="255" name="name"></label><label><?php echo esc_html__('Description', 'atlas-platform'); ?><textarea rows="3" name="description"></textarea></label><label><?php echo esc_html__('Optional patient-facing Resource IDs, one per line', 'atlas-platform'); ?><textarea rows="4" name="items"></textarea></label><p><button class="button button-primary"><?php echo esc_html__('Save packet', 'atlas-platform'); ?></button></p></form></section>

<section class="atlas-admin-panel"><h2><?php echo esc_html__('Saved packets', 'atlas-platform'); ?></h2><?php if ($packets === []): ?><section class="atlas-empty-state"><h3><?php echo esc_html__('No packets yet', 'atlas-platform'); ?></h3><p><?php echo esc_html__('Create a packet from reusable patient-facing resources, then preview and print it here.', 'atlas-platform'); ?></p></section><?php endif; ?><div class="atlas-library-list"><?php foreach ($packets as $row): ?><article class="atlas-library-row"><div><h2><a href="<?php echo esc_url(add_query_arg(['page' => 'atlas-packets', 'packet_id' => (string) $row['id']], admin_url('admin.php'))); ?>"><?php echo esc_html((string) $row['name']); ?></a></h2><p><?php echo esc_html(sprintf(__('Status: %s. Items: %d. Updated %s', 'atlas-platform'), (string) $row['status'], (int) ($row['item_count'] ?? 0), (string) $row['updated_at'])); ?></p></div><a class="button" href="<?php echo esc_url(add_query_arg(['page' => 'atlas-packets', 'packet_id' => (string) $row['id'], 'atlas_print' => '1'], admin_url('admin.php'))); ?>"><?php echo esc_html__('Preview / Print', 'atlas-platform'); ?></a></article><?php endforeach; ?></div></section>
<?php endif; ?>

<?php if ($selected !== null): $packet = $selected['packet']; ?>
<?php if (! $isPrint): ?>
<section class="atlas-admin-panel atlas-packet-preview-controls"><h2><?php echo esc_html((string) $packet['name']); ?></h2><p><?php echo esc_html((string) ($packet['description'] ?? '')); ?></p>
<?php if (is_array($readiness ?? null)): ?><div class="notice <?php echo ! empty($readiness['ready']) ? 'notice-success' : 'notice-warning'; ?> inline"><p><?php echo esc_html(! empty($readiness['ready']) ? __('Ready to print.', 'atlas-platform') : __('Readiness issues:', 'atlas-platform')); ?></p><?php if (empty($readiness['ready'])): ?><ul><?php foreach (($readiness['issues'] ?? []) as $issue): ?><li><?php echo esc_html((string) $issue); ?></li><?php endforeach; ?></ul><?php endif; ?></div><?php endif; ?>
<p><a class="button button-primary" href="<?php echo esc_url(add_query_arg(['page' => 'atlas-packets', 'packet_id' => (string) $packet['id'], 'atlas_print' => '1'], admin_url('admin.php'))); ?>"><?php echo esc_html__('Open print preview', 'atlas-platform'); ?></a></p>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-row-actions"><input type="hidden" name="action" value="atlas_snapshot_packet"><input type="hidden" name="packet_id" value="<?php echo esc_attr((string) $packet['id']); ?>"><?php wp_nonce_field('atlas_snapshot_packet'); ?><button class="button"><?php echo esc_html__('Save print snapshot', 'atlas-platform'); ?></button></form>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-row-actions"><input type="hidden" name="action" value="atlas_update_packet_status"><input type="hidden" name="packet_id" value="<?php echo esc_attr((string) $packet['id']); ?>"><?php wp_nonce_field('atlas_update_packet_status'); ?><button class="button" name="status" value="draft"><?php echo esc_html__('Draft', 'atlas-platform'); ?></button><button class="button button-primary" name="status" value="ready"><?php echo esc_html__('Mark ready', 'atlas-platform'); ?></button><button class="button" name="status" value="archived"><?php echo esc_html__('Archive', 'atlas-platform'); ?></button></form></section>
<?php endif; ?>

<section class="atlas-patient-preview atlas-packet-print"><header><strong><?php echo esc_html((string) $packet['name']); ?></strong><span><?php echo esc_html(($snapshot ?? null) !== null ? __('Historical packet snapshot', 'atlas-platform') : __('Patient-facing Atlas packet', 'atlas-platform')); ?></span></header><?php if ((string) ($packet['description'] ?? '') !== ''): ?><p class="atlas-resource-summary"><?php echo esc_html((string) $packet['description']); ?></p><?php endif; ?><?php if ($selected['items'] === []): ?><section class="atlas-empty-state"><h3><?php echo esc_html__('No packet items', 'atlas-platform'); ?></h3><p><?php echo esc_html__('Add reusable patient education resources or patient-facing instructions before printing this packet.', 'atlas-platform'); ?></p></section><?php endif; ?><ol class="atlas-packet-items"><?php foreach ($selected['items'] as $item): ?><li><article class="atlas-packet-item is-<?php echo esc_attr((string) $item['type']); ?>"><h2><?php echo esc_html((string) ($item['title'] ?: $item['item_id'])); ?></h2><p class="atlas-eyebrow"><?php echo esc_html((string) $item['type'] . ' · ' . (string) $item['status']); ?></p><?php if ((string) ($item['summary'] ?? '') !== ''): ?><p class="atlas-resource-summary"><?php echo esc_html((string) $item['summary']); ?></p><?php endif; ?><?php if ((string) $item['notes'] !== ''): ?><p><?php echo esc_html((string) $item['notes']); ?></p><?php endif; ?><?php if ((string) ($item['html'] ?? '') !== ''): ?><div class="atlas-resource-content"><?php echo wp_kses_post((string) $item['html']); ?></div><?php endif; ?><?php if (($item['provenance'] ?? []) !== []): ?><div class="atlas-trust-strip"><?php foreach ($item['provenance'] as $source): ?><span><?php echo esc_html((string) ($source['publisher'] ?? $source['label'] ?? __('Source', 'atlas-platform'))); ?><?php if ((string) ($source['title'] ?? $source['value'] ?? '') !== ''): ?>: <?php echo esc_html((string) ($source['title'] ?? $source['value'])); ?><?php endif; ?></span><?php endforeach; ?></div><?php endif; ?><small><?php echo esc_html((string) $item['item_id']); ?></small><?php if (! $isPrint && ($snapshot ?? null) === null): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="atlas_remove_packet_item"><input type="hidden" name="packet_id" value="<?php echo esc_attr((string) $packet['id']); ?>"><input type="hidden" name="packet_item_id" value="<?php echo esc_attr((string) $item['id']); ?>"><?php wp_nonce_field('atlas_remove_packet_item'); ?><button class="button"><?php echo esc_html__('Remove', 'atlas-platform'); ?></button></form><?php endif; ?></article></li><?php endforeach; ?></ol><footer><small><?php echo esc_html__('Packet content is reusable patient-facing material and must not contain patient-identifying information or internal payer requirements.', 'atlas-platform'); ?></small></footer></section>

<?php if (! $isPrint && ($snapshot ?? null) === null): ?>
<section class="atlas-admin-panel"><h3><?php echo esc_html__('Add item', 'atlas-platform'); ?></h3><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="atlas-authoring-form"><input type="hidden" name="action" value="atlas_add_packet_item"><input type="hidden" name="packet_id" value="<?php echo esc_attr((string) $packet['id']); ?>"><?php wp_nonce_field('atlas_add_packet_item'); ?><div class="atlas-form-columns"><label><?php echo esc_html__('Patient resource picker', 'atlas-platform'); ?><select name="item_id"><option value=""><?php echo esc_html__('Select a published patient education resource', 'atlas-platform'); ?></option><?php foreach (($patientResources ?? []) as $resource): ?><option value="<?php echo esc_attr((string) $resource['id']); ?>"><?php echo esc_html((string) $resource['title']); ?></option><?php endforeach; ?></select></label><label><?php echo esc_html__('Item type', 'atlas-platform'); ?><select name="item_type"><option value="resource">Patient-facing Resource</option><option value="instruction">Patient-facing Instruction</option></select></label><label><?php echo esc_html__('Title', 'atlas-platform'); ?><input name="title"></label><label><?php echo esc_html__('Notes', 'atlas-platform'); ?><textarea rows="3" name="notes"></textarea></label></div><p><button class="button"><?php echo esc_html__('Add item', 'atlas-platform'); ?></button></p></form></section>
<section class="atlas-admin-panel"><h3><?php echo esc_html__('Snapshot history', 'atlas-platform'); ?></h3><?php if (($snapshots ?? []) === []): ?><p><?php echo esc_html__('No print snapshots saved yet.', 'atlas-platform'); ?></p><?php endif; ?><div class="atlas-library-list"><?php foreach (($snapshots ?? []) as $snap): $snapData = $snap['snapshot'] ?? []; ?><article class="atlas-library-row"><div><h2><?php echo esc_html((string) ($snap['created_at'] ?? '')); ?></h2><p><?php echo esc_html(sprintf(__('Status: %s. Items: %d. Actor: %d', 'atlas-platform'), (string) ($snap['packet_status'] ?? ''), count((array) ($snapData['items'] ?? [])), (int) ($snap['actor_user_id'] ?? 0))); ?></p></div><a class="button" href="<?php echo esc_url(add_query_arg(['page' => 'atlas-packets', 'packet_id' => (string) $packet['id'], 'snapshot_id' => (string) $snap['id']], admin_url('admin.php'))); ?>"><?php echo esc_html__('Open snapshot', 'atlas-platform'); ?></a></article><?php endforeach; ?></div></section>
<?php endif; ?>
<?php if ($isPrint): ?><script>window.addEventListener('load',function(){window.print();});</script><?php endif; ?>
<?php endif; ?>
</main></div></div>
