<?php
declare(strict_types=1);if(!defined('ABSPATH')){exit;}
$messages=['updated'=>__('Editorial status updated.','atlas-platform'),'not-found'=>__('The Resource Version was not found or is no longer accessible.','atlas-platform'),'failed'=>__('The operation could not be completed. Refresh and try again.','atlas-platform'),'revision-created'=>__('A new draft revision was created.','atlas-platform'),'archived'=>__('The resource was archived.','atlas-platform'),'assigned'=>__('Reviewer assigned.','atlas-platform'),'note-added'=>__('Review note added.','atlas-platform')];
$actions=['draft'=>['in_review'=>__('Submit for review','atlas-platform')],'in_review'=>['draft'=>__('Return to draft','atlas-platform'),'approved'=>__('Approve','atlas-platform')],'approved'=>['draft'=>__('Return to draft','atlas-platform'),'published'=>__('Publish','atlas-platform')],'review_due'=>['in_review'=>__('Start review','atlas-platform')]];
?>
<div class="atlas-preview-wrap"><div class="atlas-shell"><main class="atlas-resource-main">
<p class="atlas-eyebrow"><?php echo esc_html__('Clinical governance','atlas-platform'); ?></p><h1><?php echo esc_html__('Resource review queue','atlas-platform'); ?></h1><p><?php echo esc_html__('Review immutable versions in the current organization context. Publishing requires separate authority.','atlas-platform'); ?></p>
<?php if(isset($messages[$notice])):?><div class="notice notice-<?php echo $notice==='failed'?'error':'success'; ?> inline"><p><?php echo esc_html($messages[$notice]); ?></p></div><?php endif;?>
<?php if($items===[]):?><section class="atlas-empty-state"><h2><?php echo esc_html__('The review queue is clear.','atlas-platform'); ?></h2></section><?php else:?><div class="atlas-library-list">
<?php foreach($items as$item):?><article class="atlas-library-row"><div><div class="atlas-card-meta"><span><?php echo esc_html(ucfirst($item->scope)); ?></span><span><?php echo esc_html(sprintf(__('Version %d','atlas-platform'),$item->versionNumber)); ?></span><span class="atlas-status-dot"><?php echo esc_html(ucwords(str_replace('_',' ',$item->status))); ?></span></div><h2><?php echo esc_html($item->title); ?></h2><p><?php echo esc_html($item->summary); ?></p><a href="<?php echo esc_url(add_query_arg(['page'=>'atlas-resource-history','resource_id'=>$item->resourceId,'version_id'=>$item->versionId],admin_url('admin.php'))); ?>"><?php echo esc_html__('History and review workspace','atlas-platform'); ?></a></div>
<div class="atlas-row-actions"><?php foreach($actions[$item->status]??[] as$to=>$label):if($to==='published'&&!current_user_can('atlas_publish_resources'))continue;?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="atlas_editorial_transition"><input type="hidden" name="version_id" value="<?php echo esc_attr($item->versionId); ?>"><input type="hidden" name="to" value="<?php echo esc_attr($to); ?>"><input type="hidden" name="idempotency_key" value="<?php echo esc_attr(wp_generate_uuid4()); ?>"><?php wp_nonce_field('atlas_editorial_transition'); ?><button class="button<?php echo $to==='published'?' button-primary':''; ?>"><?php echo esc_html($label); ?></button></form><?php endforeach;?></div></article><?php endforeach;?>
</div><?php endif;?></main></div></div>
