<?php

declare(strict_types=1);

namespace Atlas\Support;

final class Fixtures
{
    public static function enabled(): bool{return(bool)apply_filters('atlas_enable_demo_data',true);}private static function data(array$d):array{return self::enabled()?$d:[];}
    public static function dashboard():array{return self::data(['welcome'=>'Good evening','organization'=>'Atlas Demo Health','quick_actions'=>[['label'=>'Find a resource','href'=>'/resources','hint'=>'Clinical and operational references'],['label'=>'Check payer requirements','href'=>'/insurance','hint'=>'Coverage, documentation, and forms'],['label'=>'Open a playbook','href'=>'/playbooks','hint'=>'Step-by-step operational guidance']],'recent'=>[['title'=>'Home Oxygen Qualification & Documentation','type'=>'Resource','meta'=>'Reviewed Jul 2026'],['title'=>'Medicare DME: Oxygen','type'=>'Payer requirement','meta'=>'Effective Jan 2026'],['title'=>'Arrange Home Oxygen','type'=>'Playbook','meta'=>'7 steps']]]);}
    public static function resources():array{return self::data([
        ['slug'=>'home-oxygen-qualification','title'=>'Home Oxygen Qualification & Documentation','summary'=>'A practical guide to qualifying testing, documentation, and discharge coordination for home oxygen.','category'=>'DME','audience'=>'Nursing + Care Management','reviewed'=>'Jul 18, 2026','trust'=>'Reviewed','source'=>'CMS Medicare Learning Network'],
        ['slug'=>'snf-placement-checklist','title'=>'Skilled Nursing Facility Placement Checklist','summary'=>'What to gather, confirm, and communicate before sending a referral for post-acute skilled nursing placement.','category'=>'Post-acute','audience'=>'Care Management','reviewed'=>'Jul 11, 2026','trust'=>'Reviewed','source'=>'Atlas Demo Health'],
        ['slug'=>'home-health-eligibility','title'=>'Home Health Eligibility Guide','summary'=>'Fast reference for homebound status, skilled need, ordering requirements, and common referral pitfalls.','category'=>'Home Health','audience'=>'Clinical Teams','reviewed'=>'Jun 29, 2026','trust'=>'Reviewed','source'=>'CMS'],
        ['slug'=>'transportation-options','title'=>'Non-Emergency Transportation Options','summary'=>'Decision support for choosing transportation based on mobility, payer, medical need, and destination.','category'=>'Transportation','audience'=>'Care Coordination','reviewed'=>'Jun 14, 2026','trust'=>'Local review','source'=>'Atlas Demo Health'],
        ['slug'=>'dme-documentation','title'=>'Durable Medical Equipment Documentation Basics','summary'=>'Core documentation elements that commonly determine whether DME orders move forward or bounce back.','category'=>'DME','audience'=>'Prescribers + Nursing','reviewed'=>'May 31, 2026','trust'=>'Reviewed','source'=>'CMS']]);}
    public static function resource(string$slug):?array{foreach(self::resources()as$r)if($r['slug']===$slug)return$r+['key_points'=>['Confirm the qualifying clinical criteria before the patient leaves the care setting.','Match the order and supporting documentation to the payer requirement.','Document the result that establishes medical necessity and make the source easy to locate.'],'workflow'=>['Verify qualifying test or assessment','Confirm order language and prescriber documentation','Identify in-network supplier','Send complete referral packet','Confirm acceptance and delivery plan'],'citation'=>'Centers for Medicare & Medicaid Services. Medicare coverage guidance and supplier documentation requirements.','related'=>['Arrange Home Oxygen','Medicare DME: Oxygen','Home Oxygen: What to Expect']];return null;}
    public static function insurance():array{return self::data([
        ['slug'=>'medicare-dme-oxygen','title'=>'Home Oxygen Coverage & Documentation','summary'=>'Qualification, ordering, and supplier documentation for home oxygen.','payer'=>'Original Medicare','context'=>'DME / Home oxygen','effective'=>'Jan 1, 2026','status'=>'Current'],
        ['slug'=>'medicare-home-health','title'=>'Home Health Eligibility','summary'=>'Homebound status, skilled need, plan of care, and certification requirements.','payer'=>'Original Medicare','context'=>'Home Health','effective'=>'Jan 1, 2026','status'=>'Current'],
        ['slug'=>'demo-ma-dme','title'=>'DME Prior Authorization Basics','summary'=>'Demonstration requirement showing plan-specific authorization and network context.','payer'=>'Harbor Medicare Advantage','context'=>'DME','effective'=>'Apr 1, 2026','status'=>'Demo'],
        ['slug'=>'demo-medicaid-transport','title'=>'Non-Emergency Medical Transportation','summary'=>'Demonstration benefit requirements for covered transportation.','payer'=>'Chesapeake Medicaid','context'=>'Transportation','effective'=>'Jul 1, 2026','status'=>'Review soon']]);}
    public static function insuranceDetail():?array{if(!self::enabled())return null;return['title'=>'Home Oxygen Coverage & Documentation','payer'=>'Original Medicare','summary'=>'Use this requirement to confirm that the clinical record, order, qualifying test, and supplier packet align before discharge.','source'=>'CMS National Coverage Determination / DME guidance','anchor'=>'Home use of oxygen and supplier documentation','effective'=>'Jan 1, 2026','requirements'=>['A qualifying blood gas or oxygen saturation test is documented under the applicable coverage criteria.','The treating practitioner documents the condition supporting oxygen therapy and the need for home use.','The order contains the equipment and flow or use instructions required by the supplier.','The supplier receives enough supporting documentation to establish coverage before delivery.'],'documents'=>['Signed order','Qualifying test result','Relevant progress note','Demographics + coverage','Discharge timing'],'warning'=>'Do not send only the oxygen order. Missing qualifying results or clinical documentation is a common reason the referral is returned.'];}
    public static function playbooks():array{return self::data([
        ['slug'=>'arrange-home-oxygen','title'=>'Arrange Home Oxygen','summary'=>'Move from qualifying test to confirmed home delivery without losing the thread between clinical criteria, payer rules, and supplier logistics.','area'=>'DME + Discharge','status'=>'Published','steps'=>7,'time'=>'10–20 min','progress'=>100],
        ['slug'=>'snf-discharge','title'=>'Discharge to Skilled Nursing Facility','summary'=>'Coordinate referral readiness, payer authorization, acceptance, transport, and handoff.','area'=>'Post-acute','status'=>'Published','steps'=>8,'time'=>'20–40 min','progress'=>100],
        ['slug'=>'home-health','title'=>'Arrange Home Health Services','summary'=>'Confirm eligibility, obtain orders, identify an agency, and close the loop on acceptance.','area'=>'Home Health','status'=>'Published','steps'=>6,'time'=>'10–20 min','progress'=>100],
        ['slug'=>'dme-order','title'=>'Obtain Durable Medical Equipment','summary'=>'Identify the right equipment pathway and assemble a referral that can be acted on the first time.','area'=>'DME','status'=>'Draft demo','steps'=>5,'time'=>'10–15 min','progress'=>72]]);}
    public static function playbookDetail():?array{if(!self::enabled())return null;return['title'=>'Arrange Home Oxygen','summary'=>'A guided operational path from clinical qualification to confirmed home delivery.','area'=>'DME + Discharge','steps_count'=>7,'reviewed'=>'Jul 18, 2026','documents'=>['Qualifying test','Signed oxygen order','Progress note','Face sheet','Coverage information'],'steps'=>[
        ['title'=>'Confirm the discharge plan','detail'=>'Verify that home oxygen is part of the intended discharge plan and identify the expected discharge window.'],
        ['title'=>'Verify qualifying oxygen testing','detail'=>'Locate the qualifying saturation or blood gas result and make sure it is usable for the payer context.','warning'=>'A test result buried in narrative documentation may not be enough for the supplier.'],
        ['title'=>'Confirm prescriber documentation','detail'=>'Make sure the clinical note supports the condition and need for home oxygen.'],
        ['title'=>'Obtain a complete order','detail'=>'Confirm equipment, flow or use instructions, route, frequency, and prescriber signature as required.'],
        ['title'=>'Choose an appropriate supplier','detail'=>'Use payer and geography context to identify a supplier that can serve the patient.'],
        ['title'=>'Send the complete referral packet','detail'=>'Transmit the order, qualifying result, relevant note, demographics, coverage, and timing together.'],
        ['title'=>'Close the loop','detail'=>'Confirm supplier acceptance, delivery timing, and the handoff plan before the patient leaves.']]];}
    public static function knowledgeBase():array{return self::data([
        ['slug'=>'discharge-documentation-standard','title'=>'Discharge Documentation Standard','summary'=>'Minimum documentation expectations for safe, complete discharge handoff.','type'=>'Policy','owner'=>'Care Transitions Council','review'=>'Jul 2027'],
        ['slug'=>'after-hours-dme','title'=>'After-Hours DME Escalation','summary'=>'Escalation path when an equipment need threatens a safe discharge outside normal business hours.','type'=>'SOP','owner'=>'Case Management','review'=>'Mar 2027'],
        ['slug'=>'transport-safety','title'=>'Transportation Safety Reference','summary'=>'Choosing transportation based on mobility, supervision needs, and clinical stability.','type'=>'Reference','owner'=>'Nursing Operations','review'=>'Jan 2027'],
        ['slug'=>'home-health-referral','title'=>'Home Health Referral Standard','summary'=>'Local expectations for referral completeness, agency communication, and handoff closure.','type'=>'Policy','owner'=>'Population Health','review'=>'Oct 2026']]);}
    public static function knowledgeDetail():?array{if(!self::enabled())return null;return['title'=>'Discharge Documentation Standard','summary'=>'Local minimum expectations for documenting a safe discharge and handing the plan to the next care setting.','type'=>'Policy','owner'=>'Care Transitions Council','reviewed'=>'Jul 22, 2026','next_review'=>'Jul 2027','requirements'=>['Document the destination and responsible receiving party or service when applicable.','Reconcile and communicate medications and outstanding follow-up needs.','Record equipment, services, transportation, and education required for a safe transition.','Document unresolved barriers and the escalation or contingency plan.','Confirm that required handoff information was sent to the receiving care setting when applicable.'],'escalation'=>'If a required discharge element cannot be completed, document the barrier, notify the responsible clinical or care-management lead, and record the agreed contingency before discharge.'];}
}
