<?php
declare(strict_types=1);
namespace Atlas\Platform\Resources\Editorial;
final class WordPressResourceGovernanceRepository implements ResourceGovernanceRepository
{
private string$r;private string$v;private string$c;private string$a;private string$n;
public function __construct(private object$db){$this->r=$db->prefix.'atlas_resources';$this->v=$db->prefix.'atlas_resource_versions';$this->c=$db->prefix.'atlas_citations';$this->a=$db->prefix.'atlas_editorial_assignments';$this->n=$db->prefix.'atlas_editorial_notes';}
private function scope(bool$platform):string{return$platform?"(r.scope IN ('platform','public') OR (r.scope='organization' AND r.organization_id=%s))":"(r.scope='organization' AND r.organization_id=%s)";}
public function history(string$id,?string$org,bool$platform):array{$rows=$this->db->get_results($this->db->prepare("SELECT v.* FROM `{$this->v}` v INNER JOIN `{$this->r}` r ON r.id=v.resource_id WHERE r.id=%s AND ".$this->scope($platform)." ORDER BY v.version_number DESC",$id,$org??''),ARRAY_A);return is_array($rows)?$rows:[];}
public function revise(string$id,?string$org,bool$platform,int$actor):?string
{
$row=$this->db->get_row($this->db->prepare("SELECT v.* FROM `{$this->v}` v INNER JOIN `{$this->r}` r ON r.id=v.resource_id WHERE v.id=%s AND ".$this->scope($platform)." LIMIT 1",$id,$org??''),ARRAY_A);if(!is_array($row)){return null;}$new=wp_generate_uuid4();$number=(int)$this->db->get_var($this->db->prepare("SELECT COALESCE(MAX(version_number),0)+1 FROM `{$this->v}` WHERE resource_id=%s",$row['resource_id']));$ok=$this->db->insert($this->v,['id'=>$new,'resource_id'=>$row['resource_id'],'version_number'=>$number,'title'=>$row['title'],'summary'=>$row['summary'],'body_json'=>$row['body_json'],'review_status'=>'draft','effective_date'=>$row['effective_date'],'review_due_date'=>null,'change_summary'=>'Revision from version '.$row['version_number'],'author_user_id'=>$actor,'created_at'=>current_time('mysql',true)]);if($ok===false){return null;}$citations=$this->db->get_results($this->db->prepare("SELECT * FROM `{$this->c}` WHERE resource_version_id=%s ORDER BY display_order",$id),ARRAY_A);foreach(is_array($citations)?$citations:[] as$c){unset($c['id']);$c['id']=wp_generate_uuid4();$c['resource_version_id']=$new;$c['citation_key']=hash('sha256',wp_json_encode([$new,$c['source_id'],$c['page_reference'],$c['section_reference']]));$this->db->insert($this->c,$c);}return$new;
}
public function archive(string$id,?string$org,bool$platform):bool{return$this->db->query($this->db->prepare("UPDATE `{$this->r}` r SET archived_at=%s,updated_at=%s WHERE r.id=%s AND ".$this->scope($platform),current_time('mysql',true),current_time('mysql',true),$id,$org??''))===1;}
private function accessible(string$id,?string$org,bool$platform):bool{$found=$this->db->get_var($this->db->prepare("SELECT v.id FROM `{$this->v}` v INNER JOIN `{$this->r}` r ON r.id=v.resource_id WHERE v.id=%s AND ".$this->scope($platform)." LIMIT 1",$id,$org??''));return is_string($found)&&$found!=='';}
public function assign(string$id,int$reviewer,?string$due,?string$org,bool$platform):bool{if($reviewer<1||!$this->accessible($id,$org,$platform)){return false;}return$this->db->replace($this->a,['resource_version_id'=>$id,'reviewer_user_id'=>$reviewer,'due_at'=>$due,'assigned_by'=>get_current_user_id(),'assigned_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)])!==false;}
public function addNote(string$id,int$author,string$type,string$text,?string$org,bool$platform):bool{if(!$this->accessible($id,$org,$platform)){return false;}return$this->db->insert($this->n,['id'=>wp_generate_uuid4(),'resource_version_id'=>$id,'author_user_id'=>$author,'note_type'=>$type,'note_text'=>$text,'created_at'=>current_time('mysql',true)])!==false;}
public function workspace(string$id,?string$org,bool$platform):array{if(!$this->accessible($id,$org,$platform)){return['assignment'=>null,'notes'=>[]];}$assignment=$this->db->get_row($this->db->prepare("SELECT a.*,u.display_name,u.user_email FROM `{$this->a}` a LEFT JOIN `{$this->db->users}` u ON u.ID=a.reviewer_user_id WHERE a.resource_version_id=%s",$id),ARRAY_A);$notes=$this->db->get_results($this->db->prepare("SELECT n.*,u.display_name FROM `{$this->n}` n LEFT JOIN `{$this->db->users}` u ON u.ID=n.author_user_id WHERE n.resource_version_id=%s ORDER BY n.created_at DESC",$id),ARRAY_A);return['assignment'=>is_array($assignment)?$assignment:null,'notes'=>is_array($notes)?$notes:[]];}
}
