<?php
declare(strict_types=1);
namespace Atlas\Platform\Resources\Sources;
use Atlas\Platform\Core\Audit\AuditRecorder;
use InvalidArgumentException;
final class SourceWorkspaceService
{
public function __construct(private SourceWorkspaceRepository$repo,private AuditRecorder$audit){}
public function createDocument(?string$org,int$user,array$input):string{$this->user($user);$data=['title'=>$this->text($input,'title',255,true),'publisher'=>$this->text($input,'publisher',255,true),'source_url'=>$this->url($input['source_url']??''),'document_type'=>$this->key($input['document_type']??'policy',['policy','manual','form','guideline','organization_policy'],'policy'),'effective_date'=>$this->date($input['effective_date']??null),'checksum'=>$this->text($input,'checksum',128,false),'notes'=>$this->noPhi($this->text($input,'notes',2000,false))];$id=$this->repo->createDocument($org,$user,$data);$this->audit->record('source.document_created','resources',$user,$org,'source_document',$id,['publisher'=>$data['publisher'],'document_type'=>$data['document_type']]);return$id;}
public function updateDocumentStatus(string$id,?string$org,string$status,string$notes,int$user):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['queued','extracting','ready','stale','failed'],'');if($status===''){throw new InvalidArgumentException('Source status is invalid.');}$ok=$this->repo->updateDocumentStatus($id,$org,$status,$this->noPhi(substr(trim($notes),0,2000)));if($ok){$this->audit->record('source.document_status_updated','resources',$user,$org,'source_document',$id,['status'=>$status]);}return$ok;}
public function createSection(string$doc,array$input,int$user):string{$this->user($user);$doc=$this->id($doc);$data=['page_number'=>max(0,(int)($input['page_number']??0)),'section_label'=>$this->text($input,'section_label',191,false),'text_excerpt'=>$this->noPhi($this->text($input,'text_excerpt',5000,true)),'anchor'=>$this->text($input,'anchor',191,false)];$id=$this->repo->createSection($doc,$data);$this->audit->record('source.section_created','resources',$user,null,'source_section',$id,['source_document_id'=>$doc]);return$id;}
public function createCandidate(string$section,?string$org,array$input,int$user):string{$this->user($user);$section=$this->id($section);$data=['candidate_type'=>$this->key($input['candidate_type']??'requirement',['requirement','exception','definition','form','warning'],'requirement'),'statement'=>$this->noPhi($this->text($input,'statement',5000,true))];$id=$this->repo->createCandidate($section,$org,$data);$this->audit->record('extraction.candidate_created','resources',$user,$org,'extraction_candidate',$id,['candidate_type'=>$data['candidate_type']]);return$id;}
public function reviewCandidate(string$id,string$status,int$user,?string$org=null):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['approved','rejected','needs_changes'],'');if($status===''){throw new InvalidArgumentException('Candidate review status is invalid.');}$ok=$this->repo->reviewCandidate($id,$status,$user);if($ok){$this->audit->record('extraction.candidate_reviewed','resources',$user,$org,'extraction_candidate',$id,['status'=>$status]);}return$ok;}
public function createRequirement(?string$org,int$user,array$input):string{$this->user($user);$data=['payer'=>$this->text($input,'payer',191,true),'plan_name'=>$this->text($input,'plan_name',191,false),'topic'=>$this->text($input,'topic',191,true),'jurisdiction'=>$this->text($input,'jurisdiction',120,false),'requirement_type'=>$this->key($input['requirement_type']??'documentation',['documentation','eligibility','prior_authorization','frequency_limit','form','exception'],'documentation'),'requirement_text'=>$this->noPhi($this->text($input,'requirement_text',5000,true)),'source_candidate_id'=>$this->optionalId($input['source_candidate_id']??''),'effective_date'=>$this->date($input['effective_date']??null),'expires_at'=>$this->date($input['expires_at']??null)];$id=$this->repo->createRequirement($org,$user,$data);$this->audit->record('payer_requirement.created','resources',$user,$org,'payer_requirement',$id,['payer'=>$data['payer'],'topic'=>$data['topic']]);return$id;}
public function reviewRequirement(string$id,?string$org,string$status,int$user):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['draft','in_review','published','retired'],'');if($status===''){throw new InvalidArgumentException('Requirement review status is invalid.');}$ok=$this->repo->reviewRequirement($id,$org,$status,$user);if($ok){$this->audit->record('payer_requirement.reviewed','resources',$user,$org,'payer_requirement',$id,['status'=>$status]);}return$ok;}
public function requirements(?string$org,array$criteria=[],int$limit=25):array{return$this->repo->requirements($org,$limit,['payer'=>$this->text($criteria,'payer',191,false),'topic'=>$this->text($criteria,'topic',191,false),'status'=>$this->key($criteria['status']??'',['draft','in_review','published','retired'],'')]);}
public function documentationChecklist(?string$org,array$criteria=[],int$limit=25):array{$requirements=$this->requirements($org,$criteria,$limit);$state=$this->repo->checklistState(array_map(static fn($r):string=>(string)($r['id']??''),$requirements),$org);$items=[];foreach($requirements as$requirement){$id=(string)($requirement['id']??'');$checks=$this->applyChecklistState($id,$this->checklistItems((string)($requirement['requirement_text']??'')),$state);$evidence=$this->requirementEvidence($id,$org);$items[]=['id'=>$id,'payer'=>(string)($requirement['payer']??''),'plan_name'=>(string)($requirement['plan_name']??''),'topic'=>(string)($requirement['topic']??''),'requirement_type'=>(string)($requirement['requirement_type']??''),'review_status'=>(string)($requirement['review_status']??''),'checklist_items'=>$checks,'evidence'=>$evidence];}return$items;}
public function requirementEvidence(string$id,?string$org):?array{$id=$this->id($id);$requirement=$this->repo->findRequirement($id,$org);if($requirement===null){return null;}$state=$this->repo->checklistState([$id],$org);$sourceId=(string)($requirement['source_candidate_id']??'');$source=$sourceId===''?null:$this->repo->findRequirementSource($sourceId,$org);return['requirement'=>$requirement,'source'=>$source,'checklist_items'=>$this->applyChecklistState($id,$this->checklistItems((string)($requirement['requirement_text']??'')),$state)];}
public function updateChecklistState(string$requirementId,?string$org,string$hash,string$label,string$status,string$notes,int$user):bool{$this->user($user);$requirementId=$this->id($requirementId);if($this->repo->findRequirement($requirementId,$org)===null){return false;}$status=$this->key($status,['needed','collected','waived','not_applicable'],'');if($status===''){throw new InvalidArgumentException('Checklist status is invalid.');}$ok=$this->repo->saveChecklistState($requirementId,$org,substr($hash,0,64),$this->noPhi(substr(trim($label),0,1000)),$status,$this->noPhi(substr(trim($notes),0,1000)),$user);if($ok){$this->audit->record('documentation_checklist.updated','resources',$user,$org,'payer_requirement',$requirementId,['status'=>$status,'checklist_hash'=>$hash]);}return$ok;}
public function checklistExport(?string$org,array$criteria=[]):array{return['generated_at'=>gmdate('c'),'internal_only'=>true,'items'=>$this->documentationChecklist($org,$criteria+['status'=>'published'],100)];}
public function dashboard(?string$org):array{$requirements=$this->requirements($org,[],100);return['summary'=>$this->repo->summary($org),'documents'=>$this->repo->documents($org),'candidates'=>$this->repo->candidates($org),'requirements'=>array_slice($requirements,0,50),'review_lanes'=>$this->reviewLanes($requirements),'freshness_alerts'=>$this->freshnessAlerts($requirements,$this->repo->documents($org,100))];}
private function user(int$user):void{if($user<=0){throw new InvalidArgumentException('A signed-in Atlas user is required.');}}
private function text(array$input,string$key,int$max,bool$required):string{$value=substr(trim((string)($input[$key]??'')),0,$max);if($required&&$value===''){throw new InvalidArgumentException("{$key} is required.");}return$value;}
private function noPhi(string$value):string{if(preg_match('/\b(?:MRN|DOB|SSN)\b|(?:\d{3}-\d{2}-\d{4})/i',$value)===1){throw new InvalidArgumentException('Do not enter patient-identifying information in Atlas source workspaces.');}return$value;}
private function url(mixed$value):string{$value=trim((string)$value);if($value===''){return'';}return filter_var($value,FILTER_VALIDATE_URL)?substr($value,0,500):throw new InvalidArgumentException('Source URL is invalid.');}
private function date(mixed$value):?string{$value=trim((string)$value);if($value===''){return null;}return preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)===1?$value:throw new InvalidArgumentException('Dates must use YYYY-MM-DD.');}
private function key(mixed$value,array$allowed,string$default):string{$value=sanitize_key((string)$value);return in_array($value,$allowed,true)?$value:$default;}
private function id(string$id):string{$id=strtolower(trim($id));if(preg_match('/^[a-f0-9-]{36}$/',$id)!==1){throw new InvalidArgumentException('Identifier is invalid.');}return$id;}
private function optionalId(mixed$id):string{$id=trim((string)$id);return$id===''?'':$this->id($id);}
private function checklistItems(string$text):array{$lines=preg_split('/\R+|(?<=[.;])\s+/',trim($text))?:[];$items=[];foreach($lines as$line){$line=trim($line," \t\n\r\0\x0B-•*");if($line!==''){$label=substr($line,0,220);$items[]=['hash'=>hash('sha256',$label),'label'=>$label,'status'=>'needed','notes'=>''];}}if($items===[]){$label=substr(trim($text),0,220);$items[]=['hash'=>hash('sha256',$label),'label'=>$label,'status'=>'needed','notes'=>''];}return$items;}
private function applyChecklistState(string$id,array$items,array$state):array{foreach($items as&$item){$saved=$state[$id.':'.(string)$item['hash']]??null;if(is_array($saved)){$item['status']=(string)($saved['status']??$item['status']);$item['notes']=(string)($saved['notes']??'');$item['updated_at']=(string)($saved['updated_at']??'');}}unset($item);return$items;}
private function reviewLanes(array$requirements):array{$lanes=['draft'=>0,'in_review'=>0,'published'=>0,'retired'=>0,'stale_or_expiring'=>0];foreach($requirements as$r){$status=(string)($r['review_status']??'draft');if(isset($lanes[$status])){$lanes[$status]++;}$expires=(string)($r['expires_at']??'');if($expires!==''&&$expires<=gmdate('Y-m-d',strtotime('+30 days'))){$lanes['stale_or_expiring']++;}}return$lanes;}
private function freshnessAlerts(array$requirements,array$documents):array{$alerts=[];$soon=gmdate('Y-m-d',strtotime('+30 days'));foreach($requirements as$r){$expires=(string)($r['expires_at']??'');if($expires!==''&&$expires<gmdate('Y-m-d')){$alerts[]=['type'=>'requirement_expired','label'=>(string)($r['payer']??'').' - '.(string)($r['topic']??''),'date'=>$expires];}elseif($expires!==''&&$expires<=$soon){$alerts[]=['type'=>'requirement_expiring','label'=>(string)($r['payer']??'').' - '.(string)($r['topic']??''),'date'=>$expires];}}foreach($documents as$d){if((string)($d['extraction_status']??'')==='stale'){$alerts[]=['type'=>'source_stale','label'=>(string)($d['publisher']??'').' - '.(string)($d['title']??''),'date'=>(string)($d['last_checked_at']??'')];}}return$alerts;}
}
