<?php
declare(strict_types=1);
namespace Atlas\Platform\Resources\Sources;
use Atlas\Platform\Core\Audit\AuditRecorder;
use InvalidArgumentException;
final class SourceWorkspaceService
{
public function __construct(private SourceWorkspaceRepository$repo,private AuditRecorder$audit){}
public function createDocument(?string$org,int$user,array$input):string{$this->user($user);$data=['title'=>$this->text($input,'title',255,true),'publisher'=>$this->text($input,'publisher',255,true),'source_url'=>$this->url($input['source_url']??''),'document_type'=>$this->key($input['document_type']??'policy',['policy','manual','form','guideline','organization_policy'],'policy'),'effective_date'=>$this->date($input['effective_date']??null),'checksum'=>$this->text($input,'checksum',128,false),'notes'=>$this->noPhi($this->text($input,'notes',2000,false))];$id=$this->repo->createDocument($org,$user,$data);$this->audit->record('source.document_created','resources',$user,$org,'source_document',$id,['publisher'=>$data['publisher'],'document_type'=>$data['document_type']]);return$id;}
public function updateDocumentStatus(string$id,?string$org,string$status,string$notes,int$user):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['queued','extracting','ready','stale','failed'],'');if($status===''){throw new InvalidArgumentException('Source status is invalid.');}$ok=$this->repo->updateDocumentStatus($id,$org,$status,$this->noPhi(substr(trim($notes),0,2000)));if($ok){$this->audit->record('source.document_status_updated','resources',$user,$org,'source_document',$id,['status'=>$status]);}return$ok;}
public function createSection(string$doc,array$input,int$user):string{$this->user($user);$doc=$this->id($doc);$data=['page_number'=>max(0,(int)($input['page_number']??0)),'section_label'=>$this->text($input,'section_label',191,false),'text_excerpt'=>$this->noPhi($this->text($input,'text_excerpt',5000,true)),'anchor'=>$this->text($input,'anchor',191,false)];$id=$this->repo->createSection($doc,$data);$this->audit->record('source.section_created','resources',$user,null,'source_section',$id,['source_document_id'=>$doc]);return$id;}
public function createCandidate(string$section,?string$org,array$input,int$user):string{$this->user($user);$section=$this->id($section);$data=['candidate_type'=>$this->key($input['candidate_type']??'requirement',['requirement','exception','definition','form','warning'],'requirement'),'statement'=>$this->noPhi($this->text($input,'statement',5000,true))];$id=$this->repo->createCandidate($section,$org,$data);$this->audit->record('extraction.candidate_created','resources',$user,$org,'extraction_candidate',$id,['candidate_type'=>$data['candidate_type']]);return$id;}
public function reviewCandidate(string$id,string$status,int$user,?string$org=null):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['approved','rejected','needs_changes'],'');if($status===''){throw new InvalidArgumentException('Candidate review status is invalid.');}$ok=$this->repo->reviewCandidate($id,$status,$user);if($ok){$this->audit->record('extraction.candidate_reviewed','resources',$user,$org,'extraction_candidate',$id,['status'=>$status]);}return$ok;}
public function createRequirement(?string$org,int$user,array$input):string{$this->user($user);$data=['payer'=>$this->text($input,'payer',191,true),'plan_name'=>$this->text($input,'plan_name',191,false),'topic'=>$this->text($input,'topic',191,true),'jurisdiction'=>$this->text($input,'jurisdiction',120,false),'requirement_type'=>$this->key($input['requirement_type']??'documentation',['documentation','eligibility','prior_authorization','frequency_limit','form','exception'],'documentation'),'requirement_text'=>$this->noPhi($this->text($input,'requirement_text',5000,true)),'source_candidate_id'=>$this->optionalId($input['source_candidate_id']??''),'effective_date'=>$this->date($input['effective_date']??null),'expires_at'=>$this->date($input['expires_at']??null)];$id=$this->repo->createRequirement($org,$user,$data);$this->audit->record('payer_requirement.created','resources',$user,$org,'payer_requirement',$id,['payer'=>$data['payer'],'topic'=>$data['topic']]);return$id;}
public function reviewRequirement(string$id,?string$org,string$status,int$user):bool{$this->user($user);$id=$this->id($id);$status=$this->key($status,['draft','in_review','published','retired'],'');if($status===''){throw new InvalidArgumentException('Requirement review status is invalid.');}$ok=$this->repo->reviewRequirement($id,$org,$status,$user);if($ok){$this->audit->record('payer_requirement.reviewed','resources',$user,$org,'payer_requirement',$id,['status'=>$status]);}return$ok;}
public function requirements(?string$org,array$criteria=[],int$limit=25):array{return$this->repo->requirements($org,$limit,['payer'=>$this->text($criteria,'payer',191,false),'topic'=>$this->text($criteria,'topic',191,false),'status'=>$this->key($criteria['status']??'',['draft','in_review','published','retired'],'')]);}
public function dashboard(?string$org):array{return['summary'=>$this->repo->summary($org),'documents'=>$this->repo->documents($org),'candidates'=>$this->repo->candidates($org),'requirements'=>$this->requirements($org,[],50)];}
private function user(int$user):void{if($user<=0){throw new InvalidArgumentException('A signed-in Atlas user is required.');}}
private function text(array$input,string$key,int$max,bool$required):string{$value=substr(trim((string)($input[$key]??'')),0,$max);if($required&&$value===''){throw new InvalidArgumentException("{$key} is required.");}return$value;}
private function noPhi(string$value):string{if(preg_match('/\b(?:MRN|DOB|SSN)\b|(?:\d{3}-\d{2}-\d{4})/i',$value)===1){throw new InvalidArgumentException('Do not enter patient-identifying information in Atlas source workspaces.');}return$value;}
private function url(mixed$value):string{$value=trim((string)$value);if($value===''){return'';}return filter_var($value,FILTER_VALIDATE_URL)?substr($value,0,500):throw new InvalidArgumentException('Source URL is invalid.');}
private function date(mixed$value):?string{$value=trim((string)$value);if($value===''){return null;}return preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)===1?$value:throw new InvalidArgumentException('Dates must use YYYY-MM-DD.');}
private function key(mixed$value,array$allowed,string$default):string{$value=sanitize_key((string)$value);return in_array($value,$allowed,true)?$value:$default;}
private function id(string$id):string{$id=strtolower(trim($id));if(preg_match('/^[a-f0-9-]{36}$/',$id)!==1){throw new InvalidArgumentException('Identifier is invalid.');}return$id;}
private function optionalId(mixed$id):string{$id=trim((string)$id);return$id===''?'':$this->id($id);}
}
