<?php
/** @var array{resource: Atlas\Platform\Resources\Domain\PublishedResource, body_html: string, branding: ?Atlas\Platform\PatientResources\Domain\BrandingProfile, logo_url: ?string} $view */
declare(strict_types=1); if(!defined('ABSPATH')){exit;} $item=$view['resource'];
?>
<div class="atlas-preview-wrap atlas-resource-view"><div class="atlas-shell"><main class="atlas-resource-main">
<?php if($item->resource->type==='patient_education'&&$view['branding']!==null):?><div class="atlas-print-brand"><?php if(is_string($view['logo_url'])):?><img src="<?php echo esc_url($view['logo_url']);?>" alt=""><?php endif;?><div><strong><?php echo esc_html($view['branding']->displayName);?></strong><span><?php echo nl2br(esc_html($view['branding']->contactBlock));?></span></div></div><?php endif;?>
<nav class="atlas-resource-breadcrumb" aria-label="<?php echo esc_attr__('Breadcrumb','atlas-platform');?>"><a href="<?php echo esc_url(admin_url('admin.php?page=atlas'));?>"><?php echo esc_html__('Atlas home','atlas-platform');?></a><span aria-hidden="true">/</span><span><?php echo esc_html($item->version->title);?></span></nav>
<header class="atlas-resource-header"><div><p class="atlas-eyebrow"><?php echo esc_html(ucwords(str_replace('_',' ',$item->resource->type)));?></p><h1><?php echo esc_html($item->version->title);?></h1><p class="atlas-resource-summary"><?php echo esc_html($item->version->summary);?></p></div><button class="button button-secondary atlas-print-button" type="button" onclick="window.print()"><?php echo esc_html__('Print resource','atlas-platform');?></button></header>
<div class="atlas-trust-strip"><span><strong><?php echo esc_html__('Scope','atlas-platform');?>:</strong> <?php echo esc_html(ucfirst($item->resource->scope));?></span><span><strong><?php echo esc_html__('Review status','atlas-platform');?>:</strong> <?php echo esc_html(ucwords(str_replace('_',' ',$item->version->reviewStatus)));?></span><span><strong><?php echo esc_html__('Version','atlas-platform');?>:</strong> <?php echo esc_html((string)$item->version->version);?></span><?php if($item->version->effectiveDate!==null):?><span><strong><?php echo esc_html__('Effective','atlas-platform');?>:</strong> <?php echo esc_html($item->version->effectiveDate);?></span><?php endif;?></div>
<div class="atlas-resource-columns"><article class="atlas-resource-content"><?php echo wp_kses_post($view['body_html']);?></article><aside class="atlas-resource-sources"><h2><?php echo esc_html__('Sources and provenance','atlas-platform');?></h2><?php if($item->citations===[]):?><p><?php echo esc_html__('No citations are attached. This resource should not be treated as verified guidance.','atlas-platform');?></p><?php else:?><ol><?php foreach($item->citations as $citation):?><li><strong><?php echo esc_html($citation->publisher);?></strong><span><?php echo esc_html($citation->sourceTitle);?></span><?php if($citation->section!==null):?><small><?php echo esc_html(sprintf(__('Section: %s','atlas-platform'),$citation->section));?></small><?php endif;?><?php if($citation->sourceUrl!==null):?><a href="<?php echo esc_url($citation->sourceUrl);?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__('Open source','atlas-platform');?></a><?php endif;?></li><?php endforeach;?></ol><?php endif;?></aside></div>
<footer class="atlas-resource-footer"><strong><?php echo esc_html__('Change summary','atlas-platform');?>:</strong> <?php echo esc_html($item->version->changeSummary);?><?php if($item->version->reviewDueDate!==null):?><span><?php echo esc_html(sprintf(__('Review due: %s','atlas-platform'),$item->version->reviewDueDate));?></span><?php endif;?></footer>
<?php if($item->resource->type==='patient_education'&&$view['branding']!==null&&$view['branding']->footer!==''):?><p class="atlas-branded-footer"><?php echo esc_html($view['branding']->footer);?></p><?php endif;?>
</main></div></div>
