<?php
declare(strict_types=1);
namespace Atlas\Platform\Resources\Rest;
use Atlas\Platform\Core\Logging\Logger;
use Atlas\Platform\Organizations\Services\CurrentOrganizationResolver;
use Atlas\Platform\Resources\Sources\SourceWorkspaceService;
use InvalidArgumentException;
use Throwable;
use WP_Error;
use WP_REST_Request;
use WP_REST_Response;
final class SourceWorkspaceController
{
public function __construct(private SourceWorkspaceService$service,private CurrentOrganizationResolver$orgs,private Logger$logger){}
public function readPermission():bool{return is_user_logged_in()&&current_user_can('atlas_access');}
public function sourceWritePermission():bool{return is_user_logged_in()&&current_user_can('atlas_upload_sources');}
public function reviewPermission():bool{return is_user_logged_in()&&current_user_can('atlas_review_extractions');}
public function requirements(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response(['requirements'=>$this->service->requirements($org?->id,['payer'=>$r->get_param('payer'),'topic'=>$r->get_param('topic'),'dme_category_slug'=>$r->get_param('dme_category_slug'),'prior_authorization_status'=>$r->get_param('prior_authorization_status'),'status'=>$r->get_param('status')],max(1,(int)($r->get_param('per_page')?:25)))],200);}catch(Throwable$e){return$this->error($e,'atlas_requirements_unavailable',500);}}
public function insuranceProfiles(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response(['profiles'=>$this->service->insuranceProfiles($org?->id,['payer'=>$r->get_param('payer'),'jurisdiction'=>$r->get_param('jurisdiction'),'status'=>$r->get_param('status')],max(1,(int)($r->get_param('per_page')?:25)))],200);}catch(Throwable$e){return$this->error($e,'atlas_insurance_profiles_unavailable',500);}}
public function createInsuranceProfile(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createInsuranceProfile($org?->id,get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id],201);}catch(Throwable$e){return$this->error($e,'atlas_insurance_profile_failed');}}
public function dmeCategories(WP_REST_Request$r):WP_REST_Response|WP_Error{try{return new WP_REST_Response(['categories'=>$this->service->dmeCategories(['status'=>$r->get_param('status')],max(1,(int)($r->get_param('per_page')?:100)))],200);}catch(Throwable$e){return$this->error($e,'atlas_dme_categories_unavailable',500);}}
public function createDmeCategory(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$id=$this->service->createDmeCategory(get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id],201);}catch(Throwable$e){return$this->error($e,'atlas_dme_category_failed');}}
public function dmeMatches(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->dmeRequirementMatches($org?->id,['payer'=>$r->get_param('payer'),'plan_name'=>$r->get_param('plan_name'),'dme_category'=>$r->get_param('dme_category'),'jurisdiction'=>$r->get_param('jurisdiction'),'prior_authorization_status'=>$r->get_param('prior_authorization_status')],max(1,(int)($r->get_param('per_page')?:50))),200);}catch(Throwable$e){return$this->error($e,'atlas_dme_matches_unavailable',500);}}
public function checklist(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response(['checklist'=>$this->service->documentationChecklist($org?->id,['payer'=>$r->get_param('payer'),'topic'=>$r->get_param('topic'),'status'=>$r->get_param('status')?:'published'],max(1,(int)($r->get_param('per_page')?:25)))],200);}catch(Throwable$e){return$this->error($e,'atlas_documentation_checklist_unavailable',500);}}
public function checklistExport(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->checklistExport($org?->id,['payer'=>$r->get_param('payer'),'topic'=>$r->get_param('topic')]),200);}catch(Throwable$e){return$this->error($e,'atlas_documentation_checklist_export_unavailable',500);}}
public function coverageSummaryExport(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->coverageSummaryExport($org?->id,['payer'=>$r->get_param('payer'),'topic'=>$r->get_param('topic'),'dme_category_slug'=>$r->get_param('dme_category_slug'),'jurisdiction'=>$r->get_param('jurisdiction'),'prior_authorization_status'=>$r->get_param('prior_authorization_status')]),200);}catch(Throwable$e){return$this->error($e,'atlas_coverage_summary_export_unavailable',500);}}
public function evidence(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$evidence=$this->service->requirementEvidence((string)$r->get_param('id'),$org?->id);return$evidence===null?new WP_Error('atlas_requirement_not_found',__('The requirement was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($evidence,200);}catch(Throwable$e){return$this->error($e,'atlas_requirement_evidence_unavailable',500);}}
public function coverageSummary(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$summary=$this->service->coverageSummary((string)$r->get_param('id'),$org?->id);return$summary===null?new WP_Error('atlas_requirement_not_found',__('The requirement was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($summary,200);}catch(Throwable$e){return$this->error($e,'atlas_coverage_summary_unavailable',500);}}
public function requirementWorkspace(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$workspace=$this->service->requirementDetailWorkspace((string)$r->get_param('id'),$org?->id);return$workspace===null?new WP_Error('atlas_requirement_not_found',__('The requirement workspace was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($workspace,200);}catch(Throwable$e){return$this->error($e,'atlas_requirement_workspace_unavailable',500);}}
public function updateChecklist(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$body=(array)$r->get_json_params();$ok=$this->service->updateChecklistState((string)$r->get_param('id'),$org?->id,(string)($body['hash']??''),(string)($body['label']??''),(string)($body['status']??''),(string)($body['notes']??''),get_current_user_id());return$ok?new WP_REST_Response(['status'=>'ok'],200):new WP_Error('atlas_requirement_not_found',__('The requirement was not found or could not be updated.','atlas-platform'),['status'=>404]);}catch(Throwable$e){return$this->error($e,'atlas_checklist_update_failed');}}
public function compareSourceVersion(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$comparison=$this->service->sourceVersionComparison((string)$r->get_param('id'),$org?->id);return$comparison===null?new WP_Error('atlas_source_document_not_found',__('The source document was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($comparison,200);}catch(Throwable$e){return$this->error($e,'atlas_source_comparison_unavailable',500);}}
public function openSourceImpactReview(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->openSourceImpactReview((string)$r->get_param('id'),$org?->id,get_current_user_id()),200);}catch(Throwable$e){return$this->error($e,'atlas_source_impact_review_failed');}}
public function clearSourceImpactReview(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$body=(array)$r->get_json_params();$ok=$this->service->clearSourceImpactReview((string)$r->get_param('id'),$org?->id,get_current_user_id(),(string)($body['review_note']??$body['note']??''));return$ok?new WP_REST_Response(['status'=>'ok'],200):new WP_Error('atlas_requirement_not_found',__('The requirement was not found or could not be updated.','atlas-platform'),['status'=>404]);}catch(Throwable$e){return$this->error($e,'atlas_source_impact_review_clear_failed');}}
public function createRequirementChangeProposal(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createRequirementChangeProposal((string)$r->get_param('id'),$org?->id,get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id,'status'=>'draft'],201);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposal_failed');}}
public function applyRequirementChangeProposal(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$ok=$this->service->applyRequirementChangeProposal((string)$r->get_param('proposal_id'),(string)$r->get_param('id'),$org?->id,get_current_user_id());return$ok?new WP_REST_Response(['status'=>'applied'],200):new WP_Error('atlas_requirement_change_proposal_not_applied',__('The change proposal could not be applied.','atlas-platform'),['status'=>404]);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposal_apply_failed');}}
public function rejectRequirementChangeProposal(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$body=(array)$r->get_json_params();$ok=$this->service->rejectRequirementChangeProposal((string)$r->get_param('proposal_id'),(string)$r->get_param('id'),$org?->id,get_current_user_id(),(string)($body['rejection_note']??$body['note']??''));return$ok?new WP_REST_Response(['status'=>'rejected'],200):new WP_Error('atlas_requirement_change_proposal_not_rejected',__('The change proposal could not be rejected.','atlas-platform'),['status'=>404]);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposal_reject_failed');}}
public function requirementChangeProposals(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response(['proposals'=>$this->service->requirementChangeProposals((string)$r->get_param('id'),$org?->id,max(1,(int)($r->get_param('per_page')?:25)))],200);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposals_unavailable',500);}}
public function requirementChangeProposalWorkspace(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$workspace=$this->service->requirementChangeProposalWorkspace((string)$r->get_param('proposal_id'),(string)$r->get_param('id'),$org?->id);return$workspace===null?new WP_Error('atlas_requirement_change_proposal_not_found',__('The change proposal workspace was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($workspace,200);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposal_workspace_unavailable',500);}}
public function changeProposalQueue(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->changeProposalQueue($org?->id,['proposal_status'=>$r->get_param('proposal_status')],max(1,(int)($r->get_param('per_page')?:50))),200);}catch(Throwable$e){return$this->error($e,'atlas_requirement_change_proposal_queue_unavailable',500);}}
public function sourceImpactQueue(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());return new WP_REST_Response($this->service->sourceImpactReviewQueue($org?->id,['payer'=>$r->get_param('payer'),'topic'=>$r->get_param('topic')],max(1,(int)($r->get_param('per_page')?:50))),200);}catch(Throwable$e){return$this->error($e,'atlas_source_impact_queue_unavailable',500);}}
public function dashboard(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$comparison=(string)($r->get_param('comparison_source_id')??'');return new WP_REST_Response($this->service->dashboard($org?->id,$comparison===''?null:$comparison),200);}catch(Throwable$e){return$this->error($e,'atlas_source_dashboard_unavailable',500);}}
public function createDocument(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createDocument($org?->id,get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id],201);}catch(Throwable$e){return$this->error($e,'atlas_source_document_failed');}}
public function sourceIntakeWorkspace(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$workspace=$this->service->sourceIntakeWorkspace((string)$r->get_param('id'),$org?->id);return$workspace===null?new WP_Error('atlas_source_document_not_found',__('The source document was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($workspace,200);}catch(Throwable$e){return$this->error($e,'atlas_source_intake_workspace_unavailable',500);}}
public function createCandidateFromPage(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createCandidateFromPage((string)$r->get_param('id'),$org?->id,(array)$r->get_json_params(),get_current_user_id());return new WP_REST_Response(['id'=>$id,'status'=>'pending'],201);}catch(Throwable$e){return$this->error($e,'atlas_candidate_from_page_failed');}}
public function candidateWorkspace(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$workspace=$this->service->candidateWorkspace((string)$r->get_param('id'),$org?->id);return$workspace===null?new WP_Error('atlas_candidate_not_found',__('The extraction candidate was not found or is not accessible.','atlas-platform'),['status'=>404]):new WP_REST_Response($workspace,200);}catch(Throwable$e){return$this->error($e,'atlas_candidate_workspace_unavailable',500);}}
public function createRequirementFromCandidate(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createRequirementDraftFromCandidate((string)$r->get_param('id'),$org?->id,get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id,'status'=>'draft'],201);}catch(Throwable$e){return$this->error($e,'atlas_requirement_from_candidate_failed');}}
public function createRequirement(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$id=$this->service->createRequirement($org?->id,get_current_user_id(),(array)$r->get_json_params());return new WP_REST_Response(['id'=>$id],201);}catch(Throwable$e){return$this->error($e,'atlas_requirement_failed');}}
public function reviewRequirement(WP_REST_Request$r):WP_REST_Response|WP_Error{try{$org=$this->orgs->resolveForUser(get_current_user_id());$ok=$this->service->reviewRequirement((string)$r->get_param('id'),$org?->id,(string)$r->get_param('status'),get_current_user_id());return$ok?new WP_REST_Response(['status'=>'ok'],200):new WP_Error('atlas_requirement_not_found',__('The requirement was not found or could not be updated.','atlas-platform'),['status'=>404]);}catch(Throwable$e){return$this->error($e,'atlas_requirement_review_failed');}}
private function error(Throwable$e,string$code,int$fallback=400):WP_Error{$status=$e instanceof InvalidArgumentException?400:$fallback;if(!$e instanceof InvalidArgumentException){$this->logger->log('error',$code,'Source workspace request failed.',[],'resources',$e);}return new WP_Error($code,$e instanceof InvalidArgumentException?$e->getMessage():__('The source workspace request failed safely.','atlas-platform'),['status'=>$status]);}
}
