<?php
declare(strict_types=1);
namespace Atlas\Platform\Resources\Editorial\Admin;
use Atlas\Platform\Core\Logging\Logger;use Atlas\Platform\Organizations\Services\CurrentOrganizationResolver;use Atlas\Platform\Resources\Editorial\EditorialQueueRepository;use Atlas\Platform\Resources\Editorial\EditorialService;use Atlas\Platform\Resources\Editorial\ResourceGovernanceRepository;use Throwable;
final class EditorialQueueAdminPage
{
private string$hook='';
public function __construct(private EditorialQueueRepository$queue,private EditorialService$editorial,private ResourceGovernanceRepository$governance,private CurrentOrganizationResolver$organizations,private Logger$logger){}
public function register():void{$this->hook=(string)add_submenu_page('atlas',__('Review Queue','atlas-platform'),__('Review Queue','atlas-platform'),'atlas_review_resources','atlas-resource-review',[$this,'render']);add_submenu_page(null,__('Resource history','atlas-platform'),__('Resource history','atlas-platform'),'atlas_edit_resources','atlas-resource-history',[$this,'renderHistory']);}
public function enqueue(string$hook):void{if($hook===$this->hook||str_contains($hook,'atlas-resource-history')){wp_enqueue_style('atlas-preview',ATLAS_PLATFORM_URL.'assets/css/atlas-preview.css',[],ATLAS_PLATFORM_VERSION);}}
public function transition():void{$this->authorize('atlas_editorial_transition');$to=sanitize_key(wp_unslash((string)($_POST['to']??'')));if($to==='published'&&!current_user_can('atlas_publish_resources')){wp_die(esc_html__('You are not allowed to publish resources.','atlas-platform'),'', ['response'=>403]);}$organization=$this->organizations->resolveForUser(get_current_user_id());try{$result=$this->editorial->transition(sanitize_text_field(wp_unslash((string)($_POST['version_id']??''))),$to,get_current_user_id(),$organization?->id,current_user_can('atlas_manage_atlas'),sanitize_text_field(wp_unslash((string)($_POST['idempotency_key']??''))));$notice=$result===null?'not-found':'updated';}catch(Throwable$failure){$this->logger->log('error','resources.admin_transition_failed','Editorial transition failed.',[],'resources',$failure);$notice='failed';}$this->redirect($notice);}
public function revise():void{$this->authorize('atlas_create_revision','atlas_edit_resources');$org=$this->organizations->resolveForUser(get_current_user_id());$id=$this->governance->revise(sanitize_text_field(wp_unslash((string)($_POST['version_id']??''))),$org?->id,current_user_can('atlas_manage_atlas'),get_current_user_id());$this->redirect($id?'revision-created':'failed');}
public function archive():void{$this->authorize('atlas_archive_resource','atlas_edit_resources');$org=$this->organizations->resolveForUser(get_current_user_id());$ok=$this->governance->archive(sanitize_text_field(wp_unslash((string)($_POST['resource_id']??''))),$org?->id,current_user_can('atlas_manage_atlas'));$this->redirect($ok?'archived':'failed');}
public function assign():void{$this->authorize('atlas_assign_reviewer');$org=$this->organizations->resolveForUser(get_current_user_id());$due=sanitize_text_field(wp_unslash((string)($_POST['due_at']??'')));$ok=$this->governance->assign(sanitize_text_field(wp_unslash((string)($_POST['version_id']??''))),absint($_POST['reviewer_user_id']??0),$due===''?null:$due.' 23:59:59',$org?->id,current_user_can('atlas_manage_atlas'));$this->redirect($ok?'assigned':'failed');}
public function addNote():void{$this->authorize('atlas_add_review_note');$org=$this->organizations->resolveForUser(get_current_user_id());$text=sanitize_textarea_field(wp_unslash((string)($_POST['note_text']??'')));$type=sanitize_key(wp_unslash((string)($_POST['note_type']??'comment')));$ok=$text!==''&&$this->governance->addNote(sanitize_text_field(wp_unslash((string)($_POST['version_id']??''))),get_current_user_id(),$type,$text,$org?->id,current_user_can('atlas_manage_atlas'));$this->redirect($ok?'note-added':'failed');}
public function render():void{if(!current_user_can('atlas_review_resources')&&!current_user_can('atlas_publish_resources')){wp_die(esc_html__('You are not allowed to review resources.','atlas-platform'),'', ['response'=>403]);}$organization=$this->organizations->resolveForUser(get_current_user_id());$items=$this->queue->findForContext($organization?->id,current_user_can('atlas_manage_atlas'));$notice=sanitize_key(wp_unslash((string)($_GET['atlas_notice']??'')));require ATLAS_PLATFORM_DIR.'templates/resources/review-queue.php';}
public function renderHistory():void{if(!current_user_can('atlas_edit_resources')){wp_die(esc_html__('You are not allowed to view resource history.','atlas-platform'),'', ['response'=>403]);}$org=$this->organizations->resolveForUser(get_current_user_id());$resourceId=sanitize_text_field(wp_unslash((string)($_GET['resource_id']??'')));$versionId=sanitize_text_field(wp_unslash((string)($_GET['version_id']??'')));$platform=current_user_can('atlas_manage_atlas');$history=$this->governance->history($resourceId,$org?->id,$platform);$workspace=$versionId===''?['assignment'=>null,'notes'=>[]]:$this->governance->workspace($versionId,$org?->id,$platform);$reviewers=get_users(['fields'=>['ID','display_name','user_email']]);require ATLAS_PLATFORM_DIR.'templates/resources/history.php';}
private function authorize(string$nonce,string$cap='atlas_review_resources'):void{if(!current_user_can($cap)){wp_die(esc_html__('You are not allowed to perform this action.','atlas-platform'),'', ['response'=>403]);}check_admin_referer($nonce);}
private function redirect(string$notice):never{wp_safe_redirect(add_query_arg(['page'=>'atlas-resource-review','atlas_notice'=>$notice],admin_url('admin.php')));exit;}
}
