<?php
declare(strict_types=1);

final class AdvancedOperationsRepository
{
    public function __construct(private PDO $db) {}

    public function undoShiftChange(int $oid,int $uid,int $historyId): void
    {
        $q=$this->db->prepare('SELECT sh.* FROM shift_history sh JOIN shifts s ON s.id=sh.shift_id WHERE sh.id=? AND sh.organization_id=? AND s.organization_id=?');$q->execute([$historyId,$oid,$oid]);$event=$q->fetch();if(!$event||!$event['before_json'])throw new InvalidArgumentException('That schedule change cannot be restored.');$before=json_decode($event['before_json'],true);if(!$before)throw new InvalidArgumentException('The prior shift state is unavailable.');$q=$this->db->prepare('SELECT * FROM shifts WHERE id=? AND organization_id=?');$q->execute([$event['shift_id'],$oid]);$current=$q->fetch();$this->db->beginTransaction();try{$this->db->prepare('UPDATE shifts SET shift_date=?,starts_at=?,ends_at=?,assigned_membership_id=?,status=? WHERE id=? AND organization_id=?')->execute([$before['shift_date'],$before['starts_at'],$before['ends_at'],$before['assigned_membership_id']?:null,$before['status'],$event['shift_id'],$oid]);$this->db->prepare('INSERT INTO shift_history (organization_id,shift_id,action,before_json,after_json,reason,changed_by) VALUES (?,? ,"undo",?,?,?,?)')->execute([$oid,$event['shift_id'],json_encode($current),json_encode($before),'Restored change #'.$historyId,$uid]);$this->audit($oid,$uid,'shift.undo','shift',(int)$event['shift_id']);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function bulkEditShifts(int $oid,int $uid,array $in): int
    {
        $ids=array_values(array_unique(array_filter(array_map('intval',(array)($in['shift_ids']??[])))));if(!$ids)throw new InvalidArgumentException('Select at least one shift.');$status=$in['status']??'';if($status!==''&&!in_array($status,['open','assigned','filled','cancelled'],true))throw new InvalidArgumentException('Invalid shift status.');$count=0;$this->db->beginTransaction();try{foreach($ids as $id){$q=$this->db->prepare('SELECT * FROM shifts WHERE id=? AND organization_id=?');$q->execute([$id,$oid]);$before=$q->fetch();if(!$before)continue;$newStatus=$status?:$before['status'];$notes=trim((string)($in['notes']??''))?:$before['notes'];$this->db->prepare('UPDATE shifts SET status=?,notes=? WHERE id=? AND organization_id=?')->execute([$newStatus,$notes,$id,$oid]);$after=$before;$after['status']=$newStatus;$after['notes']=$notes;$this->db->prepare('INSERT INTO shift_history (organization_id,shift_id,action,before_json,after_json,reason,changed_by) VALUES (?,? ,"bulk_edit",?,?,?,?)')->execute([$oid,$id,json_encode($before),json_encode($after),'Bulk schedule edit',$uid]);$count++;}$this->audit($oid,$uid,'shift.bulk_edit','shift',0,['count'=>$count]);$this->db->commit();return $count;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function saveTimeOffPolicy(int $oid,array $in): void {$name=trim((string)($in['name']??''));if($name==='')throw new InvalidArgumentException('Policy name is required.');$levels=max(1,min(3,(int)($in['approval_levels']??1)));$this->db->prepare('INSERT INTO time_off_policies (organization_id,request_type_id,name,annual_hours,minimum_notice_days,approval_levels) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE annual_hours=VALUES(annual_hours),minimum_notice_days=VALUES(minimum_notice_days),approval_levels=VALUES(approval_levels),active=1')->execute([$oid,!empty($in['request_type_id'])?(int)$in['request_type_id']:null,$name,max(0,(float)($in['annual_hours']??0)),max(0,(int)($in['minimum_notice_days']??0)),$levels]);}
    public function saveTimeOffBalance(int $oid,array $in): void {$member=(int)($in['membership_id']??0);$policy=(int)($in['policy_id']??0);$this->ownedMember($oid,$member);$q=$this->db->prepare('SELECT COUNT(*) FROM time_off_policies WHERE id=? AND organization_id=?');$q->execute([$policy,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Policy unavailable.');$this->db->prepare('INSERT INTO time_off_balances (organization_id,membership_id,policy_id,balance_hours) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE balance_hours=VALUES(balance_hours)')->execute([$oid,$member,$policy,(float)($in['balance_hours']??0)]);}
    public function addBlackout(int $oid,int $uid,array $in): void {$start=(string)($in['starts_on']??'');$end=(string)($in['ends_on']??'');$name=trim((string)($in['name']??''));if(!$start||!$end||$end<$start||$name==='')throw new InvalidArgumentException('Enter a valid blackout name and date range.');$this->db->prepare('INSERT INTO request_blackouts (organization_id,starts_on,ends_on,name,reason,created_by) VALUES (?,?,?,?,?,?)')->execute([$oid,$start,$end,$name,trim((string)($in['reason']??''))?:null,$uid]);}
    public function requestControls(int $oid): array {$q=$this->db->prepare('SELECT * FROM time_off_policies WHERE organization_id=? AND active=1 ORDER BY name');$q->execute([$oid]);$policies=$q->fetchAll();$q=$this->db->prepare('SELECT b.*,u.name staff_name,p.name policy_name FROM time_off_balances b JOIN memberships m ON m.id=b.membership_id JOIN users u ON u.id=m.user_id JOIN time_off_policies p ON p.id=b.policy_id WHERE b.organization_id=? ORDER BY u.name,p.name');$q->execute([$oid]);$balances=$q->fetchAll();$q=$this->db->prepare('SELECT * FROM request_blackouts WHERE organization_id=? ORDER BY starts_on DESC');$q->execute([$oid]);return compact('policies','balances')+['blackouts'=>$q->fetchAll()];}

    public function createCalloutWave(int $oid,int $uid,array $in): void {$callout=(int)($in['callout_id']??0);$q=$this->db->prepare('SELECT COUNT(*) FROM callouts WHERE id=? AND organization_id=? AND status="replacement_open"');$q->execute([$callout,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Open callout unavailable.');$minutes=max(5,min(1440,(int)($in['response_minutes']??30)));$q=$this->db->prepare('SELECT COALESCE(MAX(wave_number),0)+1 FROM callout_escalations WHERE callout_id=?');$q->execute([$callout]);$wave=(int)$q->fetchColumn();$this->db->prepare('INSERT INTO callout_escalations (organization_id,callout_id,wave_number,response_due_at,audience,created_by) VALUES (?,?,?,DATE_ADD(NOW(),INTERVAL ? MINUTE),?,?)')->execute([$oid,$callout,$wave,$minutes,trim((string)($in['audience']??'eligible_staff'))?:'eligible_staff',$uid]);}
    public function recordAttendance(int $oid,int $uid,array $in): void {$member=(int)($in['membership_id']??0);$this->ownedMember($oid,$member);$type=(string)($in['event_type']??'');if(!in_array($type,['callout','late_arrival','early_departure','no_show'],true))throw new InvalidArgumentException('Choose a valid attendance event.');$this->db->prepare('INSERT INTO attendance_events (organization_id,membership_id,shift_id,event_type,occurred_at,minutes_affected,notes,recorded_by) VALUES (?,?,?,?,?,?,?,?)')->execute([$oid,$member,!empty($in['shift_id'])?(int)$in['shift_id']:null,$type,$in['occurred_at']??date('Y-m-d H:i:s'),max(0,(int)($in['minutes_affected']??0)),trim((string)($in['notes']??''))?:null,$uid]);}
    public function attendance(int $oid): array {$q=$this->db->prepare('SELECT ae.*,u.name staff_name FROM attendance_events ae JOIN memberships m ON m.id=ae.membership_id JOIN users u ON u.id=m.user_id WHERE ae.organization_id=? ORDER BY occurred_at DESC LIMIT 100');$q->execute([$oid]);$events=$q->fetchAll();$q=$this->db->prepare('SELECT event_type,COUNT(*) event_count,SUM(minutes_affected) minutes_affected FROM attendance_events WHERE organization_id=? AND occurred_at>=DATE_SUB(NOW(),INTERVAL 90 DAY) GROUP BY event_type');$q->execute([$oid]);$analytics=$q->fetchAll();$q=$this->db->prepare('SELECT ce.*,c.membership_id,u.name staff_name FROM callout_escalations ce JOIN callouts c ON c.id=ce.callout_id JOIN memberships m ON m.id=c.membership_id JOIN users u ON u.id=m.user_id WHERE ce.organization_id=? ORDER BY ce.created_at DESC');$q->execute([$oid]);return compact('events','analytics')+['waves'=>$q->fetchAll()];}

    public function addForecast(int $oid,int $uid,array $in): void {$location=(int)($in['location_id']??0);$department=(int)($in['department_id']??0);$this->ownedResource('locations',$oid,$location);$this->ownedResource('departments',$oid,$department);$start=(string)($in['starts_at']??'');$end=(string)($in['ends_at']??'');if(!$in['forecast_date']||!$start||!$end||$end<=$start)throw new InvalidArgumentException('Enter a valid forecast interval.');$this->db->prepare('INSERT INTO coverage_demand_forecasts (organization_id,location_id,department_id,forecast_date,starts_at,ends_at,required_count,required_skill_mix,float_pool_count,break_coverage_count,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute([$oid,$location,$department,$in['forecast_date'],$start,$end,max(1,(int)($in['required_count']??1)),trim((string)($in['required_skill_mix']??''))?:null,max(0,(int)($in['float_pool_count']??0)),max(0,(int)($in['break_coverage_count']??0)),$uid]);}
    public function coverageForecasts(int $oid): array {$q=$this->db->prepare('SELECT f.*,l.name location_name,d.name department_name,(SELECT COUNT(*) FROM shifts s WHERE s.organization_id=f.organization_id AND s.location_id=f.location_id AND s.department_id=f.department_id AND s.shift_date=f.forecast_date AND s.status IN ("assigned","filled") AND s.starts_at<f.ends_at AND s.ends_at>f.starts_at) assigned_count FROM coverage_demand_forecasts f JOIN locations l ON l.id=f.location_id JOIN departments d ON d.id=f.department_id WHERE f.organization_id=? ORDER BY f.forecast_date,f.starts_at');$q->execute([$oid]);return $q->fetchAll();}

    public function createCommandItem(int $oid,array $in): void {$title=trim((string)($in['title']??''));if($title==='')throw new InvalidArgumentException('Queue item title is required.');$owner=!empty($in['owner_membership_id'])?(int)$in['owner_membership_id']:null;if($owner)$this->ownedMember($oid,$owner);$this->db->prepare('INSERT INTO command_center_items (organization_id,item_type,title,urgency_score,owner_membership_id,due_at) VALUES (?,?,?,?,?,?)')->execute([$oid,trim((string)($in['item_type']??'operational'))?:'operational',$title,max(0,min(100,(int)($in['urgency_score']??50))),$owner,!empty($in['due_at'])?$in['due_at']:null]);}
    public function updateCommandItem(int $oid,int $uid,array $in): void {$id=(int)($in['item_id']??0);$mode=(string)($in['mode']??'');if($mode==='resolve')$this->db->prepare('UPDATE command_center_items SET status="resolved",resolution_notes=?,resolved_by=?,resolved_at=NOW() WHERE id=? AND organization_id=?')->execute([trim((string)($in['notes']??''))?:null,$uid,$id,$oid]);elseif($mode==='snooze')$this->db->prepare('UPDATE command_center_items SET snoozed_until=DATE_ADD(NOW(),INTERVAL ? HOUR) WHERE id=? AND organization_id=?')->execute([max(1,min(168,(int)($in['hours']??24))),$id,$oid]);else throw new InvalidArgumentException('Choose a valid queue action.');}
    public function commandItems(int $oid): array {$q=$this->db->prepare('SELECT c.*,u.name owner_name FROM command_center_items c LEFT JOIN memberships m ON m.id=c.owner_membership_id LEFT JOIN users u ON u.id=m.user_id WHERE c.organization_id=? AND c.status="open" AND (c.snoozed_until IS NULL OR c.snoozed_until<=NOW()) ORDER BY urgency_score DESC,due_at IS NULL,due_at');$q->execute([$oid]);return $q->fetchAll();}

    public function addDelegation(int $oid,int $uid,array $in): void {$member=(int)($in['membership_id']??0);$this->ownedMember($oid,$member);$cap=(string)($in['capability']??'');if(!in_array($cap,['schedule','approve','payroll','credentials'],true))throw new InvalidArgumentException('Choose a valid capability.');$start=(string)($in['starts_at']??'');$end=(string)($in['expires_at']??'');if(!$start||!$end||$end<=$start)throw new InvalidArgumentException('Delegation expiration must follow its start.');$this->db->prepare('INSERT INTO access_delegations (organization_id,membership_id,capability,starts_at,expires_at,granted_by) VALUES (?,?,?,?,?,?)')->execute([$oid,$member,$cap,$start,$end,$uid]);$this->audit($oid,$uid,'access.delegated','membership',$member,['capability'=>$cap,'expires_at'=>$end]);}
    public function delegations(int $oid): array {$q=$this->db->prepare('SELECT ad.*,u.name staff_name FROM access_delegations ad JOIN memberships m ON m.id=ad.membership_id JOIN users u ON u.id=m.user_id WHERE ad.organization_id=? ORDER BY ad.expires_at DESC');$q->execute([$oid]);return $q->fetchAll();}

    private function ownedMember(int $oid,int $id): void {$q=$this->db->prepare('SELECT COUNT(*) FROM memberships WHERE id=? AND organization_id=?');$q->execute([$id,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Employee unavailable.');}
    private function ownedResource(string $table,int $oid,int $id): void {if(!in_array($table,['locations','departments'],true))throw new LogicException('Invalid resource.');$q=$this->db->prepare("SELECT COUNT(*) FROM {$table} WHERE id=? AND organization_id=?");$q->execute([$id,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Organization resource unavailable.');}
    private function audit(int $oid,int $uid,string $action,string $type,int $id,array $meta=[]): void {$this->db->prepare('INSERT INTO audit_logs (organization_id,user_id,action,entity_type,entity_id,metadata_json,ip_address) VALUES (?,?,?,?,?,?,?)')->execute([$oid,$uid,$action,$type,$id,json_encode($meta),$_SERVER['REMOTE_ADDR']??null]);}
}
