<?php

declare(strict_types=1);

final class AtlasViews
{
    public static function library(string $eyebrow,string $title,string $intro,array $items,string $base,string $metaKey,string $countLabel): void
    {
        ob_start();?><section class="page-head"><div><p class="eyebrow"><?=App::e($eyebrow)?></p><h1><?=App::e($title)?></h1><p><?=App::e($intro)?></p></div><div class="count-card"><strong><?=count($items)?></strong><span><?=App::e($countLabel)?></span></div></section><div class="filterbar"><input placeholder="Search <?=App::e(strtolower($title))?>…"><select><option>All topics</option><option>DME</option><option>Post-acute</option><option>Home Health</option><option>Transportation</option></select><button class="button" type="button">Filter</button></div><div class="card-grid"><?php foreach($items as $slug=>$item):?><a class="module-card" href="<?=App::e(App::url($base.'/'.$slug))?>"><div class="module-card-top"><span class="pill"><?=App::e((string)($item['category']??$item['topic']??'Guidance'))?></span><?php if(isset($item['status'])):?><span class="trust">● <?=App::e((string)$item['status'])?></span><?php endif;?></div><h2><?=App::e((string)$item['title'])?></h2><p><?=App::e((string)$item['summary'])?></p><footer><span><?=App::e((string)($item[$metaKey]??''))?></span><strong>Open →</strong></footer></a><?php endforeach;?></div><?php App::render($title,(string)ob_get_clean());
    }

    public static function insuranceDetail(array $item): void
    {
        $requirements=$item['requirements']??['Confirm the current payer rule in the source system before acting.','Collect the documentation required by the plan.','Confirm authorization or supplier acceptance when applicable.'];
        $misses=$item['misses']??['Requirements may vary by plan or benefit design.','Do not rely on a prior approval pattern without checking the current rule.'];
        ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/insurance'))?>">Insurance</a><span>/</span><span><?=App::e($item['payer'])?></span></nav><section class="detail-head"><div><span class="pill"><?=App::e($item['payer'])?></span><h1><?=App::e($item['title'])?></h1><p><?=App::e($item['summary'])?></p></div><aside class="source-card"><span>Current source</span><strong><?=App::e($item['source'])?></strong><small>Effective <?=App::e($item['effective'])?> · Reviewed <?=App::e($item['reviewed'])?></small></aside></section><div class="detail-grid"><div><section class="panel"><p class="eyebrow">Coverage workflow</p><h2>What Atlas wants you to verify</h2><ul class="check-list"><?php foreach($requirements as $row):?><li><?=App::e($row)?></li><?php endforeach;?></ul></section><section class="panel warning-panel"><p class="eyebrow">Common misses</p><h2>Where referrals get stuck</h2><ul class="check-list"><?php foreach($misses as $row):?><li><?=App::e($row)?></li><?php endforeach;?></ul></section></div><aside class="panel"><p class="eyebrow">Connected guidance</p><h2>Keep moving</h2><?php foreach(($item['links']??[]) as [$type,$label,$path]):?><a class="related" href="<?=App::e(App::url($path))?>"><span><small><?=App::e($type)?></small><?=App::e($label)?></span><b>→</b></a><?php endforeach;?><?php if(empty($item['links'])):?><a class="related" href="<?=App::e(App::url('/search?q='.rawurlencode($item['title'])))?>">Search related Atlas guidance <b>→</b></a><?php endif;?></aside></div><?php App::render($item['title'],(string)ob_get_clean());
    }

    public static function playbookDetail(array $item): void
    {
        $sequence=$item['sequence']??[['Confirm the need','Define the operational goal and timing.'],['Check requirements','Open the relevant payer and local guidance.'],['Complete the handoff','Confirm ownership and completion rather than assuming transmission equals success.']];
        ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/playbooks'))?>">Playbooks</a><span>/</span><span><?=App::e($item['title'])?></span></nav><section class="detail-head"><div><span class="pill"><?=App::e($item['category'])?></span><h1><?=App::e($item['title'])?></h1><p><?=App::e($item['summary'])?></p></div><aside class="source-card"><span>Guided workflow</span><strong><?=App::e((string)$item['steps'])?> steps</strong><small>Typical working time <?=App::e($item['time'])?></small></aside></section><?php if(!empty($item['warning'])):?><div class="callout"><strong>Before you start</strong><span><?=App::e($item['warning'])?></span></div><?php endif;?><div class="playbook-layout"><section class="panel"><p class="eyebrow">Operational sequence</p><h2>Work the whole handoff</h2><ol class="playbook-steps"><?php foreach($sequence as $i=>[$step,$desc]):?><li><span class="step-number"><?=($i+1)?></span><div><strong><?=App::e($step)?></strong><p><?=App::e($desc)?></p><?php if($item['title']==='Arrange Home Oxygen'&&$i===1):?><a href="<?=App::e(App::url('/insurance/medicare-oxygen'))?>">Open Medicare oxygen rule →</a><?php elseif($item['title']==='Arrange Home Oxygen'&&$i===6):?><a href="<?=App::e(App::url('/patient-resources/home-oxygen'))?>">Open patient education →</a><?php endif;?></div></li><?php endforeach;?></ol></section><aside><section class="panel"><p class="eyebrow">Supporting material</p><h2>Right beside the work</h2><a class="related" href="<?=App::e(App::url('/resources/home-oxygen'))?>">Home Oxygen Resource <b>→</b></a><a class="related" href="<?=App::e(App::url('/knowledge-base/discharge-documentation'))?>">Discharge Documentation Standard <b>→</b></a></section></aside></div><?php App::render($item['title'],(string)ob_get_clean());
    }

    public static function knowledgeDetail(array $item): void
    {
        $sections=$item['sections']??['Follow the approved local process described by the owning department.','Escalate questions to the content owner when the standard does not fit the operational situation.'];
        ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/knowledge-base'))?>">Knowledge Base</a><span>/</span><span><?=App::e($item['topic'])?></span></nav><section class="detail-head"><div><span class="pill">Local standard</span><h1><?=App::e($item['title'])?></h1><p><?=App::e($item['summary'])?></p></div><aside class="source-card"><span>Owner</span><strong><?=App::e($item['owner'])?></strong><small><?=App::e($item['status'])?> · Reviewed <?=App::e($item['reviewed'])?></small></aside></section><div class="detail-grid"><section class="panel"><p class="eyebrow">Organization guidance</p><h2>What this standard expects</h2><ul class="check-list"><?php foreach($sections as $row):?><li><?=App::e($row)?></li><?php endforeach;?></ul></section><aside class="panel distinction"><p class="eyebrow">Why this lives here</p><h2>Knowledge Base ≠ Resource Library</h2><p>This is local organizational guidance. Resources provide practical reference; Insurance holds payer rules; Playbooks guide the work.</p></aside></div><?php App::render($item['title'],(string)ob_get_clean());
    }

    public static function patientDetail(array $item): void
    {
        $sections=$item['sections']??['Your care team will tell you what happens next.','Keep the contact information you receive and call if the expected service or equipment does not arrive.','Call your clinical team when you have health questions or symptoms.'];
        ob_start();?><nav class="breadcrumb"><a href="<?=App::e(App::url('/patient-resources'))?>">Patient Resources</a><span>/</span><span><?=App::e($item['topic'])?></span></nav><section class="detail-head"><div><span class="pill">Patient handout</span><h1><?=App::e($item['title'])?></h1><p><?=App::e($item['summary'])?></p></div><aside class="source-card"><span>Format</span><strong><?=App::e((string)$item['pages'])?> pages · <?=App::e($item['reading'])?></strong><small><?=App::e($item['languages'])?></small></aside></section><div class="patient-layout"><section class="handout"><div class="handout-brand"><strong>ATLAS</strong><span>Patient Education</span></div><h2><?=App::e($item['title'])?></h2><?php foreach($sections as $row):?><p><?=App::e($row)?></p><?php endforeach;?><div class="handout-note">This handout is general education and does not replace instructions from your healthcare team.</div></section><aside class="panel"><p class="eyebrow">Staff tools</p><h2>Use this handout</h2><a class="button block" href="<?=App::e(App::url('/patient-resources/packet-builder?add='.rawurlencode($item['title'])))?>">Add to patient packet</a><button class="secondary-button" onclick="window.print()">Print preview</button><p class="phi-note"><strong>PHI-free by design.</strong> Do not add patient names, MRNs, DOBs, diagnoses, or patient-specific notes to this packet.</p></aside></div><?php App::render($item['title'],(string)ob_get_clean());
    }

    public static function packetBuilder(): void
    {
        $items=Fixtures::patientResources();$selected=(string)($_GET['add']??'Home Oxygen: What to Expect');
        ob_start();?><section class="page-head"><div><p class="eyebrow">Patient Resources</p><h1>Packet Builder</h1><p>Assemble reusable patient education without creating a patient record inside Atlas.</p></div><div class="count-card"><strong>PHI</strong><span>not collected</span></div></section><div class="packet-layout"><section class="panel"><p class="eyebrow">Available handouts</p><h2>Choose education</h2><div class="selection-list"><?php foreach($items as $item):?><label><input type="checkbox" <?=($item['title']===$selected?'checked':'')?>><span><strong><?=App::e($item['title'])?></strong><small><?=App::e($item['topic'])?> · <?=App::e((string)$item['pages'])?> pages</small></span></label><?php endforeach;?></div></section><section class="panel packet-preview"><p class="eyebrow">Packet preview</p><h2>Education packet</h2><div class="packet-page"><span>ATLAS · Patient Education</span><strong><?=App::e($selected)?></strong><small>Selected for packet</small></div><div class="packet-summary"><span>Estimated packet</span><strong>2–5 pages</strong></div><button class="button" onclick="window.print()">Print packet</button><p class="phi-note">Packet Builder intentionally stores no patient identifiers in this visual build.</p></section></div><?php App::render('Packet Builder',(string)ob_get_clean());
    }

    public static function search(): void
    {
        $q=trim((string)($_GET['q']??''));$rows=Fixtures::search($q);
        ob_start();?><section class="page-head"><div><p class="eyebrow">Unified Search</p><h1><?=($q!==''?'Results for “'.App::e($q).'”':'Search everything Atlas knows.')?></h1><p>One search across practical resources, payer guidance, Playbooks, local standards, and patient education.</p></div><div class="count-card"><strong><?=count($rows)?></strong><span>results</span></div></section><form class="search-hero" method="get" action="<?=App::e(App::url('/search'))?>"><input name="q" value="<?=App::e($q)?>" placeholder="Try oxygen, transportation, SNF…" autofocus><button class="button">Search Atlas</button></form><div class="search-results"><?php if(!$rows):?><section class="empty"><strong>No matching Atlas guidance</strong><p>Try a broader clinical or operational term.</p></section><?php endif;?><?php foreach($rows as $row):?><a href="<?=App::e(App::url($row['path']))?>"><span class="pill"><?=App::e($row['type'])?></span><div><h2><?=App::e($row['title'])?></h2><p><?=App::e($row['summary'])?></p><small><?=App::e($row['meta'])?></small></div><b>→</b></a><?php endforeach;?></div><?php App::render('Search',(string)ob_get_clean());
    }

    public static function workspace(): void
    {
        ob_start();?><section class="page-head"><div><p class="eyebrow">My Workspace</p><h1>Your working set, not another inbox.</h1><p>Keep frequently used guidance and unfinished operational work close at hand.</p></div></section><div class="workspace-grid"><section class="panel span-2"><div class="panel-head"><div><p class="eyebrow">Continue working</p><h2>Arrange Home Oxygen</h2></div><span class="status-chip">Step 3 of 7</span></div><div class="progress"><span style="width:43%"></span></div><p>Next: locate qualifying evidence and make the result easy for the supplier to find.</p><a class="button inline" href="<?=App::e(App::url('/playbooks/arrange-home-oxygen'))?>">Continue Playbook</a></section><section class="panel"><p class="eyebrow">Saved guidance</p><h2>Quick reference</h2><a class="related" href="<?=App::e(App::url('/insurance/medicare-oxygen'))?>">Medicare DME: Oxygen <b>→</b></a><a class="related" href="<?=App::e(App::url('/knowledge-base/discharge-documentation'))?>">Discharge Documentation <b>→</b></a></section><section class="panel"><p class="eyebrow">Patient packet</p><h2>Continue education packet</h2><p>Home Oxygen: What to Expect is selected.</p><a class="related" href="<?=App::e(App::url('/patient-resources/packet-builder'))?>">Open Packet Builder <b>→</b></a></section><section class="panel span-2"><p class="eyebrow">Recently used</p><h2>Back to the work</h2><div class="mini-grid"><a href="<?=App::e(App::url('/resources/home-oxygen'))?>"><span>Resource</span><strong>Home Oxygen Qualification</strong></a><a href="<?=App::e(App::url('/playbooks/snf-placement'))?>"><span>Playbook</span><strong>SNF Placement</strong></a><a href="<?=App::e(App::url('/patient-resources/home-health'))?>"><span>Patient Resource</span><strong>Starting Home Health</strong></a></div></section></div><?php App::render('My Workspace',(string)ob_get_clean());
    }

    public static function profile(): void
    {
        $user=Auth::user();ob_start();?><section class="page-head"><div><p class="eyebrow">Profile & context</p><h1><?=App::e((string)($user['display_name']??'Atlas User'))?></h1><p>Your identity and organization context shape what Atlas will eventually authorize and show.</p></div></section><div class="profile-grid"><section class="panel"><p class="eyebrow">Account</p><h2>Profile</h2><dl class="facts"><div><dt>Name</dt><dd><?=App::e((string)($user['display_name']??'Atlas User'))?></dd></div><div><dt>Email</dt><dd><?=App::e((string)($user['email']??'—'))?></dd></div><div><dt>Role</dt><dd><?=App::e((string)($user['role']??'Member'))?></dd></div></dl></section><section class="panel"><p class="eyebrow">Organization context</p><h2>Atlas Demo Health</h2><p>The organization switch is visual for now. In the functional pass, the server—not the browser—will determine memberships and authorized organization context.</p><button class="secondary-button" type="button">Change organization</button></section><section class="panel span-2 distinction"><p class="eyebrow">Security boundary</p><h2>Organization context is not a client-side permission.</h2><p>Future requests will resolve the authenticated user’s membership and permissions on the server before data is returned or changed.</p></section></div><?php App::render('Profile',(string)ob_get_clean());
    }
}
