<?php

declare(strict_types=1);

final class DemoOrganizationSeeder
{
    public function __construct(private PDO $db) {}

    public function create(int $ownerUserId): array
    {
        $suffix=strtolower(substr(bin2hex(random_bytes(3)),0,6));$password='Atlas!'.bin2hex(random_bytes(4));$today=date('Y-m-d');$monday=date('Y-m-d',strtotime('monday this week'));
        $this->db->beginTransaction();
        try {
            $name='Atlas Full Demo '.strtoupper($suffix);$slug='atlas-full-demo-'.$suffix;
            $this->db->prepare('INSERT INTO organizations (name,slug,organization_type,timezone,created_by) VALUES (?, ?, "multispecialty", "America/New_York", ?)')->execute([$name,$slug,$ownerUserId]);$oid=(int)$this->db->lastInsertId();
            $this->db->prepare('INSERT INTO memberships (organization_id,user_id,role,status) VALUES (?, ?, "owner", "active")')->execute([$oid,$ownerUserId]);$ownerMembership=(int)$this->db->lastInsertId();
            $this->db->prepare('INSERT INTO organization_security_settings (organization_id,allow_local_accounts,updated_by) VALUES (?,1,?)')->execute([$oid,$ownerUserId]);
            $this->db->prepare('INSERT INTO organization_settings (organization_id,display_name,timezone,week_starts_on,primary_color,secondary_color,logo_text,updated_by) VALUES (?, ?, "America/New_York",1,"#2867d8","#7756d9","Atlas Demo",?)')->execute([$oid,$name,$ownerUserId]);

            $locationInsert=$this->db->prepare('INSERT INTO locations (organization_id,name,timezone,is_primary) VALUES (?, ?, "America/New_York", ?)');$locations=[];foreach([['Harbor Medical Center',1],['Riverside Specialty Clinic',0],['Central Operations Hub',0]] as [$label,$primary]){$locationInsert->execute([$oid,$label,$primary]);$locations[]=(int)$this->db->lastInsertId();}
            $departmentInsert=$this->db->prepare('INSERT INTO departments (organization_id,location_id,name,color) VALUES (?,?,?,?)');$departments=[];foreach([[$locations[0],'Clinical Support','#2867d8'],[$locations[0],'Front Office','#7756d9'],[$locations[1],'Procedural Services','#0d9a7c'],[$locations[2],'Central Scheduling','#e87921']] as $row){$departmentInsert->execute([$oid,...$row]);$departments[]=(int)$this->db->lastInsertId();}
            $positionInsert=$this->db->prepare('INSERT INTO positions (organization_id,department_id,name,category,color) VALUES (?,?,?,?,?)');$positions=[];foreach([[$departments[0],'Medical Assistant','clinical_support','#2867d8'],[$departments[0],'Clinical Lead','leadership','#164ea6'],[$departments[1],'Patient Services Representative','front_office','#7756d9'],[$departments[2],'Procedure Technician','procedural','#0d9a7c'],[$departments[3],'Scheduling Coordinator','administrative','#e87921']] as $row){$positionInsert->execute([$oid,...$row]);$positions[]=(int)$this->db->lastInsertId();}

            $accounts=[];$staff=[['Demo Administrator','admin',1],['Demo Scheduler','scheduler',4],['Demo Supervisor','supervisor',2],['Alex Morgan','member',1],['Jordan Lee','member',1],['Taylor Brooks','member',3],['Casey Rivera','member',3],['Riley Chen','member',5],['Morgan Patel','member',1],['Jamie Wilson','member',3],['Avery Johnson','member',4],['Cameron Smith','member',5]];
            $members=[];foreach($staff as $i=>[$staffName,$role,$positionNumber]){$username='demo.'.strtolower(str_replace(' ','-',preg_replace('/^Demo /','',$staffName))).'.'.$suffix;$email=$username.'@local.atlas.invalid';$this->db->prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)')->execute([$staffName,$email,password_hash($password,PASSWORD_DEFAULT)]);$uid=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO local_accounts (user_id,organization_id,username,must_change_password,created_by) VALUES (?,?,?,0,?)')->execute([$uid,$oid,$username,$ownerUserId]);$this->db->prepare('INSERT INTO memberships (organization_id,user_id,role,status) VALUES (?,?,?,"active")')->execute([$oid,$uid,$role]);$mid=(int)$this->db->lastInsertId();$positionIndex=$positionNumber-1;$departmentId=(int)[$departments[0],$departments[0],$departments[1],$departments[2],$departments[3]][$positionIndex];$locationId=$departmentId===$departments[2]?$locations[1]:($departmentId===$departments[3]?$locations[2]:$locations[0]);$this->db->prepare('INSERT INTO staff_assignments (organization_id,membership_id,location_id,department_id,position_id,is_primary) VALUES (?,?,?,?,?,1)')->execute([$oid,$mid,$locationId,$departmentId,$positions[$positionIndex]]);$this->db->prepare('INSERT INTO workforce_profiles (membership_id,organization_id,employment_type,expected_weekly_hours,flex_eligible,opening_eligible,closing_eligible) VALUES (?, ?, ?, ?, 1, ?, ?)')->execute([$mid,$oid,$i>8?'part_time':'full_time',$i>8?24:40,$i%2,$i%3===0]);$members[]=$mid;$accounts[]=['name'=>$staffName,'username'=>$username,'password'=>$password,'role'=>$role];}

            $this->db->prepare('INSERT INTO teams (organization_id,department_id,name) VALUES (?, ?, "Blue Team"),(?, ?, "Green Team"),(?, ?, "Access Center")')->execute([$oid,$departments[0],$oid,$departments[2],$oid,$departments[3]]);
            $this->db->prepare('INSERT INTO providers (organization_id,location_id,department_id,name,specialty) VALUES (?,?,?,"Dr. Maya Thompson","Family Medicine"),(?,?,?,"Dr. Samuel Ortiz","Internal Medicine"),(?,?,?,"Dr. Priya Shah","Cardiology")')->execute([$oid,$locations[0],$departments[0],$oid,$locations[0],$departments[0],$oid,$locations[1],$departments[2]]);$providers=$this->db->query('SELECT id FROM providers WHERE organization_id='.$oid.' ORDER BY id')->fetchAll(PDO::FETCH_COLUMN);
            $this->db->prepare('INSERT INTO stations (organization_id,location_id,department_id,name) VALUES (?,?,?,"Pod A"),(?,?,?,"Pod B"),(?,?,?,"Procedure Room 1")')->execute([$oid,$locations[0],$departments[0],$oid,$locations[0],$departments[0],$oid,$locations[1],$departments[2]]);$stations=$this->db->query('SELECT id FROM stations WHERE organization_id='.$oid.' ORDER BY id')->fetchAll(PDO::FETCH_COLUMN);
            $this->db->prepare('INSERT INTO work_functions (organization_id,department_id,name,color) VALUES (?, ?, "Inbox Coverage","#0d9a7c"),(?, ?, "Prior Authorizations","#e87921"),(?, ?, "Referral Queue","#7756d9")')->execute([$oid,$departments[0],$oid,$departments[1],$oid,$departments[3]]);
            $this->db->prepare('INSERT INTO qualifications (organization_id,name) VALUES (?,"CPR/BLS"),(?,"Medication Administration"),(?,"Procedure Support")')->execute([$oid,$oid,$oid]);$qualifications=$this->db->query('SELECT id FROM qualifications WHERE organization_id='.$oid.' ORDER BY id')->fetchAll(PDO::FETCH_COLUMN);$qualInsert=$this->db->prepare('INSERT INTO staff_qualifications (membership_id,qualification_id,expires_on,verified_at) VALUES (?,?,?,NOW())');foreach($members as $i=>$mid){$qualInsert->execute([$mid,$qualifications[0],date('Y-m-d',strtotime('+'.(30+$i*20).' days'))]);if($i%2===0)$qualInsert->execute([$mid,$qualifications[1],date('Y-m-d',strtotime('+1 year'))]);}

            $this->db->prepare('INSERT INTO request_types (organization_id,name,paid) VALUES (?,"Paid Time Off",1),(?,"Sick Leave",1),(?,"Unpaid Leave",0),(?,"Education Day",1)')->execute([$oid,$oid,$oid,$oid]);$requestTypes=$this->db->query('SELECT id FROM request_types WHERE organization_id='.$oid.' ORDER BY id')->fetchAll(PDO::FETCH_COLUMN);
            $availability=$this->db->prepare('INSERT INTO availability_entries (organization_id,membership_id,entry_type,weekday,availability,starts_at,ends_at,status,reviewed_by,reviewed_at) VALUES (?,?,"recurring",?, ?, ?, ?, ?, ?, NOW())');foreach($members as $i=>$mid){foreach(range(1,5) as $day)$availability->execute([$oid,$mid,$day,$i%5===0&&$day===5?'unavailable':'available',$i%3===0?'07:30':'08:00',$i%3===0?'16:00':'16:30',$i===10?'pending':'approved',$ownerUserId]);}
            $timeOff=$this->db->prepare('INSERT INTO time_off_requests (organization_id,membership_id,request_type_id,starts_on,ends_on,employee_note,manager_note,status,reviewed_by,reviewed_at) VALUES (?,?,?,?,?,?,?,?,?,NOW())');foreach([[$members[3],$requestTypes[0],7,'pending'],[$members[4],$requestTypes[1],2,'approved'],[$members[6],$requestTypes[3],14,'denied']] as [$mid,$type,$offset,$status])$timeOff->execute([$oid,$mid,$type,date('Y-m-d',strtotime('+'.$offset.' days')),date('Y-m-d',strtotime('+'.$offset.' days')),'Demo employee request',$status==='denied'?'Coverage unavailable':'Demo manager note',$status,$ownerUserId]);

            $this->db->prepare('INSERT INTO schedule_periods (organization_id,name,starts_on,ends_on,status,created_by) VALUES (?,"Current Demo Schedule",?,?,"published",?),(?,"Next Demo Schedule",?,?,"draft",?)')->execute([$oid,date('Y-m-d',strtotime($monday.' -7 days')),date('Y-m-d',strtotime($monday.' +13 days')),$ownerUserId,$oid,date('Y-m-d',strtotime($monday.' +14 days')),date('Y-m-d',strtotime($monday.' +27 days')),$ownerUserId]);$q=$this->db->prepare('SELECT id FROM schedule_periods WHERE organization_id=? AND name="Current Demo Schedule"');$q->execute([$oid]);$period=(int)$q->fetchColumn();
            $shiftInsert=$this->db->prepare('INSERT INTO shifts (organization_id,schedule_period_id,location_id,department_id,assigned_membership_id,shift_date,starts_at,ends_at,status,eligibility_mode,exact_position_id,cross_department_mode,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$shiftIds=[];foreach(range(-5,14) as $dayOffset){$weekday=(int)date('N',strtotime($today.' '.$dayOffset.' days'));if($weekday>5)continue;foreach(array_slice($members,3,8) as $i=>$mid){$pos=$positions[$i%count($positions)];$dept=(int)[$departments[0],$departments[0],$departments[1],$departments[2],$departments[3]][$i%5];$loc=$dept===$departments[2]?$locations[1]:($dept===$departments[3]?$locations[2]:$locations[0]);$assigned=($dayOffset===3&&$i===2)?null:$mid;$shiftInsert->execute([$oid,$period,$loc,$dept,$assigned,date('Y-m-d',strtotime($today.' '.$dayOffset.' days')),$i%3===0?'07:30':'08:00',$i%3===0?'16:00':'16:30',$assigned?'assigned':'open','exact',$pos,$i%4===0?'approval':'prohibited','Seeded demo shift',$ownerUserId]);$shiftIds[]=(int)$this->db->lastInsertId();}}
            $coverage=$this->db->prepare('INSERT INTO coverage_assignments (organization_id,shift_id,membership_id,provider_id,station_id,coverage_type,created_by) VALUES (?,?,?,?,?,?,?)');foreach(array_slice($shiftIds,0,12) as $i=>$shift)$coverage->execute([$oid,$shift,$members[3+$i%5],$providers[$i%3]??null,$stations[$i%3]??null,$i%4===0?'backup':'primary',$ownerUserId]);
            $providerSession=$this->db->prepare('INSERT INTO provider_sessions (organization_id,provider_id,location_id,department_id,session_date,starts_at,ends_at,support_count,notes,created_by) VALUES (?,?,?,?,?,"08:00","12:00",2,"Demo provider session",?)');foreach(range(0,6) as $d)if((int)date('N',strtotime('+'.$d.' days'))<=5)$providerSession->execute([$oid,$providers[$d%3],$d%3===2?$locations[1]:$locations[0],$d%3===2?$departments[2]:$departments[0],date('Y-m-d',strtotime('+'.$d.' days')),$ownerUserId]);
            $requirement=$this->db->prepare('INSERT INTO coverage_requirements (organization_id,location_id,department_id,provider_id,weekday,starts_at,ends_at,required_count,priority,created_by) VALUES (?,?,?,?,?,"08:00","16:30",?,?,?)');foreach(range(1,5) as $day)$requirement->execute([$oid,$locations[0],$departments[0],$providers[0],$day,2,$day===1?'critical':'standard',$ownerUserId]);
            $this->db->prepare('INSERT INTO shift_templates (organization_id,name,location_id,department_id,position_id,starts_at,ends_at,cross_department_mode,notes,created_by) VALUES (?,"Standard MA Day",?,?,?,"08:00","16:30","approval","Reusable demo template",?),(?,"Early Front Desk",?,?,?,"07:30","16:00","prohibited","Opening template",?)')->execute([$oid,$locations[0],$departments[0],$positions[0],$ownerUserId,$oid,$locations[0],$departments[1],$positions[2],$ownerUserId]);

            $this->db->prepare('INSERT INTO credential_types (organization_id,name,issuing_authority,renewal_days,warning_days) VALUES (?,"BLS","American Heart Association",730,60),(?,"Certified Medical Assistant","AAMA",365,90)')->execute([$oid,$oid]);$credentialTypes=$this->db->query('SELECT id FROM credential_types WHERE organization_id='.$oid.' ORDER BY id')->fetchAll(PDO::FETCH_COLUMN);foreach(array_slice($members,3,6) as $i=>$mid)$this->db->prepare('INSERT INTO member_credentials (organization_id,membership_id,credential_type_id,credential_number,issued_on,expires_on,status,verified_by,verified_at) VALUES (?,?,?,?,?,?,"verified",?,NOW())')->execute([$oid,$mid,$credentialTypes[$i%2],'DEMO-'.str_pad((string)$i,4,'0',STR_PAD_LEFT),date('Y-m-d',strtotime('-1 year')),date('Y-m-d',strtotime('+'.(15+$i*45).' days')),$ownerUserId]);
            foreach(array_slice($members,3,8) as $i=>$mid){$this->db->prepare('INSERT INTO pay_profiles (membership_id,organization_id,pay_type,hourly_rate,overtime_multiplier,overtime_weekly_hours,updated_by) VALUES (?, ?, "hourly", ?,1.5,40,?)')->execute([$mid,$oid,20+$i*1.75,$ownerUserId]);$shift=$shiftIds[$i]??null;if($shift)$this->db->prepare('INSERT INTO time_entries (organization_id,membership_id,shift_id,clocked_in_at,clocked_out_at,break_minutes,status,employee_note,reviewed_by,reviewed_at) VALUES (?,?,?,DATE_SUB(NOW(),INTERVAL 9 HOUR),DATE_SUB(NOW(),INTERVAL 1 HOUR),30,?,"Demo time entry",?,NOW())')->execute([$oid,$mid,$shift,$i===7?'submitted':'approved',$ownerUserId]);}
            $this->db->prepare('INSERT INTO master_schedules (organization_id,name,effective_from,active,created_by) VALUES (?,"Standard Clinic Week",?,1,?)')->execute([$oid,$monday,$ownerUserId]);$master=(int)$this->db->lastInsertId();$masterEntry=$this->db->prepare('INSERT INTO master_schedule_entries (master_schedule_id,organization_id,membership_id,weekday,location_id,department_id,position_id,starts_at,ends_at,notes) VALUES (?,?,?,?,?,?,?,"08:00","16:30","Demo recurring assignment")');foreach(array_slice($members,3,6) as $i=>$mid)foreach(range(1,5) as $day)$masterEntry->execute([$master,$oid,$mid,$day,$locations[0],$departments[$i%2],$positions[$i%2]]);

            $calloutShift=$shiftIds[count($shiftIds)-2];$this->db->prepare('INSERT INTO callouts (organization_id,shift_id,membership_id,reason_category,employee_note,status,acknowledged_by,acknowledged_at) VALUES (?,?,?,"illness","Demo callout for testing","replacement_open",?,NOW())')->execute([$oid,$calloutShift,$members[4],$ownerUserId]);$callout=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO callout_offers (callout_id,membership_id,eligibility_result,status) VALUES (?, ?, "eligible","offered"),(?, ?, "approval","accepted")')->execute([$callout,$members[5],$callout,$members[6]]);
            $this->db->prepare('INSERT INTO message_threads (organization_id,subject,thread_type,created_by) VALUES (?,"Welcome to the Atlas demo","announcement",?)')->execute([$oid,$ownerUserId]);$thread=(int)$this->db->lastInsertId();$threadMember=$this->db->prepare('INSERT INTO message_thread_members (thread_id,membership_id) VALUES (?,?)');foreach(array_merge([$ownerMembership],$members) as $mid)$threadMember->execute([$thread,$mid]);$this->db->prepare('INSERT INTO messages (thread_id,sender_membership_id,body) VALUES (?, ?, "This demo organization is ready for full workflow testing."),(?, ?, "Schedules, requests, credentials, and coverage examples are already loaded.")')->execute([$thread,$ownerMembership,$thread,$members[0]]);
            $notice=$this->db->prepare('INSERT INTO notifications (organization_id,membership_id,notification_type,title,body,action_route) VALUES (?,?,"demo","Demo workspace ready","Explore your role-specific pages and workflows","dashboard")');foreach($members as $mid)$notice->execute([$oid,$mid]);
            $this->db->prepare('INSERT INTO fairness_settings (organization_id,hours_weight,opening_weight,closing_weight,weekend_weight,declined_offer_weight,cost_weight,updated_by) VALUES (?,1,2,2,2,0.5,0.25,?)')->execute([$oid,$ownerUserId]);
            $this->db->prepare('INSERT INTO audit_logs (organization_id,user_id,action,entity_type,entity_id,metadata_json) VALUES (?, ?, "demo.organization_created", "organization", ?, ?)')->execute([$oid,$ownerUserId,$oid,json_encode(['accounts'=>count($accounts),'shifts'=>count($shiftIds)])]);
            $accounts[]=['name'=>'Organization Owner','username'=>'Use your current account','password'=>'Existing password','role'=>'owner'];$this->db->commit();return ['organization_id'=>$oid,'organization_name'=>$name,'accounts'=>$accounts,'password'=>$password];
        } catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }
}
