<?php
declare(strict_types=1);

final class ProductionReadinessRepository
{
    public function __construct(private PDO $db) {}

    public function trendReport(int $oid,string $from,string $through): array
    {
        if(!$from||!$through||$through<$from)throw new InvalidArgumentException('Choose a valid trend period.');$months=[];$cursor=(new DateTimeImmutable($from))->modify('first day of this month');$end=new DateTimeImmutable($through);while($cursor<=$end){$months[$cursor->format('Y-m')]=['month'=>$cursor->format('Y-m'),'scheduled_hours'=>0,'open_shifts'=>0,'callouts'=>0,'time_off_hours'=>0];$cursor=$cursor->modify('+1 month');}$q=$this->db->prepare('SELECT DATE_FORMAT(shift_date,"%Y-%m") month,SUM(TIME_TO_SEC(TIMEDIFF(ends_at,starts_at))/3600) scheduled_hours,SUM(status="open") open_shifts FROM shifts WHERE organization_id=? AND shift_date BETWEEN ? AND ? AND status<>"cancelled" GROUP BY DATE_FORMAT(shift_date,"%Y-%m")');$q->execute([$oid,$from,$through]);foreach($q->fetchAll() as $r)if(isset($months[$r['month']]))$months[$r['month']]=array_merge($months[$r['month']],$r);$q=$this->db->prepare('SELECT DATE_FORMAT(reported_at,"%Y-%m") month,COUNT(*) callouts FROM callouts WHERE organization_id=? AND DATE(reported_at) BETWEEN ? AND ? GROUP BY DATE_FORMAT(reported_at,"%Y-%m")');$q->execute([$oid,$from,$through]);foreach($q->fetchAll() as $r)if(isset($months[$r['month']]))$months[$r['month']]['callouts']=(int)$r['callouts'];$q=$this->db->prepare('SELECT DATE_FORMAT(starts_on,"%Y-%m") month,SUM((DATEDIFF(ends_on,starts_on)+1)*8) time_off_hours FROM time_off_requests WHERE organization_id=? AND status="approved" AND starts_on BETWEEN ? AND ? GROUP BY DATE_FORMAT(starts_on,"%Y-%m")');$q->execute([$oid,$from,$through]);foreach($q->fetchAll() as $r)if(isset($months[$r['month']]))$months[$r['month']]['time_off_hours']=(float)$r['time_off_hours'];return array_values($months);
    }

    public function saveView(int $oid,int $member,array $in): void {$this->member($oid,$member);$name=trim((string)($in['name']??''));$type=in_array($in['view_type']??'', ['report','schedule','search'],true)?$in['view_type']:'search';$route=trim((string)($in['route']??''));if($name===''||$route==='')throw new InvalidArgumentException('Saved view name and route are required.');$parameters=[];parse_str((string)($in['parameters']??''),$parameters);$this->db->prepare('INSERT INTO saved_views (organization_id,membership_id,view_type,name,route,parameters_json,favorite) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE route=VALUES(route),parameters_json=VALUES(parameters_json),favorite=VALUES(favorite)')->execute([$oid,$member,$type,$name,$route,json_encode($parameters),!empty($in['favorite'])]);}
    public function savedViews(int $oid,int $member): array {$this->member($oid,$member);$q=$this->db->prepare('SELECT * FROM saved_views WHERE organization_id=? AND membership_id=? ORDER BY favorite DESC,updated_at DESC');$q->execute([$oid,$member]);$rows=$q->fetchAll();foreach($rows as &$r)$r['parameters']=json_decode($r['parameters_json'],true)?:[];return $rows;}
    public function recordNavigation(int $oid,int $member,string $route,string $title): void {$this->member($oid,$member);$q=$this->db->prepare('SELECT route FROM navigation_activity WHERE membership_id=? ORDER BY visited_at DESC LIMIT 1');$q->execute([$member]);if($q->fetchColumn()===$route)return;$this->db->prepare('INSERT INTO navigation_activity (organization_id,membership_id,route,title) VALUES (?,?,?,?)')->execute([$oid,$member,mb_substr($route,0,120),mb_substr($title,0,180)]);$this->db->prepare('DELETE FROM navigation_activity WHERE membership_id=? AND id NOT IN (SELECT id FROM (SELECT id FROM navigation_activity WHERE membership_id=? ORDER BY visited_at DESC LIMIT 30) recent)')->execute([$member,$member]);}
    public function recentNavigation(int $oid,int $member): array {$this->member($oid,$member);$q=$this->db->prepare('SELECT route,title,MAX(visited_at) visited_at FROM navigation_activity WHERE organization_id=? AND membership_id=? GROUP BY route,title ORDER BY visited_at DESC LIMIT 10');$q->execute([$oid,$member]);return $q->fetchAll();}
    public function search(int $oid,string $term): array {$term=trim($term);if(mb_strlen($term)<2)return [];$like='%'.$term.'%';$out=[];$queries=[['person','SELECT m.id id,u.name title,CONCAT(COALESCE(d.name,"No department")," · ",u.email) subtitle,"employee" route FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN staff_assignments sa ON sa.membership_id=m.id AND sa.is_primary=1 LEFT JOIN departments d ON d.id=sa.department_id WHERE m.organization_id=? AND (u.name LIKE ? OR u.email LIKE ?) LIMIT 10'],['department','SELECT id,name title,"Department" subtitle,"organization" route FROM departments WHERE organization_id=? AND name LIKE ? LIMIT 10'],['position','SELECT id,name title,"Position" subtitle,"organization" route FROM positions WHERE organization_id=? AND name LIKE ? LIMIT 10'],['shift','SELECT id,CONCAT(shift_date," · ",starts_at) title,notes subtitle,"schedule" route FROM shifts WHERE organization_id=? AND (notes LIKE ? OR shift_date LIKE ?) LIMIT 10']];foreach($queries as [$type,$sql]){$q=$this->db->prepare($sql);$q->execute(substr_count($sql,'?')===3?[$oid,$like,$like]:[$oid,$like]);foreach($q->fetchAll() as $row){$row['type']=$type;$out[]=$row;}}return $out;}

    public function previewImport(int $oid,int $uid,string $type,string $csv,string $source='pasted.csv'): int {$allowed=['locations','departments','positions','coverage_requirements'];if(!in_array($type,$allowed,true))throw new InvalidArgumentException('Unsupported import type.');$lines=preg_split('/\r\n|\r|\n/',trim($csv));if(count($lines)<2)throw new InvalidArgumentException('CSV must include a header and at least one row.');$header=array_map(fn($v)=>strtolower(trim($v)),str_getcsv(array_shift($lines)));$required=['locations'=>['name'],'departments'=>['name','location'],'positions'=>['name','department','category'],'coverage_requirements'=>['location','department','weekday','starts_at','ends_at','required_count']][$type];$missing=array_diff($required,$header);if($missing)throw new InvalidArgumentException('Missing columns: '.implode(', ',$missing));$rows=[];$invalid=0;foreach($lines as $index=>$line){if(trim($line)==='')continue;$values=str_getcsv($line);if(count($values)!==count($header)){$payload=[];$errors=['Column count does not match header.'];}else{$payload=array_combine($header,$values);$errors=[];foreach($required as $column)if(trim((string)($payload[$column]??''))==='')$errors[]=$column.' is required.';}$rows[]=['number'=>$index+2,'payload'=>$payload,'errors'=>$errors];if($errors)$invalid++;}$this->db->beginTransaction();try{$this->db->prepare('INSERT INTO data_import_jobs (organization_id,import_type,status,source_name,row_count,valid_count,invalid_count,created_by) VALUES (?,? ,"preview",?,?,?,?,?)')->execute([$oid,$type,$source,count($rows),count($rows)-$invalid,$invalid,$uid]);$job=(int)$this->db->lastInsertId();$insert=$this->db->prepare('INSERT INTO data_import_rows (import_job_id,row_number,payload_json,status,error_message) VALUES (?,?,?,?,?)');foreach($rows as $row)$insert->execute([$job,$row['number'],json_encode($row['payload']),$row['errors']?'invalid':'valid',$row['errors']?implode(' ',$row['errors']):null]);$this->db->commit();return $job;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    public function importJobs(int $oid): array {$q=$this->db->prepare('SELECT dij.*,u.name created_by_name FROM data_import_jobs dij JOIN users u ON u.id=dij.created_by WHERE dij.organization_id=? ORDER BY dij.created_at DESC LIMIT 30');$q->execute([$oid]);return $q->fetchAll();}
    public function importRows(int $oid,int $job): array {$q=$this->db->prepare('SELECT dir.* FROM data_import_rows dir JOIN data_import_jobs dij ON dij.id=dir.import_job_id WHERE dir.import_job_id=? AND dij.organization_id=? ORDER BY dir.row_number');$q->execute([$job,$oid]);$rows=$q->fetchAll();foreach($rows as &$r)$r['payload']=json_decode($r['payload_json'],true)?:[];return $rows;}
    public function commitImport(int $oid,int $uid,int $job): int {$q=$this->db->prepare('SELECT * FROM data_import_jobs WHERE id=? AND organization_id=? AND status="preview"');$q->execute([$job,$oid]);$meta=$q->fetch();if(!$meta||$meta['invalid_count'])throw new InvalidArgumentException('Only a fully valid preview can be committed.');$rows=$this->importRows($oid,$job);$count=0;$this->db->beginTransaction();try{foreach($rows as $row){$p=$row['payload'];$id=null;if($meta['import_type']==='locations'){$this->db->prepare('INSERT INTO locations (organization_id,name) VALUES (?,?)')->execute([$oid,trim($p['name'])]);$id=(int)$this->db->lastInsertId();}elseif($meta['import_type']==='departments'){$location=$this->named('locations',$oid,$p['location']);$this->db->prepare('INSERT INTO departments (organization_id,location_id,name,color) VALUES (?,?,?,"#2867d8")')->execute([$oid,$location,trim($p['name'])]);$id=(int)$this->db->lastInsertId();}elseif($meta['import_type']==='positions'){$department=$this->named('departments',$oid,$p['department']);$category=in_array($p['category'],['clinical_support','provider','front_office','procedural','diagnostic','administrative','revenue_cycle','operations','leadership','other'],true)?$p['category']:'other';$this->db->prepare('INSERT INTO positions (organization_id,department_id,name,category,color) VALUES (?,?,?,?,"#7756d9")')->execute([$oid,$department,trim($p['name']),$category]);$id=(int)$this->db->lastInsertId();}else{throw new InvalidArgumentException('Coverage imports require interactive resource validation and remain preview-only.');}$this->db->prepare('UPDATE data_import_rows SET status="committed",created_resource_id=? WHERE id=?')->execute([$id,$row['id']]);$count++;}$this->db->prepare('UPDATE data_import_jobs SET status="committed",committed_at=NOW() WHERE id=?')->execute([$job]);$this->db->commit();return $count;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    public function rollbackImport(int $oid,int $job): int {$q=$this->db->prepare('SELECT * FROM data_import_jobs WHERE id=? AND organization_id=? AND status="committed"');$q->execute([$job,$oid]);$meta=$q->fetch();if(!$meta)throw new InvalidArgumentException('Committed import unavailable.');$table=['locations'=>'locations','departments'=>'departments','positions'=>'positions'][$meta['import_type']]??null;if(!$table)throw new InvalidArgumentException('This import cannot be automatically rolled back.');$rows=$this->importRows($oid,$job);$count=0;$this->db->beginTransaction();try{foreach(array_reverse($rows) as $row)if($row['created_resource_id']){$q=$this->db->prepare("DELETE FROM {$table} WHERE id=? AND organization_id=?");$q->execute([$row['created_resource_id'],$oid]);$count+=$q->rowCount();}$this->db->prepare('UPDATE data_import_rows SET status="rolled_back" WHERE import_job_id=?')->execute([$job]);$this->db->prepare('UPDATE data_import_jobs SET status="rolled_back",rolled_back_at=NOW() WHERE id=?')->execute([$job]);$this->db->commit();return $count;}catch(PDOException $e){if($this->db->inTransaction())$this->db->rollBack();throw new InvalidArgumentException('Rollback is blocked because imported records are already in use. Archive them instead.');}}
    public function createSupportRequest(int $oid,int $member,array $in): void {$this->member($oid,$member);$subject=trim((string)($in['subject']??''));$description=trim((string)($in['description']??''));$category=in_array($in['category']??'', ['question','defect','access','data','security'],true)?$in['category']:'question';if($subject===''||$description==='')throw new InvalidArgumentException('Support subject and description are required.');$this->db->prepare('INSERT INTO support_requests (organization_id,membership_id,category,subject,description) VALUES (?,?,?,?,?)')->execute([$oid,$member,$category,$subject,$description]);}
    public function supportRequests(int $oid): array {$q=$this->db->prepare('SELECT sr.*,u.name requester_name FROM support_requests sr JOIN memberships m ON m.id=sr.membership_id JOIN users u ON u.id=m.user_id WHERE sr.organization_id=? ORDER BY FIELD(sr.status,"open","in_progress","resolved","closed"),sr.created_at DESC');$q->execute([$oid]);return $q->fetchAll();}
    private function named(string $table,int $oid,string $name): int {if(!in_array($table,['locations','departments'],true))throw new LogicException('Invalid import lookup.');$q=$this->db->prepare("SELECT id FROM {$table} WHERE organization_id=? AND LOWER(name)=LOWER(?) AND active=1");$q->execute([$oid,trim($name)]);$id=$q->fetchColumn();if(!$id)throw new InvalidArgumentException(ucfirst(rtrim($table,'s')).' not found: '.$name);return (int)$id;}
    private function member(int $oid,int $member): void {$q=$this->db->prepare('SELECT COUNT(*) FROM memberships WHERE id=? AND organization_id=? AND status="active"');$q->execute([$member,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Membership unavailable.');}
}
