<?php
declare(strict_types=1);

final class WorkforceExperienceRepository
{
    public function __construct(private PDO $db) {}

    public function deliverySettings(int $oid,int $member): array {$this->member($oid,$member);$q=$this->db->prepare('SELECT * FROM notification_delivery_settings WHERE organization_id=? AND membership_id=?');$q->execute([$oid,$member]);return $q->fetch()?:['quiet_starts_at'=>null,'quiet_ends_at'=>null,'digest_frequency'=>'immediate','push_enabled'=>0];}
    public function saveDeliverySettings(int $oid,int $member,array $in): void {$this->member($oid,$member);$frequency=in_array($in['digest_frequency']??'', ['immediate','daily','weekly'],true)?$in['digest_frequency']:'immediate';$this->db->prepare('INSERT INTO notification_delivery_settings (membership_id,organization_id,quiet_starts_at,quiet_ends_at,digest_frequency,push_enabled) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE quiet_starts_at=VALUES(quiet_starts_at),quiet_ends_at=VALUES(quiet_ends_at),digest_frequency=VALUES(digest_frequency),push_enabled=VALUES(push_enabled)')->execute([$member,$oid,$in['quiet_starts_at']?:null,$in['quiet_ends_at']?:null,$frequency,!empty($in['push_enabled'])]);}
    public function saveNotificationTemplate(int $oid,array $in): void {$event=trim((string)($in['event_key']??''));$subject=trim((string)($in['subject_template']??''));$body=trim((string)($in['body_template']??''));$channel=in_array($in['channel']??'', ['in_app','email','push'],true)?$in['channel']:'in_app';if($event===''||$subject===''||$body==='')throw new InvalidArgumentException('Template event, subject, and body are required.');$this->db->prepare('INSERT INTO notification_templates (organization_id,event_key,channel,subject_template,body_template) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE subject_template=VALUES(subject_template),body_template=VALUES(body_template),active=1')->execute([$oid,$event,$channel,$subject,$body]);}
    public function notificationOperations(int $oid): array {$q=$this->db->prepare('SELECT * FROM notification_templates WHERE organization_id=? AND active=1 ORDER BY event_key,channel');$q->execute([$oid]);$templates=$q->fetchAll();$q=$this->db->prepare('SELECT nd.*,u.name staff_name FROM notification_deliveries nd JOIN memberships m ON m.id=nd.membership_id JOIN users u ON u.id=m.user_id WHERE nd.organization_id=? ORDER BY nd.created_at DESC LIMIT 100');$q->execute([$oid]);return ['templates'=>$templates,'deliveries'=>$q->fetchAll()];}

    public function requireCredential(int $oid,array $in): void {$position=(int)($in['position_id']??0);$type=(int)($in['credential_type_id']??0);$this->resource('positions',$oid,$position);$this->resource('credential_types',$oid,$type);$this->db->prepare('INSERT INTO position_credential_requirements (organization_id,position_id,credential_type_id,required) VALUES (?,?,?,1) ON DUPLICATE KEY UPDATE required=1')->execute([$oid,$position,$type]);}
    public function requestRenewal(int $oid,int $uid,array $in): void {$credential=(int)($in['member_credential_id']??0);$q=$this->db->prepare('SELECT COUNT(*) FROM member_credentials WHERE id=? AND organization_id=?');$q->execute([$credential,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Credential unavailable.');$this->db->prepare('INSERT INTO credential_renewals (organization_id,member_credential_id,requested_on,due_on,notes,requested_by) VALUES (?,?,CURDATE(),?,?,?)')->execute([$oid,$credential,$in['due_on']?:null,trim((string)($in['notes']??''))?:null,$uid]);}
    public function credentialCompliance(int $oid): array {$q=$this->db->prepare('SELECT pcr.*,p.name position_name,ct.name credential_name FROM position_credential_requirements pcr JOIN positions p ON p.id=pcr.position_id JOIN credential_types ct ON ct.id=pcr.credential_type_id WHERE pcr.organization_id=? AND pcr.required=1 ORDER BY p.name,ct.name');$q->execute([$oid]);$requirements=$q->fetchAll();$q=$this->db->prepare('SELECT m.id membership_id,u.name,COUNT(pcr.credential_type_id) required_count,SUM(CASE WHEN mc.id IS NOT NULL AND mc.status="verified" AND (mc.expires_on IS NULL OR mc.expires_on>=CURDATE()) THEN 1 ELSE 0 END) compliant_count FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN staff_assignments sa ON sa.membership_id=m.id AND sa.is_primary=1 LEFT JOIN position_credential_requirements pcr ON pcr.position_id=sa.position_id AND pcr.organization_id=m.organization_id AND pcr.required=1 LEFT JOIN member_credentials mc ON mc.membership_id=m.id AND mc.credential_type_id=pcr.credential_type_id AND mc.organization_id=m.organization_id WHERE m.organization_id=? AND m.status="active" GROUP BY m.id,u.name ORDER BY u.name');$q->execute([$oid]);$forecast=$q->fetchAll();$q=$this->db->prepare('SELECT cr.*,ct.name credential_name,u.name staff_name FROM credential_renewals cr JOIN member_credentials mc ON mc.id=cr.member_credential_id JOIN credential_types ct ON ct.id=mc.credential_type_id JOIN memberships m ON m.id=mc.membership_id JOIN users u ON u.id=m.user_id WHERE cr.organization_id=? ORDER BY FIELD(cr.status,"requested","submitted","rejected","verified"),cr.due_on');$q->execute([$oid]);return compact('requirements','forecast')+['renewals'=>$q->fetchAll()];}
    public function addCredentialDocument(int $oid,int $uid,int $credential,string $original,string $storage,string $mime,int $size): void {$q=$this->db->prepare('SELECT COUNT(*) FROM member_credentials WHERE id=? AND organization_id=?');$q->execute([$credential,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Credential unavailable.');$this->db->prepare('INSERT INTO credential_documents (organization_id,member_credential_id,original_name,storage_name,mime_type,file_size,uploaded_by) VALUES (?,?,?,?,?,?,?)')->execute([$oid,$credential,$original,$storage,$mime,$size,$uid]);}
    public function credentialDocuments(int $oid): array {$q=$this->db->prepare('SELECT cd.*,ct.name credential_name,u.name staff_name FROM credential_documents cd JOIN member_credentials mc ON mc.id=cd.member_credential_id JOIN credential_types ct ON ct.id=mc.credential_type_id JOIN memberships m ON m.id=mc.membership_id JOIN users u ON u.id=m.user_id WHERE cd.organization_id=? ORDER BY cd.created_at DESC');$q->execute([$oid]);return $q->fetchAll();}
    public function credentialDocument(int $oid,int $id): ?array {$q=$this->db->prepare('SELECT * FROM credential_documents WHERE id=? AND organization_id=?');$q->execute([$id,$oid]);return $q->fetch()?:null;}

    public function saveBreakRule(int $oid,int $uid,array $in): void {$threshold=max(60,(int)($in['shift_minutes_threshold']??360));$required=max(0,(int)($in['required_break_minutes']??30));$this->db->prepare('INSERT INTO break_compliance_rules (organization_id,shift_minutes_threshold,required_break_minutes,updated_by) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE shift_minutes_threshold=VALUES(shift_minutes_threshold),required_break_minutes=VALUES(required_break_minutes),updated_by=VALUES(updated_by)')->execute([$oid,$threshold,$required,$uid]);}
    public function lockLaborPeriod(int $oid,int $uid,array $in): void {$start=(string)($in['starts_on']??'');$end=(string)($in['ends_on']??'');if(!$start||!$end||$end<$start)throw new InvalidArgumentException('Enter a valid labor period.');$this->db->prepare('INSERT INTO labor_periods (organization_id,starts_on,ends_on,status,locked_by,locked_at) VALUES (?,?,?,"locked",?,NOW()) ON DUPLICATE KEY UPDATE status="locked",locked_by=VALUES(locked_by),locked_at=NOW()')->execute([$oid,$start,$end,$uid]);}
    public function scanTimeExceptions(int $oid): int {$q=$this->db->prepare('SELECT te.*,GREATEST(0,TIMESTAMPDIFF(MINUTE,te.clocked_in_at,te.clocked_out_at)-te.break_minutes) worked_minutes,COALESCE(br.shift_minutes_threshold,360) threshold,COALESCE(br.required_break_minutes,30) required_break FROM time_entries te LEFT JOIN break_compliance_rules br ON br.organization_id=te.organization_id WHERE te.organization_id=? AND te.clocked_out_at IS NOT NULL AND DATE(te.clocked_in_at)>=DATE_SUB(CURDATE(),INTERVAL 60 DAY)');$q->execute([$oid]);$count=0;$insert=$this->db->prepare('INSERT INTO time_entry_exceptions (organization_id,membership_id,time_entry_id,exception_type,exception_date,notes) SELECT ?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM time_entry_exceptions WHERE time_entry_id=? AND exception_type=?)');foreach($q->fetchAll() as $entry){$worked=max(0,(int)$entry['worked_minutes']);if($worked>=(int)$entry['threshold']&&(int)$entry['break_minutes']<(int)$entry['required_break']){$insert->execute([$oid,$entry['membership_id'],$entry['id'],'short_break',substr($entry['clocked_in_at'],0,10),'Required break was not recorded.',$entry['id'],'short_break']);$count+=$insert->rowCount();}}return $count;}
    public function resolveTimeException(int $oid,int $uid,array $in): void {$decision=in_array($in['decision']??'', ['resolved','dismissed'],true)?$in['decision']:'resolved';$this->db->prepare('UPDATE time_entry_exceptions SET status=?,notes=?,resolved_by=?,resolved_at=NOW() WHERE id=? AND organization_id=?')->execute([$decision,trim((string)($in['notes']??''))?:null,$uid,(int)$in['exception_id'],$oid]);}
    public function laborOperations(int $oid): array {$this->scanTimeExceptions($oid);$q=$this->db->prepare('SELECT * FROM break_compliance_rules WHERE organization_id=?');$q->execute([$oid]);$rule=$q->fetch()?:['shift_minutes_threshold'=>360,'required_break_minutes'=>30];$q=$this->db->prepare('SELECT te.*,u.name staff_name FROM time_entry_exceptions te JOIN memberships m ON m.id=te.membership_id JOIN users u ON u.id=m.user_id WHERE te.organization_id=? ORDER BY FIELD(te.status,"open","resolved","dismissed"),te.exception_date DESC');$q->execute([$oid]);$exceptions=$q->fetchAll();$q=$this->db->prepare('SELECT * FROM labor_periods WHERE organization_id=? ORDER BY starts_on DESC');$q->execute([$oid]);return compact('rule','exceptions')+['periods'=>$q->fetchAll()];}

    public function saveFairnessSettings(int $oid,int $uid,array $in): void {$keys=['hours_weight','opening_weight','closing_weight','weekend_weight','declined_offer_weight','cost_weight'];$v=[];foreach($keys as $key)$v[]=max(0,min(20,(float)($in[$key]??0)));$this->db->prepare('INSERT INTO fairness_settings (organization_id,hours_weight,opening_weight,closing_weight,weekend_weight,declined_offer_weight,cost_weight,updated_by) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE hours_weight=VALUES(hours_weight),opening_weight=VALUES(opening_weight),closing_weight=VALUES(closing_weight),weekend_weight=VALUES(weekend_weight),declined_offer_weight=VALUES(declined_offer_weight),cost_weight=VALUES(cost_weight),updated_by=VALUES(updated_by)')->execute([$oid,...$v,$uid]);}
    public function recordRecommendationOutcome(int $oid,int $uid,array $in): void {$shift=(int)($in['shift_id']??0);$q=$this->db->prepare('SELECT COUNT(*) FROM shifts WHERE id=? AND organization_id=?');$q->execute([$shift,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Shift unavailable.');$outcome=in_array($in['outcome']??'', ['accepted','declined','overridden','not_used'],true)?$in['outcome']:'not_used';$this->db->prepare('INSERT INTO recommendation_outcomes (organization_id,shift_id,recommended_membership_id,selected_membership_id,recommendation_score,outcome,manager_reason,recorded_by) VALUES (?,?,?,?,?,?,?,?)')->execute([$oid,$shift,!empty($in['recommended_membership_id'])?(int)$in['recommended_membership_id']:null,!empty($in['selected_membership_id'])?(int)$in['selected_membership_id']:null,!empty($in['recommendation_score'])?(float)$in['recommendation_score']:null,$outcome,trim((string)($in['manager_reason']??''))?:null,$uid]);}
    public function fairnessOperations(int $oid): array {$q=$this->db->prepare('SELECT * FROM fairness_settings WHERE organization_id=?');$q->execute([$oid]);$settings=$q->fetch()?:['hours_weight'=>1,'opening_weight'=>2,'closing_weight'=>2,'weekend_weight'=>2,'declined_offer_weight'=>0,'cost_weight'=>0];$q=$this->db->prepare('SELECT outcome,COUNT(*) outcome_count,AVG(recommendation_score) average_score FROM recommendation_outcomes WHERE organization_id=? GROUP BY outcome');$q->execute([$oid]);$outcomes=$q->fetchAll();$q=$this->db->prepare('SELECT membership_id,COUNT(*) declined_count FROM callout_offers co JOIN callouts c ON c.id=co.callout_id WHERE c.organization_id=? AND co.status="declined" GROUP BY membership_id');$q->execute([$oid]);return compact('settings','outcomes')+['declines'=>$q->fetchAll()];}

    public function acknowledgeShift(int $oid,int $member,int $shift): void {$this->member($oid,$member);$q=$this->db->prepare('SELECT COUNT(*) FROM shifts WHERE id=? AND organization_id=? AND assigned_membership_id=? AND status IN ("assigned","filled")');$q->execute([$shift,$oid,$member]);if(!$q->fetchColumn())throw new InvalidArgumentException('Assigned shift unavailable.');$this->db->prepare('INSERT INTO schedule_acknowledgments (organization_id,membership_id,shift_id,acknowledged_at) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE acknowledged_at=NOW()')->execute([$oid,$member,$shift]);}
    public function acknowledgments(int $oid,int $member): array {$this->member($oid,$member);$q=$this->db->prepare('SELECT shift_id,acknowledged_at FROM schedule_acknowledgments WHERE organization_id=? AND membership_id=?');$q->execute([$oid,$member]);return array_column($q->fetchAll(),'acknowledged_at','shift_id');}
    private function member(int $oid,int $member): void {$q=$this->db->prepare('SELECT COUNT(*) FROM memberships WHERE id=? AND organization_id=? AND status="active"');$q->execute([$member,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Membership unavailable.');}
    private function resource(string $table,int $oid,int $id): void {if(!in_array($table,['positions','credential_types'],true))throw new LogicException('Invalid resource.');$q=$this->db->prepare("SELECT COUNT(*) FROM {$table} WHERE id=? AND organization_id=?");$q->execute([$id,$oid]);if(!$q->fetchColumn())throw new InvalidArgumentException('Organization resource unavailable.');}
}
